### ISSUE TITLE
GraphQL example errors out

### ISSUE THREAD

**Issue by jongold** [airbnb/react-sketchapp#10]
**Expected behavior:**

`/examples/profile-cards-graphql` when installed, executes correctly.

**Observed behavior:**

in Console.app:

<img width="650" alt="screen shot 2017-04-06 at 8 09 44 pm" src="https://cloud.githubusercontent.com/assets/551247/24784122/4a26b71a-1b05-11e7-98d5-7c4c76866fd6.png">

**How to reproduce:**

```
cd ~/examples/profile-cards-graphql
npm i
npm run watch
skpm link .
```

then execute the plugin in a new document in sketch

**Sketch version:**
43 (38999)

* * *

reported by @ChristopherBiscardi — I can't reproduce it 🤔

**Comment by jongold** [comment]
Oops - actually I can replicate it - the GraphQL example is currently crashing Sketch 😅 

I'm going to assume it's something in skpm or sketch-module-fetch-polyfill - @darknoon can you help me read this crash log?
https://gist.github.com/jongold/6235d9d92398e658b10e063cf734542c

cc @mathieudutour

**Comment by mathieudutour** [comment]
no, the error is in `react-sketchapp`, you can print the `allProfiles` but the `render` method is creashing

**Comment by mathieudutour** [comment]
specifically, it's when rendering the `Avatar` that it's crashing

**Comment by jongold** [comment]
@mathieudutour oh wow my bad - my brain isn't switched on. Thanks for finding it.

There was an image being fetched that didn't exist - fixed now.

Closing this, and making #13 high priority.
