### ISSUE TITLE
Example generating sketch file from command line

### ISSUE THREAD

**Issue by joekim** [airbnb/react-sketchapp#100]
For an example like `basic-setup`, can we get documentation on how to create a sketch file without needing an open document in sketch?

Not sure if it's support yet, but ideally without invoking sketch at all and just writing to the sketch file format directly.

**Comment by jongold** [comment]
Unfortunately it's not possible as far as I know :(

Internally at Airbnb we have a script that opens Sketch if it's not currently open, renders, and saves the document which is useful for rendering on CI — not quite ready to release that code yet though.

**Comment by dhruska** [comment]
Apologies for reviving an old thread, but - any chance that code was open-sourced? We would love to be able to do this!
