### ISSUE TITLE
shadowOpacity has no effect

### ISSUE THREAD

**Issue by CLL80** [airbnb/react-sketchapp#107]
I am trying to use the shadowOpacity style property, but it has no effect. When rendered to Sketch, the shadow always shows with Alpha 100.

**Expected behavior:**
Setting:
```
style={{
  shadowOpacity: 0.5,
  shadowOffset: {
    width: 10,
    height: 14
  }
}}
```
**Observed behavior:**
...should show as a shadow with 50% opacity in Sketch.

**How to reproduce:**
From the example project linked below, render `examples/color` to Sketch. I've added a shadow to reproduce the issue.
https://github.com/CLL80/react-sketchapp/tree/issue/shadowOpacity
https://github.com/CLL80/react-sketchapp/blob/issue/shadowOpacity/examples/colors/src/main.js

**Sketch version:**
43.2

**Comment by jongold** [comment]
Thanks for the clear bug report!

**Comment by CLL80** [comment]
No problem. Thanks for the great tool!

**Comment by Psarna94** [comment]
+1

**Comment by mjaltamirano** [comment]
@jongold Do you think it is related to the following error message I am seeing for the when rendering the example?

`Warning: Failed prop type: Invalid prop `style` of type `number` supplied to `View`, expected `object`.
    in View (created by Document)
    in Document`

**Comment by dchen** [comment]
I think Sketch shadows may not respect the opacity contextSetting. There is no opacity parameter exposed in the Sketch UI as far as I know. The opacity adjustment is just the alpha of the shadow color. If so, perhaps we can just calculate the opacity into the alpha.

**Comment by jongold** [comment]
@mjaltamirano nope, that's #9 😅 

@dchen is right - that looks like how React Native works
![image](https://user-images.githubusercontent.com/591643/27050393-2a27e254-4f67-11e7-9681-7818f020d7c9.png)

**Comment by gretzky** [comment]
any updates? still broken for me

**Comment by jongold** [comment]
@gretzky sorry! forgot to publish a new version - try 0.11.6 :)
