### ISSUE TITLE
Fix default line height

### ISSUE THREAD

**Issue by jongold** [airbnb/react-sketchapp#11]
It's noticeable here -
![image](https://cloud.githubusercontent.com/assets/591643/24584234/7b893c6c-171b-11e7-8c2a-3876e6722657.png)

~Looks like Sketch defaults to `1.2` line-height whereas browsers (and Native? maybe?) default to `1`.~

from [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height)
> **normal**
> Depends on the user agent. Desktop browsers (including Firefox) use a default value of roughly 1.2, depending on the element's font-family.

Line height seems to be correct, I think bounding boxes are being drawn incorrectly

Check this out:
- the two titles have just been rendered with `lineHeight: 22`. the one on the right has had its bounding box adjusted already; the one on the left is as-it-renders.

After double-clicking on an anchor point on `Four Barrel Coffee`, or resizing it horizontally, the bounding box snaps up several pixels, at which point I reflow the text underneath it.

I _think_ the bounding box is initially getting drawn too big, but I'm not sure why 🤔 
![kapture 2017-04-01 at 20 57 15](https://cloud.githubusercontent.com/assets/591643/24584294/e7f9353a-171d-11e7-96a7-4a0e62b55d6f.gif)

**Comment by lmjabreu** [comment]
Is this not a Sketch bug? I may be missing something but I often run into this issue using Sketch without react-sketchapp, I need to +1/-1 the line height and then set it back to the initial value for Sketch to render it properly.

_Can we get rid of Sketch altogether with react-sketchapp? Eventually? It ends up being just a bad renderer and adapter for output formats/plugins._
