### ISSUE TITLE
Throw error on non-https images

### ISSUE THREAD

**Issue by jongold** [airbnb/react-sketchapp#12]
Fun fact - you can only load images over https in Sketch!

We should throw an error if you try to load an image over http.

**Comment by agisilaos** [comment]
Hey @jongold I would love to work on this! Can you give me more info to start so I can start working on it? Thank you in advance for creating such tool!!

**Comment by jongold** [comment]
[Here's where](https://github.com/airbnb/react-sketchapp/blob/master/src/renderers/ImageRenderer.js#L89-L91) we're extracting the URL from props and instantiating `MSImageData` from it

[This is the function](https://github.com/airbnb/react-sketchapp/blob/master/src/jsonUtils/hacksForJSONImpl.js#L49-L53) that actually makes the image data.

I think it might be enough to just shortcircuit that function if the URL doesn't start with `https://` or `file://` (or maybe better to shortcircuit if it _does_ start with `http://`). check it doesn't break anything else!

development workflow -
- make a branch, install the dependencies, check `npm run check` is working
- `npm link`
- `npm run watch` to build the library
- `cd` into one of the examples (or any react-sketchapp project itself), `npm install` and then `npm link react-sketchapp`
- make changes, try to break it! testing is kinda brittle due to the nature of it being built upon Sketch!
- if you change any of the examples, please don't commit them!

**Comment by agisilaos** [comment]
Thanks @jongold I will keep you updated on that one. Oh, it didn't start well. Any idea what is happening here? 
<img width="1386" alt="screen shot 2017-04-28 at 02 37 13" src="https://cloud.githubusercontent.com/assets/10944108/25508581/af865fea-2bbb-11e7-9cb3-90e46c42799c.png">

**Comment by jongold** [comment]
looks like you're not in the right directory?

**Comment by agisilaos** [comment]
@jongold Yup you were right! but after that I got another error... Weird: 
<img width="1386" alt="screen shot 2017-04-29 at 01 53 55" src="https://cloud.githubusercontent.com/assets/10944108/25550060/baa176e4-2c7e-11e7-8583-ad43118ffbf9.png">

**Comment by agisilaos** [comment]
Nvm, I just fixed it! I had to 'npm update' when I was inside that directory!

**Comment by agisilaos** [comment]
Ok my progress so far @jongold: 

- [x] Make a branch & install dependencies & check `npm run check`
- [x] `npm link`
- [x] `npm run watch`
- [x] `cd` into one of the examples (or any react-sketchapp project itself), npm install and then npm link react-sketchapp
- [ ] make changes, try to break it! testing is kinda brittle due to the nature of it being built upon Sketch!
- [ ] if you change any of the examples, please don't commit them!

**Comment by jongold** [comment]
This is fixed in #111 / `0.11.1` :)
