### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by tk-pivotus** [airbnb/react-sketchapp#120]
Thanks for creating this awesome project!  We are evaluating this tool for our internal consumption.

How would you use/render custom fonts in react-sketchapp?

**Comment by jongold** [comment]
Hey! If you have the font installed locally you can just use it as normal! Be careful to use the PostScript name of the font…

```js
const style = {
  fontFamily: "GT America",
  fontSize: 24,
}

const Component = props => <Text style={style}>{props.children}</Text>
```

There's no support for @font-face yet
