### ISSUE TITLE
Could not find a JSTalk connection to com.bohemiancoding.sketch3.JSTalk

### ISSUE THREAD

**Issue by WhynoChinese** [airbnb/react-sketchapp#121]
![image](https://user-images.githubusercontent.com/11802308/27065829-594364b6-5032-11e7-95b0-0327a399491c.png)

**Comment by jongold** [comment]
Where is your Sketch installed?
- Is it in a directory other than `/Applications`?
- Is it called soemthing other than `Sketch` (maybe `Sketch beta`?)
