### ISSUE TITLE
Requesting a new feature

### ISSUE THREAD

**Issue by yarism** [airbnb/react-sketchapp#123]
Hey, love the project! Would love to use this in my react web app. Is it possible to make it run with regular react and not react-native?

**Comment by ckarlbe** [comment]
+1

**Comment by jongold** [comment]
Agreed — would be awesome, but there were some tough technical choices to be made.

I'd say that this isn't on the roadmap anytime soon, but I outlined some ideas [in a previous issue](https://github.com/airbnb/react-sketchapp/issues/29#issuecomment-297435389).

Any solution that we figure out for React Sketch.app is equally applicable to React Native, React Native Web, React Primitives etc etc, so should be developed outside the scope of this project.
