### ISSUE TITLE
Symbol image override failed

### ISSUE THREAD

**Issue by taojoe** [airbnb/react-sketchapp#129]
**Expected behavior:**
image override works
**Observed behavior:**
when I test with examples/symbols,  the override for image is not override with new url, but new url shows as text. 
**How to reproduce:**
git clone react-sketchapp
cd examples/symbols
npm install
npm run render
**Sketch version:**
43.2
**Please attach screenshots, a zip file of your project, and/or a link to your github project**
![image](https://user-images.githubusercontent.com/545656/27509590-298c1114-5933-11e7-9862-58b93e875258.png)
![image](https://user-images.githubusercontent.com/545656/27509597-64f3800c-5933-11e7-8752-4189e15436c9.png)

**Comment by jongold** [comment]
Oh no! Looks like @ianhook is on the way to solving it in #130.

As an aside, you have to use https image URLs, not http, due to a Cocoa limitation.

**Comment by tafelito** [comment]
I know this is an old issue and it was supposed to be fixed but I'm having the same issue when running the examples with Sketch version  48.2 . I tested the symbols example, and the overrides doesn't seem to be doing anything. 

```
<NestedSym
        name="Nested Symbol"
        overrides={{
          'Red Square Instance': BlueSquareSym,
          'Blue Square Text': 'TESTING',
          Photo:
            'https://pbs.twimg.com/profile_images/833785170285178881/loBb32g3.jpg',
        }}
      />
```
None of the values on overrides are shown in sketch after rendering

<img src="https://user-images.githubusercontent.com/5973652/36273629-18f88aa6-1253-11e8-80b6-cb616d3d22c5.png" width="40%"/>
