### ISSUE TITLE
Gracefully handle Image errors

### ISSUE THREAD

**Issue by jongold** [airbnb/react-sketchapp#13]
Most noticeably, if you don't have an internet connection, trying to render an image crashes Sketch

**Comment by dchen** [comment]
I'm looking into this. Reproduced the error in profile-cards example with no Internet access.

Crash log:
```
$ npm run render

> profile-cards@ render /Users/david_chen/Projects/dchen/react-sketchapp/examples/profile-cards
> skpm build --watch --run

🖨  Copied src/manifest.json in 13ms
Executing post-build scripts
⚒  Built ./main.js in 3351ms
2017-05-03 11:56:46.760 sketchtool[69353:689538] *** Terminating app due to uncaught exception 'NSInvalidReceivePortException', reason: 'connection went invalid while waiting for a reply because a mach port died'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffa61ac37b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffbafa048d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffa622ac3d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fffa7ba95b9 -[NSConnection sendInvocation:internal:] + 2414
	4   CoreFoundation                      0x00007fffa611e5fa ___forwarding___ + 538
	5   CoreFoundation                      0x00007fffa611e358 _CF_forwarding_prep_0 + 120
	6   sketchtool                          0x0000000106742792 -[BCSTRunCommand waitForLaunchOfApplicationWithEngine:] + 306
	7   Foundation                          0x00007fffa7b9f5e8 __NSFireDelayedPerform + 417
	8   CoreFoundation                      0x00007fffa612bd04 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	9   CoreFoundation                      0x00007fffa612b98f __CFRunLoopDoTimer + 1071
	10  CoreFoundation                      0x00007fffa612b4ea __CFRunLoopDoTimers + 298
	11  CoreFoundation                      0x00007fffa6122c31 __CFRunLoopRun + 2065
	12  CoreFoundation                      0x00007fffa61221c4 CFRunLoopRunSpecific + 420
	13  CoreFoundation                      0x00007fffa6161c31 CFRunLoopRun + 97
	14  sketchtool                          0x000000010670380f ECCommandLineMain + 289
	15  sketchtool                          0x0000000106745d01 main + 33
	16  libdyld.dylib                       0x00007fffbb885235 start + 1
	17  ???                                 0x0000000000000004 0x0 + 4
)
libc++abi.dylib: terminating with uncaught exception of type NSException
> 

> 
```

**Comment by dchen** [comment]
@jongold Replacing [initWithContentsOfURL](https://developer.apple.com/reference/appkit/nsimage/1519907-initwithcontentsofurl?language=objc) [here](https://github.com/airbnb/react-sketchapp/blob/5ff80edf6092fb6a015db576c6a5da3816d9cbe9/src/jsonUtils/hacksForJSONImpl.js#L50) with [initByReferencingURL](https://developer.apple.com/reference/appkit/nsimage/1519990-initbyreferencingurl?language=objc) causes the image to be blank if Internet access is unavailable instead of crashing. What do you think of switching to this? 

I believe the difference is it lazy loads the image, only retrieving at the time it is drawn, which just slightly defers it in our use case. Not sure if there are other effects.

**Comment by ljharb** [comment]
I wonder if we could replace it with a "broken image" placeholder image instead of "nothing", like browsers do?

**Comment by dchen** [comment]
Jon mentions that the change to the current method was done for a reason ([this commit](https://github.com/airbnb/react-sketchapp/commit/690627c6027717d9236e548aafc5d8fdd79fa116)) but unsure what it is.

@darknoon Any thoughts on this?

**Comment by darknoon** [comment]
Synchronously loading an image via `initWithContentsOfURL` is 100% the wrong thing to do. I don't remember what the issue with ` initByReferencingURL:` was, but I think @dchen might be right that it just crashes when it tries to show the image. The API is only incidentally capable of making images from remote URLs (it's intended for `file://` and `data://` URLs, and it is sort of accidentally exposed here in `NSImage`. Just like the browser doesn't beachball while load images, `react-sketchapp` shouldn't be doing it.

The comment here is also particularly relevant:
https://developer.apple.com/reference/foundation/nsdata/1547245-datawithcontentsofurl

The approach that I recommend is using the `fetch()` polyfill and collect promises in an image manager to load the images then redo the render when they're all loaded (or as they load like you would in `react-native`). You can then handle failure at that level and decide if you still want to render the components / substitute placeholders.

Another common case is a poor network or high packet loss condition where it doesn't fail explicitly, but hangs. This makes all of sketch hang, which is major sadtown.

**Comment by dchen** [comment]
Does anyone know what the issues were with initByReferencingURL:? I think it would be better for the image to be blank rather than Sketch crashing entirely when there's a problem loading.
