### ISSUE TITLE
Error while running command after build

### ISSUE THREAD

**Issue by xuv** [airbnb/react-sketchapp#132]
_I am Julien Deswaef_

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------
Downloaded a fresh install of react-sketchapp. Trying to run the basic example

**Observed behavior:** Here is the full log:
```
$ npm run render

> basic-setup@1.0.0 render […]/react-sketchapp/examples/basic-setup
> skpm build --watch --run

🖨  Copied src/manifest.json in 8ms
babel-preset-env: `DEBUG` option

Using targets:
{
  "android": "30",
  "chrome": "35",
  "edge": "14",
  "explorer": "9",
  "firefox": "52",
  "safari": "8",
  "ucandroid": "1"
}

Modules transform: false

Using plugins:
  check-es2015-constants {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-es2015-arrow-functions {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-es2015-block-scoped-functions {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-es2015-block-scoping {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-es2015-classes {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-es2015-computed-properties {"android":"30","chrome":"35","explorer":"9","ucandroid":"1"}
  transform-es2015-destructuring {"android":"30","chrome":"35","edge":"14","explorer":"9","firefox":"52","safari":"8","ucandroid":"1"}
  transform-es2015-duplicate-keys {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-es2015-for-of {"android":"30","chrome":"35","edge":"14","explorer":"9","firefox":"52","safari":"8","ucandroid":"1"}
  transform-es2015-function-name {"android":"30","chrome":"35","edge":"14","explorer":"9","firefox":"52","safari":"8","ucandroid":"1"}
  transform-es2015-literals {"android":"30","chrome":"35","explorer":"9","firefox":"52","safari":"8","ucandroid":"1"}
  transform-es2015-object-super {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-es2015-parameters {"android":"30","chrome":"35","explorer":"9","firefox":"52","safari":"8","ucandroid":"1"}
  transform-es2015-shorthand-properties {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-es2015-spread {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-es2015-sticky-regex {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-es2015-typeof-symbol {"chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-es2015-unicode-regex {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  transform-exponentiation-operator {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
  syntax-trailing-function-commas {"android":"30","chrome":"35","explorer":"9","safari":"8","ucandroid":"1"}
error Error while running the command after build
2017-06-26 15:28:16.419 coscript[62413:25812287] Exception: (null)

[NOTE: this exception originated in the server.]
[NOTE: this exception originated in the server.]
*** Object does not implement or has different method signature for selector 'hasExtension:'


⛏  Built ./my-command.js in 1473ms
```

**How to reproduce:** 
`npm run render` on `basic-setup` example

**Sketch version:** 44.1

**Comment by davidseik** [comment]
Yeah, the render functionality to have `hot updates` is broken since sketch 44.
Check this issue: https://github.com/airbnb/react-sketchapp/issues/72

You can always do `npm run build` & `npm run link-plugin` and then manually run the plugin in sketch under `plugins` and the name of your plugin. Hope that helps.

**Comment by xuv** [comment]
Ok, thanks for that. I was not sure this was the same error or not.  There is a "fix" mentioned in [this comment](https://github.com/airbnb/react-sketchapp/issues/72#issuecomment-307907253) but don't know where to apply it. Any clue?

**Comment by davidseik** [comment]
No idea where, maybe @jongold should tell us where :stuck_out_tongue:

**Comment by jongold** [comment]
Yeah, it's the same error - I haven't had time to work on it, sorry :(

That fix is the fix we need to do for `skpm`. apologies for the blip — that said, running the plugin via SketchRunner (or with `Plugins -> Run Last Plugin Again`) is pretty speedy :)

**Comment by xuv** [comment]
@jongold: Thanks for the quick reply. Yes. SketchRunner or Run Last Plugin Again is ok :) But nothing compared to automatic reloading like you had it before. It was sooo sooo fast... 

`⌘s` + watch reload or `⌘s > ⌘+TAB > ⌘+' >` + starting typing plugin name... There is a few key stroke difference :) The first one felt so smooth. 

But I'm here complaining... although your tool is great. Love it. Wish I could help you fix this.

**Comment by mathieudutour** [comment]
I'm sure you can :)
A few guiding steps:
- this is the commit where we switch to use `run-sketch-command` instead of `sketchtool`: https://github.com/skpm/skpm/commit/fc9fc91bacb38c002d6ab5cae122960db0b9e8b9
- you already found the comment where @jongold explains what we want: https://github.com/airbnb/react-sketchapp/issues/72#issuecomment-307907253
- the `sketchtool` method is the one we want for sketch >= 44 and `run-sketch-command` is for sketch < 44

Don't have much time to tackle this myself right now unfortunately :(

**Comment by jongold** [comment]
I mostly fixed it on a branch last night, hopefully will PR today

**Comment by xuv** [comment]
@jongold OMG, that would be amazing. I'm still looking at @mathieudutour suggestion but I must say I have some difficulties finding my way around. :)

**Comment by jongold** [comment]
Check out the discussion in #72 — closing this :)
