### ISSUE TITLE
Border specific top right bottom left options don't exist in Sketch

### ISSUE THREAD

**Issue by xuv** [airbnb/react-sketchapp#136]
Filling an issue before updating the Doc, just in case I missed something here.

But `borderTopLeftRadius`, `borderTopRightRadius`, `borderBottomLeftRadius`, `borderBottomRightRadius`, `borderTopWidth`, `borderTopWidth`, `borderRightWidth`,etc. won't have any effect in Sketch as these options are not implemented. (See [Sketch Doc about borders](https://www.sketchapp.com/learn/documentation/styling/borders/))

**Sketch version:** 44.1

[Doc](https://github.com/airbnb/react-sketchapp/blob/master/docs/styling.md) should maybe have a ⛔️ next to those options.

**Comment by jongold** [comment]
Thanks @xuv — actually we implemented individual border styles & border radiuses for rectangles — not having them was a dealbreaker for us :)

Here's a crude example:
![image](https://user-images.githubusercontent.com/591643/27706252-c59d6eaa-5cc5-11e7-9eda-7b53cb787e45.png)

**Comment by xuv** [comment]
Oh, jeez, you did. I think it's because I tried with the wrong component type. Thx for taking the time to show me.

**Comment by jongold** [comment]
Totally possible that there are bugs though - let us know if you find something reproducible :)
