### ISSUE TITLE
Quickstart npm run render error

### ISSUE THREAD

**Issue by idkjs** [airbnb/react-sketchapp#138]
| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------
Running the quick start and following these instructions:
```
Open a new Sketch file, then in a terminal:

git clone https://github.com/airbnb/react-sketchapp.git
cd react-sketchapp/examples/basic-setup && npm install

npm run render

```
**Expected behavior:**

**Observed behavior:**
Getting this error
```sh
(node:15917) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'apply' of undefined
(node:15917) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
🖨  Copied src/manifest.json in 3405ms
```
**How to reproduce:**
Follow the instruction
**Sketch version:**
Sketch version is 44.1
macOS High Sierra Beta

**Comment by DokRaphael** [comment]
Had the same problem
Can you try `skpm build` in /basic-setup folder ?

**Comment by miguelmendes** [comment]
Same, I cant run the basic stuff

**Comment by DokRaphael** [comment]
It works for me by doing 
`skpm build`

**Comment by miguelmendesnet** [comment]
I tried that but :/

<img width="855" alt="screen shot 2017-07-04 at 19 16 52" src="https://user-images.githubusercontent.com/18168375/27837511-5d538894-60ed-11e7-9b1c-ff3b5ab2bcaa.png">

**Comment by mathieudutour** [comment]
what's your node version? (node -v) probably need a recent one (>=6.0.0)

**Comment by miguelmendesnet** [comment]
I was using v5.10.1, but I just changed to 7.0 and getting the same errors as now @idkjs 

<img width="1052" alt="screen shot 2017-07-04 at 19 24 07" src="https://user-images.githubusercontent.com/18168375/27837700-6789066c-60ee-11e7-93d0-6bf2ee43106c.png">

**Comment by mathieudutour** [comment]
are you all on high sierra? or it's happening on sierra as well?

**Comment by DokRaphael** [comment]
And now try `skpm build `

**Comment by DokRaphael** [comment]
I am on Sierra

**Comment by miguelmendesnet** [comment]
I am on Sierra too.

output of the skpm build 

`[1/2] 🖨  Copied src/manifest.json in 363ms
[2/2] 🛠  Built ./my-command.js in 1633ms
success Plugin built`

**Comment by mathieudutour** [comment]
just to pin point the bug: does `skpm build --watch` work?

**Comment by miguelmendesnet** [comment]
yes worked

🖨  Copied src/manifest.json in 248ms
🔩  Built ./my-command.js in 1432ms
...

**Comment by mathieudutour** [comment]
sketch 44 as well?

**Comment by miguelmendesnet** [comment]
yes sketch 44.1 opened

**Comment by mathieudutour** [comment]
could you try to install the master branch of skpm (`npm i https://github.com/skpm/skpm`) and try again?

**Comment by miguelmendesnet** [comment]
worked!

**Comment by miguelmendesnet** [comment]
thanks @mathieudutour

**Comment by LincMitch** [comment]
Trying to follow this but can't to a `skpm build` as get `Unknown argument: build`. 
My skpm version is 1.0.12, which is confusing as I installed the latest master branch `npm i https://github.com/skpm/skpm` and I believe should be v0.10.3.

**Comment by mathieudutour** [comment]
no the latest version of skpm is now 1.0.12. There is no `skpm build` anymore. Use `npm run build` instead
