### ISSUE TITLE
Working with pages

### ISSUE THREAD

**Issue by oltodo** [airbnb/react-sketchapp#139]
Is there any plan that enable us to work with Sketch [Pages](https://www.sketchapp.com/learn/documentation/grouping/pages/) ?

As our design grows, it might be nice to group together views with the same theme between them by using the pages.

For now, it only possible to add blank page using the `context`'s `document` object. But we cannot rename or remove one of them.

__Extract of [`src/types.js`](https://github.com/airbnb/react-sketchapp/blob/master/src/types.js#L16) file__

```js
export type SketchPage = {
  name: () => NSString
};

export type SketchDocument = {
  documentData: () => SketchDocumentData,
  pages: () => MSArray<SketchPage>,
  addBlankPage: () => SketchPage,
  currentPage: SketchPage
};
```

__Edit:__ Looking better I found a way to change the page name using the `setName` method (e.g. [`src/symbol.js`](https://github.com/airbnb/react-sketchapp/blob/2500505c7e23578a702771e10d0bf8292ac3594f/src/symbol.js#L94))

**Comment by oltodo** [comment]
An in-depth research and an [issue](https://github.com/BohemianCoding/developer.sketchapp.com/issues/100#issuecomment-313026834) allow me to know that the `context` object come from the [Sketch Plugins API](http://developer.sketchapp.com/).

So we able to do everything that this API allows us. Therefore, we can remove a Sketch Page using the bellow exemple :

```js
var data = context.document.documentData();
data.removePageAtIndex(1);
var pages = context.document.pages();
data.setCurrentPage(pages.firstObject());
```

Sorry for the inconvenience.

**Comment by jongold** [comment]
@oltodo glad you figured it out :)

**Comment by oltodo** [comment]
Thank @jongold.

Do you think it would be relevant to include the notions of `Document` and `Page` that could able us to work with Sketch Pages.

So we could render our design using something like that :

```jsx
import { render, Document, Page } from "react-sketchapp";

import StyleguidePage from "./pages/Styleguide";
import LoginPage from "./pages/Login";
import designSystem from "./designSystem";

export default context => {
  render(
    <Document system={designSystem}>
        <Page name="Styleguide"><StyleguidePage /></Page>
        <Page name="Login"><LoginPage /></Page>
    </Document>,
    context.document
  );
}
```

Where the `system` object could be spread through the React `context`.

Just an idea :)

**Comment by cuquo** [comment]
I agree, right now I'm trying to create design docs and it's a pain to create multiple files. It would be great to have a Document and a Page render in order to wrap multiple pages and artboards
