### ISSUE TITLE
Handle transforms

### ISSUE THREAD

**Issue by jongold** [airbnb/react-sketchapp#14]
There's some complexity in this -

- Handle rotations with native Sketch rotations
- otherwise, rasterize the transform-containing layers & apply CGTransforms to them

**Comment by jlongster** [comment]
I would love the ability to rotate things. How hard would that be? If it's straight-forward can you point me to where you would implement it? I can check it out.

**Comment by thecalvinchan** [comment]
this is awesome stuff, any updates on when we can see this merged?
