### ISSUE TITLE
Warning "Invalid prop style of type array" when using styled-components

### ISSUE THREAD

**Issue by arielger** [airbnb/react-sketchapp#140]
| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Observed behavior:**
I get the following warning when running the styled-components example:

```
Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `View`, expected `object`.
    in View (created by Styled(View))
    in Styled(View) (created by Document)
    in Document
Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `Text`, expected `object`.
    in Text (created by Styled(Text))
    in Styled(Text) (created by Document)
    in view (created by View)
    in View (created by Styled(View))
    in Styled(View) (created by Document)
    in Document
```

**How to reproduce:**
Just run the styled-components example in this repository.
I'm using Node v6.9.1 and npm v3.10.10

**Sketch version:**
45.1

**Comment by jongold** [comment]
@arielger thanks! is it still working correctly? I think that's #9, which we should really fix, but it's just a proptypes error 🙏

**Comment by arielger** [comment]
The styled-components example is working correctly, i just get those warnings. Thanks for the reply 😉

**Comment by benjamingeorge** [comment]
I'm still getting this warning with: 

"react": "^16.2.0",
"react-sketchapp": "^1.0.0",
 "styled-components": "3.1.6",
 "react-primitives": "^0.5.0",

Sketch v49
