### ISSUE TITLE
basic-setup doesn't work on macOS High Sierra 

### ISSUE THREAD

**Issue by gruberb** [airbnb/react-sketchapp#141]
**Expected behavior:**
I would like to open Sketch, run these commands:
```
git clone https://github.com/airbnb/react-sketchapp.git
cd react-sketchapp/examples/basic-setup && npm install

npm run render
```
and see the basic example.

**Observed behavior:**
`skpm` is running and building without an error, but nothing is shown in the Sketch app. I opened an empty document beforehand, but nothing got displayed.

I also installed the plugin inside the basic-setup folder.

**How to reproduce:**
Be on macOS High Sierra (Beta 2) and run, open an empty Sketch document and run:
```
git clone https://github.com/airbnb/react-sketchapp.git
cd react-sketchapp/examples/basic-setup && npm install

npm run render
```
**Sketch version:**
45.1

**Please attach screenshots, a zip file of your project, and/or a link to your github project**
<img width="1140" alt="bildschirmfoto 2017-07-06 um 16 58 41" src="https://user-images.githubusercontent.com/2135077/27917487-63f3b5b8-626c-11e7-8fbd-2154c12f9e8b.png">

**Comment by gretzky** [comment]
> First, make sure you have installed Sketch version 43-44 **(v45 is broken currently),** & a recent npm.

From the [docs](http://airbnb.io/react-sketchapp/)

**Comment by sibelius** [comment]
try to upgrade to sketch 47
