### ISSUE TITLE
Authors File?

### ISSUE THREAD

**Issue by davidseik** [airbnb/react-sketchapp#144]
| -------------------------------------------------------------------------------------------------
| Requesting a new feature
| -------------------------------------------------------------------------------------------------

Authors files so we can add ourselves to the contribuiting lists similar to what React does:
https://github.com/facebook/react/blob/master/AUTHORS

I was going to add myself to the contributors array inside the package.json but I don't see anyone outside of airbnb on it so I'm thinking it might make sense to have the authors file for the rest of us.

Thoughts?

**Comment by mathieudutour** [comment]
never understood what this file was useful for :D always easier and more informative to check https://github.com/airbnb/react-sketchapp/graphs/contributors

**Comment by ljharb** [comment]
Github already has this info under "insights", and its all in the git history as well.

Including info in files that's already in version control metadata is redundant.

**Comment by davidseik** [comment]
@mathieudutour the usage of an authors file is mainly to not include all the authors/contributors of the code inside of the package.json as the list grows a lot. NPM will default to using that file in case there's one on the root.
https://docs.npmjs.com/files/package.json#default-values

Other than listing the people that contribute to the project and maybe being some sort of easy to access mail distribution list, I don't see any other usage. Would be interesting to hear from the React team or [NPM](https://github.com/npm/npm/blob/latest/AUTHORS) team about specific usages of the AUTHORS files.

For this matter, I think it's fine if there's no file; I was just wondering about it :)

Closing the issue.
