### ISSUE TITLE
profile-cards has an invalid image uri

### ISSUE THREAD

**Issue by phanhaiquang** [airbnb/react-sketchapp#148]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

I am Quang. In "profile-cards" example, Jackie profile image i invalid.

| -------------------------------------------------------------------------------------------------
| Requesting a new feature
| -------------------------------------------------------------------------------------------------

**Proposal/Feature-request:**

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**
In sketchapp, it should show Jackie profile image.

**Observed behavior:**
Sketchapp shows nothing, except a RED rectangle.
In main.js, this uri seems invalid
https://pbs.twimg.com/profile_images/756488692135526400/JUCawBiW_400x400.jpg

**How to reproduce:**

**Sketch version:**

**Please attach screenshots, a zip file of your project, and/or a link to your github project**
![image](https://user-images.githubusercontent.com/1145845/27990877-370a0f3c-648f-11e7-9a9b-5026e2a6cdb7.png)

Thanks,

**Comment by LincMitch** [comment]
I get the same issue too, but its intermittent. Sometimes it appears, and other time not.
