### ISSUE TITLE
Add ability to define resizing attributes

### ISSUE THREAD

**Issue by ryngonzalez** [airbnb/react-sketchapp#150]
Hey there! I was wondering if there was any thought around potentially adding the ability to define the resizing options on Sketch Layers. Use case would be that I'm trying to build a Symbol library that can have flexible layouts at design-time.

Screenshot below of what I'm describing:

<img width="238" alt="screenshot 2017-07-12 16 36 05" src="https://user-images.githubusercontent.com/635300/28144433-4e64fbe0-6720-11e7-888e-8d72803a3437.png">

**Comment by davidseik** [comment]
I'm in this rabbit hole as well; Trying to create a library of components in sketch using react-sketchapp but without this feature we're not able to make it more flexible. I was analyzing the JSON trace this leaves when you change these things on the UI but I haven't found a way to extrapolate a certain property (or set of properties) that can control this part from React-Sketch-App

**Comment by jongold** [comment]
Interesting - I haven't used constraints at all — happy to include it if someone has a proposal to talk through. I'd consider whether it's something that needs to live within `View` vs can be a HOC or wrapper component etc.
