### ISSUE TITLE
Detect platform - global constants

### ISSUE THREAD

**Issue by captainill** [airbnb/react-sketchapp#151]
👋 Hello! I'm looking for advice on best practices detecting platform to write platform specific CSS. I believe there is probably an elegant way to solve for this which airbnb or others may have already found (links for further reading welcome!). I'd inquire in [react-primitives](https://github.com/lelandrichardson/react-primitives) but I believe it's a limitation with skpm touched on in #63 that's foiling me in my current direction.

I'd like to have separate webpack configs for each platform so that I can inject a `PLATFORM` global for use in multiple modules within my app. It seems I can't add my own webpack config for use with react-sketchapp because it would override skpm's `webpack.config.js`. 

How are folks approaching this issue where they are trying to reuse components and need some switch to handle stlyles like `font-family` (specific font display name vs font list ) and `width` (containers with artboard pixel width vs fluid containers at 100% on web) differently in sketch vs web?

It could be nice to expand the [React Primitives example ](https://github.com/airbnb/react-sketchapp/tree/master/examples/profile-cards-primitives) example to touch on this.

**Comment by mathieudutour** [comment]
you can modify the webpack config of skpm by creating a `webpack.skpm.config.js` file. See more info here: https://github.com/airbnb/react-sketchapp/blob/7b706c0439aae998aaf20743307160b25adfd7f4/docs/guides/using-skpm.md#custom-configuration

To know the plaform it's running in, you can also use
```
import {Platform} from 'react-primitives'

Platform.os === 'sketch' // on sketch
Platform.os === 'web' // on the web
...
```
