### ISSUE TITLE
Error while building ./my-command.js. You may need the appropriate loader to handle this file type

### ISSUE THREAD

**Issue by pcooney10** [airbnb/react-sketchapp#154]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

_I am..._

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**
Should be able to use ES6+/ES7 features with the appropriate `.babelrc` configuration.

**Observed behavior:**
Error while building from an npm module that uses the following ES6+/ES7 syntax:

    static propTypes = {
      theme: PropTypes.object,
      markedDates: PropTypes.object,
      ...
    };

**How to reproduce:**
 With [this repo](https://github.com/pcooney10/rn-calendar). The presets in my .babelrc file are `["react", "stage-0", "es2015"]`. I have also tried the following plugins: `["transform-object-rest-spread", "transform-class-properties"]`.

**Sketch version:**
43.1

**Please attach screenshots, a zip file of your project, and/or a link to your github project**
**Repo**: https://github.com/pcooney10/rn-calendar
![image](https://user-images.githubusercontent.com/11021913/28342458-7be75a5c-6be6-11e7-9369-bf1c9df0615c.png)

**Comment by pcooney10** [comment]
I think the issue is that `skpm` ignores the `node_modules` directory, so my `.babelrc` settings were not getting applied to `node_modules\react-native-calendars`.

I think I can get around this limitation using a `webpack.config.js` file, but I am having some difficulty writing one that works. If anyone could post an example file, that would be greatly appreciated ! It may also be helpful to include one in one of the examples!

**Comment by pcooney10** [comment]
Hey - does anyone have a `webpack.config.js` that works with react-sketchapp and skpm?

I came across another react-native module that uses ES.Next syntax, and I am unable to compile it & use it in my app.   This is my current attempt at a webpack config:


        module.exports = {
          module: {
            rules: [
              {
                test: /\.jsx?$/,
                exclude: new RegExp(/node_modules\/(?!react-native-calendars(?:\/|$)).*/),
                use: {
                  loader: 'babel-loader',
                  options: {
                    presets: ['react', 'react-native', 'es2015', 'stage-0']
                  }
                }
              }
            ]
          }
        };

**Comment by jongold** [comment]
cc @mathieudutour

**Comment by mathieudutour** [comment]
what's the error with the last config exactly?

**Comment by pcooney10** [comment]
I am getting a few, `Module not found: Error: Can't resolve `, `Field 'browser' doesn't contain a valid alias configuration`, and `doesn't exist as directory` on imports.

**Comment by mathieudutour** [comment]
skpm changed the way it's handling the webpack config in v1.0 so it might work now. It's not really an issue with either `react-sketchapp` or `skpm` (i'm pretty sure requiring `react-native-calendars` in a sketch plugin will fail anyway) so closing this for now
