### ISSUE TITLE
Should code under examples be ignored on eslinting

### ISSUE THREAD

**Issue by sjy** [airbnb/react-sketchapp#156]
I am Johnson , a react fan and web developer.

**Proposal/Feature-request:**
examples code should be lint as well,  if a designer need help, some editor-based plugins could help make eslint pass, and Some contributors could also review and improve the code quality.

**Expected behavior:**
All JS code well lint and looks styled well. 

I can provide a pr, make the examples not ignored and exist examples be well lint.

also mentioned on [#58](https://github.com/airbnb/react-sketchapp/issues/58)

**Comment by jongold** [comment]
Hey Johnson 👋 

You're totally right - we shouldn't really be ignoring examples. Laziness / negligence on my part when we were rushing to ship, would love it if you could help out!

**Comment by sjy** [comment]
Aha, I am new to this repo, but I am really excited, within this pr, I am also going to unify the module exporting way.

**Comment by sjy** [comment]
[PR157] (https://github.com/airbnb/react-sketchapp/pull/157)
