### ISSUE TITLE
SVG primitives

### ISSUE THREAD

**Issue by jongold** [airbnb/react-sketchapp#16]
SVGs are the most sane way of expressing shape-like constructs in a react paradigm — c.f. https://github.com/chengyin/react-primitives-svg

Components: https://github.com/airbnb/react-sketchapp/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20SVG%20Primitives

### SVG components we need
- [ ] Circle
- [ ] Ellipse
- [ ] G
- [ ] Linear Gradient
- [ ] Radial Gradient
- [ ] Line
- [ ] Path
- [ ] Polygon
- [ ] Polyline
- [ ] Rect
- [ ] Symbol
- [ ] Text
- [ ] Use
- [ ] Defs
- [ ] Stop

**Comment by arahansen** [comment]
Are there any workarounds available for rendering svgs or even providing a placeholder symbol that could be populated with an existing svg that's already been imported into sketch?

**Comment by LincMitch** [comment]
Have a look at this Font icon workaround @168
