### ISSUE TITLE
Sketch crashing on Symbols example

### ISSUE THREAD

**Issue by RamonBalthazar** [airbnb/react-sketchapp#162]
Hello all, 

I'm having some trouble with the "symbols" example.

After running `npm run render` I get his on Sketch:

![image](https://user-images.githubusercontent.com/4910678/28939057-6224a6ba-7866-11e7-9f9e-e4803c332f53.png)

Then Sketch crashes if I click on the red lines thing or the "nested symbols" item.

I've never seen Sketch crashing like that. Other examples work as intended.

**How to reproduce:**
1) Clone this repo;
2) Go to `react-sketchapp/examples/symbols` and run `npm install`;
3) Open Sketch;
4) Run `npm run render`;
5) On Sketch, try selecting `Nested  Symbol` some how;
6) Behold the crash.

**Environment:**
- react-sketchapp 0.12.0
- Sketch 46
- npm 2.15.12
- macOS Sierra 10.12.6

**Comment by ianhook** [comment]
I was unable to reproduce on the same specs.  The red lines in your picture appear to be a problem when the symbol is deleted. Symbols are matched by ID in Sketch so two symbols may have the same name and different IDs. Symbols should maintain IDs though since at least 0.11.5 though.

**Comment by jongold** [comment]
It's possible that 46 has broken everything, again 😱

**Comment by petterheterjag** [comment]
I get the same behaviour running 0.12, but 0.11.5 works fine.

**Comment by RamonBalthazar** [comment]
I got it working on 0.11.5 too 😃
