### ISSUE TITLE
Can someone help me adding Semantic react UI to Sketch?

### ISSUE THREAD

**Issue by ziyafenn** [airbnb/react-sketchapp#165]
Hi guys! I'm really having trouble going any further than using airbnb examples.

I'd like to be able to use Semantic React UI components in my sketch.

http://react.semantic-ui.com/introduction

Any ideas how i could do that?

Thanks!

**Comment by jongold** [comment]
Hey Ziya! Unfortunately `semantic-ui` won't work out of the box — it uses React DOM under the hood (`div`, `button` etc). This project uses React Native / React Primitives-style components — `View`, `Text` etc. It's frustrating if you're not used to working with Primitives, but it's super cool if you do build you design system with Primitives and get to render things on lots of platforms! Leland did a great job of explaining why we made that choice at React Europe: https://www.youtube.com/watch?v=hNwQPJy-XZY

We still haven't got an easy way to convert DOM elements to their primitive representations though. Some things you could explore:
- React Native Web—which React Primitives uses to render to the browser—has a [`createDOMElement` function that you can wrap components in](https://github.com/necolas/react-native-web/blob/master/docs/guides/advanced.md). I haven't tried using it for Sketch yet but I believe the principles are similar. If you managed to get that working (potentially as a separate module we could use with React Primitives + React Sketch.app) you'd be many people's hero 🙏 
- Semantic UI components [have this `as` property which grabs the underlying DOM element](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/getElementType.js). A mechanism like that could be used to swap out `div` for `View` etc (but I wouldn't expect it to work out of the box)
- Forking / rewriting Semantic UI to use primitives (clearly ridiculous :P) — but it does show the need for a good primitives-based design system we can use with React Primitives, React Native Web, React Sketch.app etc etc

**Comment by ziyafenn** [comment]
@jongold I didn't want to open a new topic, so will ask similar questions here:

i've tried to render React Native components from https://js.coach/react-native as it shown in Airbnb examples ( git clone / cd / run-render). But as you would expect, it doesn't work. 

I'm sorry for my lack of knowledge, but could you explain why it doesn't work and how i can get to do this? 

Thanks a lot!
