### ISSUE TITLE
Triangle

### ISSUE THREAD

**Issue by sdaitzman** [airbnb/react-sketchapp#168]
_I am..._

| -------------------------------------------------------------------------------------------------
| Wondering how to make a triangle
| -------------------------------------------------------------------------------------------------

**Expected behavior:**
I can make a triangle

**Observed behavior:**
I am not sure how to make a triangle, based on the documentation. I would greatly appreciate any help that you can offer. Thank you so much.

**Comment by kristof** [comment]
I recently had the same issue, I ended up creating a PNG that included the triangle as an image. The [CSS border hack](https://css-tricks.com/snippets/css/css-triangle/) will not work since Sketch handles borders quite differently than a browser would.

**Comment by jongold** [comment]
Frustratingly we actually don't have a good solution for this yet.

There's a plan to add support for SVG-style shapes #16, but currently we just implement parts of the React Native API - `<View>`, `<Text>`, `<Image>` etc.

@kristof's solution is probably your best bet for now - sorry that we don't have anything more elegant :(

**Comment by LincMitch** [comment]
There is a workaround if you don't mind using Font icons. This is how you do it:
1. Create any SVG in Illustrator and import it to https://icomoon.io/app/
2. Install and use this font in Illustrator via the Glyphs panel
3. Select and copy the character and past into your code (appeared as a rectangle)
4. Style it with the Font-Family and a colour
5. Render to Sketch
6. DONE
---
If you want a multicoloured vector image, then you need to stack a series of icon fonts.
6. Make sure all the coloured parts of an image are saved separately but with the same art-board size.
7. Do steps 1-6 - assigning each color.
8. Stack all parts of the image by styling it using position:abolute, left:0px, top:0px,
9. DONE

**Comment by jongold** [comment]
Thanks @LincMitch - this is a great solution (and how our design system at Airbnb is architected) :)

**Comment by LincMitch** [comment]
Good to hear @jongold . 
Also... if you don't want font icons in Sketch you can "Convert to Outlines" in the Layer menu.

**Comment by LincMitch** [comment]
Another alternative might be to parse an SVG to generate a raster image in Sketch. Any idea on how to do that?
