### ISSUE TITLE
Non System fonts

### ISSUE THREAD

**Issue by LincMitch** [airbnb/react-sketchapp#182]
I am trying to render a non system font (like OpenSans).

**Observed behavior:**
If you don't use a system font, then Sketch doesn't display the correct font and reports it as a "Missing Fonts" error, at top right of the application. Clicking the error allows you to replace the font.

Are we limited to system fonts? If so, Is there a way around this? 

I believe there is a way to move a 3rd party font into the system font, but heard its not advisable. Or is this my only route?

**Comment by jongold** [comment]
My guess is that you're not specifiying the PostScript family name for the font - it could be spelt something like `OpenSans`, `Open Sans` or `Open-Sans`, and I think it will only pick up the exact version. Try finding the font in Font Book and pressing CMD-I to see what the Family name is and report back!

**Comment by LincMitch** [comment]
Got it @jongold. it works now using:

`font-family: OpenSansLight;
font-weight: 100;`

Just did Cmd I (thanks for that handy tip) and it says:
PostScript name:OpenSans-Light 

So I change it to:
`font-family: OpenSans-Light;`
and could even remove font-weight: 100.

After posting this I found the same issue #120 

This was a big stumbling block. I could demo this system as my web and Skecthapp renders where looking completely different due to this font recognition issue.

Glad you could help. Thx

**Comment by jongold** [comment]
Sure thing!
