### ISSUE TITLE
HTML lists

### ISSUE THREAD

**Issue by LincMitch** [airbnb/react-sketchapp#184]
**Proposal/Feature-request?:**

I'm trying to render HTML Lists `<UI> <LI> <OL>...` to SketchApp using React-SketchApp, React-Primitives, and Platform extensions. I have heard I can use React-web to render Lists in the browser but not sure about SketchApp. Would I use Glyphs and try fudge it for now?
Sounds like a feature request, but is there something I am missing here?

**Comment by mathieudutour** [comment]
`ul`, `li` and `ol` don't make sense in Sketch. So if you are using `react-primitives`, just use `View` and `Text` directly (the small dot could be a View 5px*5px with rounded corner and black background for example)
