### ISSUE TITLE
Exporting multiple components from 1 file

### ISSUE THREAD

**Issue by ziyafenn** [airbnb/react-sketchapp#185]
Hi guys! I was wondering how it's possible to export multiple components coded into 1 file.

I use `const CompName = () => (
<View> <Text></Text></View> );`

and at the end of the file i add `export default CompName;`

But that doesn't let me export all Components.

Any ideas? Thanks and sorry, as i'm just learning!

**Comment by jongold** [comment]
Hey Ziya! You should be able to do
```js
export const Comp = () => <View>…</View>
export const Another = () => <View>…</View>
```
and then
```js
import { Comp, Another } from './components';
```
rather than
```js
import Comp from './components'
```

Hope that helps!

**Comment by rajiff** [comment]
What about which one among these should be default? how to specify which one should be default?

**Comment by ziyafenn** [comment]
@rajiff 
on the example above:

```
export default const Comp = () => <View>…</View>
export const Another = () => <View>…</View>
```

and then

```
import Comp, { Another } from './components';
```

The default one stays always outside of the bracket and the non-default ones are inside.

**Comment by Abbeyme1** [comment]
Use this

export default <Function name>
export {<name of things you wish to export if many then seperate it by commas>} 
ex. =>  export {b,c};

_the name by which you are exporting must be same while importing._

like
import <anyName  you wish to give> , { firstName} , {secondName} from <fileName>
ex => import abc ,{b,c} from <fileName>

Or You can also use * while importing .
and then you can use it like  (using above example)   {abc.b} or {abc,c} .

Hope it will help you

**Comment by sumitwd** [comment]
Multiple function components in a single file:

import React from 'react';
function Lake(){
	return(
		<div>You choosed Summer, Great!<h2>Visit Haridwar!</h2></div>
		)
}

function Hillstation(){
	return(
		<div>You choosed Winter, Great!<h2>Visit Himachal Pradesh!</h2></div>
		)
}

function Condition_hardcore_fc(props){
	if (props.season === "summer"){
		return <Lake/>;
	}else if (props.season === "winter"){
		return <Hillstation />;
	}
}

export default Condition_hardcore_fc;

// Scenario 01: in this component, we used multiple functional components in a single module.
// Scenario 02: in index.js: we use props "season" - <Condition_hardcore_fc season="summer" />
