### ISSUE TITLE
flexGrow/Shink/Basis not supported

### ISSUE THREAD

**Issue by jacobp100** [airbnb/react-sketchapp#187]
Currently the documentation says these are supported.

I believe this would be fixed by upgrading to Yoga (#52).

I believe we want to do something like [this](https://github.com/orta/jest-snapshots-svg/blob/master/src/component-to-node.ts).

I'm happy to look at this. Would you be happy for something like the approach like above?

**Comment by jongold** [comment]
Absolutely - we'd love to be on Yoga if you have time to look into it :)

**Comment by larsonjj** [comment]
Tried looking into this, but was unable to get the `yoga-layout@1.6.0` npm package to import correctly. Everything seems to build fine, but get weird `{}("") is not a function` errors. @jacobp100 or @mathieudutour, have either of you had luck in getting yoga to work in a Node environment?

**Comment by mathieudutour** [comment]
I tried a while ago without success. But I didn’t really understand yoga tbh. There is an issue about that specifically if i remember correctly

**Comment by larsonjj** [comment]
Was successfully able to get yoga working in #188 🎉 . Feel free to check it out and let me know if you run into any issues.
