### ISSUE TITLE
TypeError when rendering basic example

### ISSUE THREAD

**Issue by apexskier** [airbnb/react-sketchapp#19]
**Expected behavior:**

Following the basic example instructions works

**Observed behavior:**

When I run the render task, Sketch opens, but the following error

```
TypeError: null is not an object (evaluating 'context.document.currentPage')
line: 9246
column: 114
```

**How to reproduce:**

```
cameronlittle@Chelan:~/Dev
$ curl https://codeload.github.com/airbnb/react-sketchapp/tar.gz/master | tar -xz --strip=2 react-sketchapp-master/examples/basic-setup
cameronlittle@Chelan:~/Dev
$ cd basic-setup
cameronlittle@Chelan:~/Dev/basic-setup
$ npm install
# for brevity, I've removed this output, since it's all normal
cameronlittle@Chelan:~/Dev/basic-setup
$ npm run render

> basic-setup@1.0.0 render /Users/cameronlittle/Dev/basic-setup
> skpm build --watch --run

🖨  Copied src/manifest.json in 6ms
Executing post-build scripts
🛠  Built ./my-command.js in 1391ms
TypeError: null is not an object (evaluating 'context.document.currentPage')
line: 9246
column: 114

```

**Version information:**

Sketch: 43.1
node: v7.2.1
npm: 3.10.10
os: macOS Sierra 10.12.3 (16D32)

**Comment by mathieudutour** [comment]
You need to have a document opened

**Comment by jongold** [comment]
This should be way clearer, sorry - **you need to have a new Sketch document open when you call render**.

We've asked the Sketch devs to help us out on this but haven't got a timeline thus far :(

**Comment by apexskier** [comment]
Great, thanks for the info!

**Comment by sjy** [comment]
Will it be better to verbose a info indicating the user a new sketch doc is required ?
