### ISSUE TITLE
Navigation example

### ISSUE THREAD

**Issue by LincMitch** [airbnb/react-sketchapp#192]
**Proposal/Feature-request:**

It would be great to see a simple example of basic navigation. For example, 2 pages with next and previous buttons. The pages would be rendered in SketchApp on 2 Artboards, whilst the web render would work as expected.

I think a simple example of this would encourage less tech savvy designers like me to embrace react-sketchapp.

**Comment by Paarmita** [comment]
@LincMitch I would like to work on this issue. What kind of skills are needed to contribute to this?

**Comment by mathieudutour** [comment]
Feel free! You can look at the [react-primitives](https://github.com/airbnb/react-sketchapp/tree/master/examples/profile-cards-primitives) example to see how to render to both sketch and the web. Then it would be designing those 2 pages (nothing fancy, we want the concept to be clear).

Feel free to start a PR and ping me if you are stuck :+1:

**Comment by Paarmita** [comment]
@mathieudutour Is there any other way to install this project if I don't have the sketch?

**Comment by wellmonge** [comment]
@mathieudutour and @Paarmita  I would help you on this issues.

**Comment by mathieudutour** [comment]
Sounds good! Let me know if you need anything

**Comment by wellmonge** [comment]
> Sounds good! Let me know if you need anything

Yes, it would be great if you have any ideia on how to creating prototyping animation, if it's necessary to fit the FR?

**Comment by mathieudutour** [comment]
It’s not supported by react-sketchapp yet so for now we can just render the screen side by side without link between them
