### ISSUE TITLE
render with container other than context.document.currentPage fails

### ISSUE THREAD

**Issue by weaintplastic** [airbnb/react-sketchapp#195]
Hi folks,

I hope it is okay to report issues with the 1.* beta version here.

When using the render function with a container other than `context.document.currentPage()` nothing is rendered.

**Expected behavior:**

I expect the component to be rendered into the given container.

**Observed behavior:**

It renders nothing. This is due to the fact the `render` clears out the document and therefore anything that has been added before (https://github.com/airbnb/react-sketchapp/blob/master/src/render.js#L124). So the actual container is not available anymore when calling `buildPages()`(https://github.com/airbnb/react-sketchapp/blob/master/src/render.js#L130) which would take care about rendering to the given container.

Maybe clearing the document should be optional or the concern of the application that is utilising react-sketchapp.

**How to reproduce:**

```
const onRun = () => {
  const document = sketch.selectedDocument;
  const page = document.selectedPage;
  const group = page.newGroup();

  render(
    <Text>I should be rendered to the group</Text>,
    group
  );

  group.adjustToFit();
};

module.exports = onRun;
```
**Sketch version:**

1.0.0-beta.5

**Comment by mathieudutour** [comment]
> Maybe clearing the document should be optional or the concern of the application that is utilising react-sketchapp.

That would go against the principle of React but we should definitely only clear the object passed as an argument.

There are actually a few places where we hardcoded `context.document` and that's not great. Not sure what the solution for symbols and shared styles tho

**Comment by weaintplastic** [comment]
> only clear the object passed as an argument.

That makes 100% sense. Let me know if I can help out providing functionality for that. probably a function called `resetContainer` rather than `resetDocument`
