### ISSUE TITLE
Sketch crashes when using <Image source={require('../path/to/asset.png')} /> instead of an URL

### ISSUE THREAD

**Issue by csantiago132** [airbnb/react-sketchapp#199]
_I am..._
Carlos Santiago

| Reporting a bug or issue

**Expected behavior:**
Load local image from an Assets folder

**Observed behavior:**
when running the script, Sketch crashes

**How to reproduce:**
use `{require('./path/to/local/asset.png')}` as image source

**Sketch version:**
47.1

**Comment by LincMitch** [comment]
I believe images only work with the beta version. Latest version being 'v1.0.0-beta.5'?

**Comment by ossanti** [comment]
Hi @LincMitch and thanks for the reply, yes im using `"react-sketchapp": "^1.0.0-beta.5"` as of right now, they work fine when uring an URL tho

**Comment by csantiago132** [comment]
reopening due to having same issue after updating (unless im missing something)

I tried:  
    source={require('../../assets/images/chart-symbols/value-5--has-data.png')}

second attempt:
    const ImageTest = require('../../assets/images/chart-symbols/value-5--has-data.png');

    source={ImageTest}

**Comment by mathieudutour** [comment]
what version of skpm are you using?

**Comment by csantiago132** [comment]
the SKPM/Builder?

`"@skpm/builder": "^0.2.0"`

**Comment by csantiago132** [comment]
I started a new install and still have the same issue
