### ISSUE TITLE
Can't resolve 'babel-loader'

### ISSUE THREAD

**Issue by hanih** [airbnb/react-sketchapp#20]
That's embarrassing but I had to install babel-loader from npm to run the example project :)
npm version 2.15.11

**Comment by jongold** [comment]
Oh weird - I'm not sure why that would be happening, but it's a much older npm version than I'm using. Will look into it - sorry!

**Comment by pmarquees** [comment]
The repository is also not listed in the package.json and npm is complaining, will do a pull request.

**Comment by jongold** [comment]
@pmarquees @hanih which example are you looking at? `examples/basic-setup` should have `skpm` as a dependency which hides you from the webpack setup.

**Comment by pmarquees** [comment]
That one, exactly.

**Comment by jongold** [comment]
@pmarquees what version of npm & node are you running?
```
npm -v
node -v
```

Would also be helpful to see how npm is resolving `skpm` for you - **from the basic-setup folder**
```
pbcopy < node_modules/skpm/package.json
```
& then paste that here.

Sorry for the issue, hope we get it resolved!

**Comment by pmarquees** [comment]
Sure..
npm: 4.5.0
node: 7.9.0

`{
  "_args": [
    [
      {
        "raw": "skpm@^0.8.0",
        "scope": null,
        "escapedName": "skpm",
        "name": "skpm",
        "rawSpec": "^0.8.0",
        "spec": ">=0.8.0 <0.9.0",
        "type": "range"
      },
      "/Users/pmarques/Documents/Projects/react-sketchapp/examples/colors"
    ]
  ],
  "_from": "skpm@>=0.8.0 <0.9.0",
  "_id": "skpm@0.8.2",
  "_inCache": true,
  "_location": "/skpm",
  "_nodeVersion": "6.6.0",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/skpm-0.8.2.tgz_1492681770945_0.7335823292378336"
  },
  "_npmUser": {
    "name": "mathieudutour",
    "email": "mathieu@dutour.me"
  },
  "_npmVersion": "3.10.3",
  "_phantomChildren": {},
  "_requested": {
    "raw": "skpm@^0.8.0",
    "scope": null,
    "escapedName": "skpm",
    "name": "skpm",
    "rawSpec": "^0.8.0",
    "spec": ">=0.8.0 <0.9.0",
    "type": "range"
  },
  "_requiredBy": [
    "#DEV:/",
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/skpm/-/skpm-0.8.2.tgz",
  "_shasum": "c31f0ded6f8d8e859d1bb847ec6e4db0a8dcec89",
  "_shrinkwrap": null,
  "_spec": "skpm@^0.8.0",
  "_where": "/Users/pmarques/Documents/Projects/react-sketchapp/examples/colors",
  "author": {
    "name": "Mathieu Dutour",
    "email": "mathieu@dutour.me",
    "url": "http://mathieu.dutour.me/"
  },
  "bin": {
    "skpm": "lib/skpm.js"
  },
  "bugs": {
    "url": "https://github.com/sketch-pm/skpm-cli/issues"
  },
  "dependencies": {
    "adm-zip": "^0.4.7",
    "babel-core": "^6.24.1",
    "babel-loader": "^7.0.0-beta.1",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-preset-airbnb": "^2.2.3",
    "chalk": "^1.1.3",
    "commander": "^2.9.0",
    "cpr": "^2.0.2",
    "js-yaml": "^3.8.2",
    "lazy-require": "^2.2.0",
    "lodash.uniqby": "^4.7.0",
    "object-assign": "^4.1.1",
    "open": "^0.0.5",
    "request": "^2.81.0",
    "semver": "^5.3.0",
    "simple-plist": "^0.2.1",
    "skpm-client": "0.2.2",
    "tar.gz": "^1.0.5",
    "webpack": "^2.3.3",
    "webpack-shell-plugin": "^0.5.0",
    "yesno": "^0.0.1"
  },
  "description": "A utility to build, publish and install sketch plugins",
  "devDependencies": {
    "standard": "^9.0.2"
  },
  "directories": {},
  "dist": {
    "shasum": "c31f0ded6f8d8e859d1bb847ec6e4db0a8dcec89",
    "tarball": "https://registry.npmjs.org/skpm/-/skpm-0.8.2.tgz"
  },
  "gitHead": "eb3f4fc55b7fccc2599ce62e94c50a9bfe4deeed",
  "homepage": "https://github.com/sketch-pm/skpm-cli#readme",
  "keywords": [
    "sketch",
    "cocoascript",
    "javascript",
    "babel"
  ],
  "license": "MIT",
  "maintainers": [
    {
      "name": "mathieudutour",
      "email": "mathieu@dutour.me"
    }
  ],
  "name": "skpm",
  "optionalDependencies": {},
  "readme": "<h1 align=\"center\">skpm - Sketch Plugin Manager</h1>\n\n<div align=\"center\">\n  <img src=\"https://avatars0.githubusercontent.com/u/24660874?v=3&s=200\" />\n</div>\n<br />\n<div align=\"center\">\n  <strong>A utility to build, publish, install and manage <a href=\"https://www.sketchapp.com/\">sketch</a> plugins.</strong>\n</div>\n\n## Installation\n\n```bash\nnpm install -g skpm\n```\n\n_The `npm` command-line tool is bundled with Node.js. If you have it installed, then you already have npm too. If not, go download [Node.js](https://nodejs.org/en/download/)._\n\n## Usage\n\n**I'm a sketch user**\n* [Installing a plugin](#installing-a-plugin)\n* [Uninstalling a plugin](#uninstalling-a-plugin)\n* [Search for plugins](#search-for-plugins)\n\n**I'm a plugin developer**\n* [Scaffold the architecture of a new plugin](#scaffold-the-architecture-of-a-new-plugin)\n* [Build the plugin](#build-the-plugin)\n* [Symlinking the local plugin to the sketch plugins folder](#symlinking-the-local-plugin-to-the-sketch-plugins-folder)\n* [Publish the plugin on the registry](#publishing-th-plugin-on-the-registry)\n\n## Documentation\n\n#### Installing a plugin\n\nTo install a sketch plugin:\n\n```bash\nskpm install name-of-the-plugin\n```\n\n#### Uninstalling a plugin\n\nTo uninstall a sketch plugin:\n\n```bash\nskpm uninstall name-of-the-plugin\n```\n\n#### Search for plugins\n\nTo search for a sketch plugin:\n\n```bash\nskpm search query\n```\n\n#### Scaffold the architecture of a new plugin\n\nTo interactively create the architecture to start developing a new plugin (see the [sketch documentation](http://developer.sketchapp.com/introduction/plugin-bundles/) for more information):\n\n```bash\nskpm init\n```\n\nThis will create:\n* a `package.json` file\n* a `src` folder with:\n  * a `manifest.json` file\n  * a `command.js` file for an example of command\n* a `.gitignore` file if non-existent\n\nThe `package.json` must contain 3 specific fields:\n* `main`: pointing to your `.sketchplugin`\n* `manifest`: pointing to your `manifest.json` (`src/manifest.json` by default)\n* `repository`: pointing to your github repository\n\n#### Build the plugin\n\nTo transpile the JavaScript to CocoaScript and copy the `manifest.json` to the `.sketchplugin`:\n```bash\nskpm build\n```\n\nTo watch for changes:\n\n```bash\nskpm build --watch\n```\n\nAdditionally, some fields from the `package.json` will be set in the `manifest.json` (if not present):\n* version\n* name\n* description\n* homepage\n\n#### Symlinking the local plugin to the sketch plugins folder\n\n```bash\nskpm link path-to-local-plugin\n```\n\nIt will also ask you if you want to [disable the caching mechanism](http://developer.sketchapp.com/introduction/preferences/#always-reload-scripts-before-running) and force Sketch to always reload a Plugin’s code from disk (recommended when developing).\n\n#### Publish the plugin on the registry\n\nTo publish a new version of the plugin to the registry:\n```bash\nskpm publish <newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease\n```\n\nThe exact order of execution is as follows:\n* Run the `preversion` script\n* Bump `version` in package.json as requested (`patch`, `minor`, `major`, etc).\n* Run the `version` script\n* Commit and tag\n* Run the `postversion` script.\n* Run the `build` script\n* Zip the folder specified in the `main` field\n* Create a draft release on GitHub\n* Upload the zip to GitHub\n* Publish the release\n* Remove the zip\n* Notify the registry\n\n## License\n\n[MIT](https://tldrlegal.com/license/mit-license)\n",
  "readmeFilename": "README.md",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sketch-pm/skpm-cli.git"
  },
  "scripts": {
    "test": "standard"
  },
  "standard": {
    "ignore": [
      "lib/utils/consolePolyfill.js"
    ]
  },
  "version": "0.8.2"
}
`

**Comment by hanih** [comment]
Node 4.7.3
Npm 2.15.11

{
  "name": "skpm",
  "version": "0.8.2",
  "description": "A utility to build, publish and install sketch plugins",
  "bin": {
    "skpm": "lib/skpm.js"
  },
  "scripts": {
    "test": "standard"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sketch-pm/skpm-cli.git"
  },
  "keywords": [
    "sketch",
    "cocoascript",
    "javascript",
    "babel"
  ],
  "author": {
    "name": "Mathieu Dutour",
    "email": "mathieu@dutour.me",
    "url": "http://mathieu.dutour.me/"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/sketch-pm/skpm-cli/issues"
  },
  "homepage": "https://github.com/sketch-pm/skpm-cli#readme",
  "devDependencies": {
    "standard": "^9.0.2"
  },
  "dependencies": {
    "adm-zip": "^0.4.7",
    "babel-core": "^6.24.1",
    "babel-loader": "^7.0.0-beta.1",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-preset-airbnb": "^2.2.3",
    "chalk": "^1.1.3",
    "commander": "^2.9.0",
    "cpr": "^2.0.2",
    "js-yaml": "^3.8.2",
    "lazy-require": "^2.2.0",
    "lodash.uniqby": "^4.7.0",
    "object-assign": "^4.1.1",
    "open": "^0.0.5",
    "request": "^2.81.0",
    "semver": "^5.3.0",
    "simple-plist": "^0.2.1",
    "skpm-client": "0.2.2",
    "tar.gz": "^1.0.5",
    "webpack": "^2.3.3",
    "webpack-shell-plugin": "^0.5.0",
    "yesno": "^0.0.1"
  },
  "standard": {
    "ignore": [
      "lib/utils/consolePolyfill.js"
    ]
  },
  "gitHead": "eb3f4fc55b7fccc2599ce62e94c50a9bfe4deeed",
  "_id": "skpm@0.8.2",
  "_shasum": "c31f0ded6f8d8e859d1bb847ec6e4db0a8dcec89",
  "_from": "skpm@>=0.8.0 <0.9.0",
  "_npmVersion": "3.10.3",
  "_nodeVersion": "6.6.0",
  "_npmUser": {
    "name": "mathieudutour",
    "email": "mathieu@dutour.me"
  },
  "dist": {
    "shasum": "c31f0ded6f8d8e859d1bb847ec6e4db0a8dcec89",
    "tarball": "https://registry.npmjs.org/skpm/-/skpm-0.8.2.tgz"
  },
  "maintainers": [
    {
      "name": "mathieudutour",
      "email": "mathieu@dutour.me"
    }
  ],
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/skpm-0.8.2.tgz_1492681770945_0.7335823292378336"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/skpm/-/skpm-0.8.2.tgz",
  "readme": "ERROR: No README data found!"
}

**Comment by VansonLeung** [comment]
npm 2.14.4
node 4.1.2

**Comment by VansonLeung** [comment]
{
  "name": "skpm",
  "version": "0.8.2",
  "description": "A utility to build, publish and install sketch plugins",
  "bin": {
    "skpm": "lib/skpm.js"
  },
  "scripts": {
    "test": "standard"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sketch-pm/skpm-cli.git"
  },
  "keywords": [
    "sketch",
    "cocoascript",
    "javascript",
    "babel"
  ],
  "author": {
    "name": "Mathieu Dutour",
    "email": "mathieu@dutour.me",
    "url": "http://mathieu.dutour.me/"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/sketch-pm/skpm-cli/issues"
  },
  "homepage": "https://github.com/sketch-pm/skpm-cli#readme",
  "devDependencies": {
    "standard": "^9.0.2"
  },
  "dependencies": {
    "adm-zip": "^0.4.7",
    "babel-core": "^6.24.1",
    "babel-loader": "^7.0.0-beta.1",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-preset-airbnb": "^2.2.3",
    "chalk": "^1.1.3",
    "commander": "^2.9.0",
    "cpr": "^2.0.2",
    "js-yaml": "^3.8.2",
    "lazy-require": "^2.2.0",
    "lodash.uniqby": "^4.7.0",
    "object-assign": "^4.1.1",
    "open": "^0.0.5",
    "request": "^2.81.0",
    "semver": "^5.3.0",
    "simple-plist": "^0.2.1",
    "skpm-client": "0.2.2",
    "tar.gz": "^1.0.5",
    "webpack": "^2.3.3",
    "webpack-shell-plugin": "^0.5.0",
    "yesno": "^0.0.1"
  },
  "standard": {
    "ignore": [
      "lib/utils/consolePolyfill.js"
    ]
  },
  "gitHead": "eb3f4fc55b7fccc2599ce62e94c50a9bfe4deeed",
  "_id": "skpm@0.8.2",
  "_shasum": "c31f0ded6f8d8e859d1bb847ec6e4db0a8dcec89",
  "_from": "skpm@>=0.8.0 <0.9.0",
  "_npmVersion": "3.10.3",
  "_nodeVersion": "6.6.0",
  "_npmUser": {
    "name": "mathieudutour",
    "email": "mathieu@dutour.me"
  },
  "dist": {
    "shasum": "c31f0ded6f8d8e859d1bb847ec6e4db0a8dcec89",
    "tarball": "https://registry.npmjs.org/skpm/-/skpm-0.8.2.tgz"
  },
  "maintainers": [
    {
      "name": "mathieudutour",
      "email": "mathieu@dutour.me"
    }
  ],
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/skpm-0.8.2.tgz_1492681770945_0.7335823292378336"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/skpm/-/skpm-0.8.2.tgz"
}

**Comment by volkanongun** [comment]
same basic-setup issue here. 
node: v7.8.0
npm: 4.5.0

**Comment by mathieudutour** [comment]
So i understand why it's failing with npm 2 (because of [this](https://docs.npmjs.com/how-npm-works/npm3)), but not really why it would fail on npm 4. I though the architecture of the dependencies stayed the same

**Comment by ljharb** [comment]
npm 2 vs 3+'s differences shouldn't have any effect on this.

**Comment by mathieudutour** [comment]
Not saying that it should, just that it does: wekpack doesn't look for nested dependencies to find `babel-loader`

**Comment by ljharb** [comment]
In that case, `babel-loader` should be a peer dependency (and thus an explicit top-level dep) and not a dependency of skpm.

**Comment by mathieudutour** [comment]
I kinda want to avoid having to set it manually.

I just published `skpm@0.9.2`. It should fix the issue for npm2. But I'm not sure what's the issue with npm4

**Comment by ljharb** [comment]
If webpack can only find it when top-level-installed, it **must** be a top-level dep (and a peer dep of skpm). There's no way around it.

**Comment by mathieudutour** [comment]
yes there is a way, using the `resolveLoader` option: https://github.com/sketch-pm/skpm/blob/master/lib/skpm-build.js#L155

**Comment by ljharb** [comment]
Great, that means webpack can find it :-)

You may want to use require.resolve tho; generally node_modules shouldn't ever be hardcoded anywhere. Not sure if that'll fix npm 4.

**Comment by mathieudutour** [comment]
Yes, just not by its own. 

Not sure what you mean, `require.resolve` would return the path of a file, here we want the path of the node_modules folder, `require.resolve` won't return that as far as I know
