### ISSUE TITLE
"TypeError: undefined is not an object" when using tags

### ISSUE THREAD

**Issue by varya** [airbnb/react-sketchapp#202]
Hi. I'm trying to render the existing styled-components of a web project. When I'm importing a styled-component which renders an HTML tag I get an error

```
TypeError: undefined is not an object (evaluating '__WEBPACK_IMPORTED_MODULE_2_styled_components_primitives___default.a.h2.withConfig')
```
I expect that renderer knows which primitives to render instead of `<h2>`, but it does not.

Is it possible to redefine and code that `<h2>` means `<Text>` and, let's say, `<div>` means `<View>`?

**Comment by mxstbr** [comment]
You have to use `styled-components/primitives`, otherwise you won't be able to render with react-sketchapp!

**Comment by varya** [comment]
@mxstbr Thanks! But will I be able to use the same code for the web? Could not find such example :-(

**Comment by mxstbr** [comment]
Yep! If you use `styled-components/primitives` you can use those components across the web, native and Sketch. See the example in the introductory blog post for example: https://medium.com/styled-components/announcing-primitives-support-for-truly-universal-component-systems-5772c7d14bc7

![primitives](https://user-images.githubusercontent.com/7525670/32440960-b3e349c8-c2f5-11e7-9527-431d90633861.png)

That's the exact same components rendering in a native app, in Sketch and on the web!

**Comment by varya** [comment]
Thanks so much! I should have done more research. Hope this thread will be useful in someone's Google search results :-)

**Comment by mxstbr** [comment]
No worries, happy to help!
