### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'Function.prototype.toString')

### ISSUE THREAD

**Issue by alampros** [airbnb/react-sketchapp#205]
I am reporting a bug or issue - I can't get any of the examples to run. They all produce the same error.

**Expected behavior:**
Renders the "basic setup" example.

**Observed behavior:**
Produces error:
```
> npm run render

> basic-setup@1.0.0 render /Users/alampros/tmp/react-sketchapp/examples/basic-setup
> skpm build --watch --run

🖨  Copied src/manifest.json in 3ms
TypeError: undefined is not an object (evaluating 'Function.prototype.toString')
line: 707
stack: isNative


__webpack_require__


__webpack_require__


__webpack_require__


__webpack_require__

__webpack_require__

__webpack_require__

run
run@[native code]
column: 40
⚒  Built ./my-command.js in 900ms
```

**How to reproduce:**
Follow the steps in the README:
```sh
git clone https://github.com/airbnb/react-sketchapp.git
cd react-sketchapp/examples/basic-setup && npm install

npm run render
```

**Sketch version:** 47.1 (45422)

**Comment by mathieudutour** [comment]
can you look in the .sketchplugin and find the my-command.js. What's on the line 707?

**Comment by alampros** [comment]
This is super weird.

From `/examples/basic-setup/basic-setup.sketchplugin/Contents/Sketch/my-command.js`:
```js
function isNative(fn) {
  // Based on isNative() from Lodash
  var funcToString = Function.prototype.toString; // 👈 Line 707
  var hasOwnProperty = Object.prototype.hasOwnProperty;
  var reIsNative = RegExp('^' + funcToString
  // Take an example native function source for comparison
  .call(hasOwnProperty
  // Strip regex characters so we can use it for regex
  ).replace(/[\\^$.*+?()[\]{}|]/g, '\\$&'
  // Remove hasOwnProperty from the template to make it generic
  ).replace(/hasOwnProperty|(function).*?(?=\\\()| for .+?(?=\\\])/g, '$1.*?') + '$');
  try {
    var source = funcToString.call(fn);
    return reIsNative.test(source);
  } catch (err) {
    return false;
  }
}
```

**Comment by mathieudutour** [comment]
hum can you go to Sketch, `Plugins > Run Script` and run `log(Function.prototype.toString)`? what does it say?

**Comment by alampros** [comment]
Same error

![screen shot 2017-11-13 at 12 20 04 pm](https://user-images.githubusercontent.com/297461/32739159-09bb2376-c86d-11e7-9fb6-b50e54269fe7.png)

**Comment by mathieudutour** [comment]
interesting. What version of macOS do you have?

**Comment by alampros** [comment]
10.13.2 Beta (17C67b)

**Comment by alampros** [comment]
I can call it on `Function` object directly, but not on the `.prototype`. Super weird. Could this have been removed as a security precaution in the upcoming macOS version?

**Comment by mathieudutour** [comment]
I'm on 10.13.1. Could they possibly have broken JavaScriptCore? haha.

I'm not sure how an object cannot have a prototype 😕  

What does `log(Object.prototype.toString)` says?

**Comment by alampros** [comment]
Works just fine.

`log(Object.prototype.toString)` => `<MOJavaScriptObject: 0x60c000826d40>`

Perhaps the CocoaScript bridge forbids access to the Function prototype?

**Comment by mathieudutour** [comment]
well it works fine on my machine, can't really see how this could fail. anyhow, that's a Sketch bug, nothing that `react-sketchapp` can do. I'll file it here

**Comment by alampros** [comment]
It looks like this might be a change to the ecma spec:
https://tc39.github.io/Function-prototype-toString-revision/#sec-function.prototype.tostring

>If the implementation cannot produce a source code string that meets these criteria then it must return a string for which eval will throw a SyntaxError exception.

**Comment by mathieudutour** [comment]
no but here the issue is that `Function.prototype` is undefined

**Comment by alampros** [comment]
Oh duh. Good call!

**Comment by mathieudutour** [comment]
I found a fix, should ship with v48 next week

**Comment by alampros** [comment]
Great news!

Sketch version 48?

**Comment by mathieudutour** [comment]
yes
