### ISSUE TITLE
Typescript typings support

### ISSUE THREAD

**Issue by ricokahler** [airbnb/react-sketchapp#206]
I am currently writing typings for react-sketchapp. I plan on publishing these typings to `@types/react-sketchapp` but an alternative to that is having the typings included in this repo itself. [This is done by including a `typings` field in the `package.json` that references a typings file (e.g. `react-sketchapp.d.ts`)](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package).

Including the typings first-party enables better typescript support as well as better javascript support (without a typescript dependency) for editors that use the typescript language service.

Proposal:

If you give me your blessing, I'd like to fully type this library and include those typings in a pull, else it's going to `@types/react-sketchapp`.

**Comment by ljharb** [comment]
A DefinitelyTyped lib is the proper place to put it; typescript types don’t belong in a non-TypeScript repo, especially since there’s no way to prevent drift.

**Comment by ricokahler** [comment]
@ljharb would you be open to a full typescript port? I'd do it.

**Comment by ljharb** [comment]
No, Airbnb does not use TypeScript at this time, so none of our repos should be using it either.

**Comment by ricokahler** [comment]
Alright I'll publish the typings to `@types` sometime today and close this then I might add a pull for documentation changes to let people know it exists but that's all.

Thanks.

**Comment by ljharb** [comment]
That sounds fine, thanks!

**Comment by ricokahler** [comment]
@ljharb Here is the pull for the typings if you'd like to review them for correctness. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21637

I'll add the documentation pull after this pull gets accepted.

**Comment by jongold** [comment]
Sweet - agreed that we should keep this repo flow typed, but super
appreciative of your work making this better for the typescript community :)

On Nov 19, 2017 6:39 PM, "Rico Kahler" <notifications@github.com> wrote:

@ljharb <https://github.com/ljharb> Here is the pull for the typings if
you'd like to review them for correctness. DefinitelyTyped/
DefinitelyTyped#21637
<https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21637>

I'll add the documentation pull after this pull gets accepted.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/airbnb/react-sketchapp/issues/206#issuecomment-345576586>,
or mute the thread

**Comment by ricokahler** [comment]
So I finished the typings and they got merged into DefinitelyTyped but I think I made a small error.

In the flow `types.js` `SketchDocument.currentPage` is [typed without a getter](https://github.com/airbnb/react-sketchapp/blob/d1b1d0acf09c32d3a997c78d3480e03480004389/src/types.js#L43) but I see it [used like a getter (e.g. `() => SketchPage`) from here](https://github.com/airbnb/react-sketchapp/blob/d1b1d0acf09c32d3a997c78d3480e03480004389/examples/basic-setup/src/my-command.js#L78). Is this type incorrect? I'm not familiar with flow unfortunately.

Anyway, the [typescript typings I wrote mirror the flow types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3289762cca59308bf092e4b49ea2242ef27fc23e/types/react-sketchapp/index.d.ts#L34) and I don't think it's working correctly.

Is the correct type for `currentPage` `() => SketchPage`?

**Comment by ljharb** [comment]
That indeed seems like the [way it's used in the codebase](https://github.com/airbnb/react-sketchapp/search?utf8=✓&q=currentPage&type=), which suggests that [this line](https://github.com/airbnb/react-sketchapp/blob/master/src/types.js#L43) has a bug.
