### ISSUE TITLE
Live reload not working

### ISSUE THREAD

**Issue by himedlooff** [airbnb/react-sketchapp#211]
**Expected behavior:**

In the styleguide example when running `npm run render` and changing `designSystem.js` the Sketch doc should be updated.

**Observed behavior:**

Running `npm run render` throws the following error and the Sketch doc does not update until you restart Sketch:

```
npm run render

> styleguide@ render /Users/mike/code/react-sketchapp/examples/styleguide
> skpm-build --watch --run

🖨  Copied src/manifest.json in 3ms
/bin/bash: ~/Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool: No such file or directory
Looks like we can't find Sketch.app.\nYou can specify where to look for it by running:\n\necho "sketchPath: ABSOLUTE/PATH/TO/Sketch.app" > ~/.skpmrc
🛠  Built ./main.js in 1248ms
```

**How to reproduce:**

Run `npm install && npm run render` in `react-sketchapp/examples/styleguide`

**Sketch version:**

47.1

**Comment by himedlooff** [comment]
I followed the error message and created `~/.skpmrc` with the contents `sketchPath: '~/Applications/Sketch.app'` and that did not resolve the error.

**Comment by himedlooff** [comment]
I also ran `defaults write ~/Library/Preferences/com.bohemiancoding.sketch3.plist AlwaysReloadScript -bool YES`

**Comment by dchen** [comment]
@himedlooff My guess is your sketchPath should be /Applications/Sketch.app and not ~/Applications/Sketch.app. Can you verify by running `ls /Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool` and see if it's there?

**Comment by himedlooff** [comment]
I moved my Sketch.app file from `~/Applications` to `/Applications` and it works now. The `.skpmrc` file does not seem to have an effect.

**Comment by maciej-gurban** [comment]
I've run into the same issue. My `.skmrc`:
```
sketchPath: '~/Downloads/Sketch.app'
```
Running `ls ~/Downloads/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool` returns:
```
/Users/MY_USER/Downloads/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool
```

When running `npm run render` I get:
```
 basic-setup@1.0.0 render /Users/maciej/dev/ads/react-sketchapp/examples/basic-setup
> skpm-build --watch --run

🖨  Copied src/manifest.json in 6ms
/bin/bash: ~/Downloads/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool: No such file or directory
Looks like we can't find Sketch.app.\nYou can specify where to look for it by running:\n\necho "sketchPath: ABSOLUTE/PATH/TO/Sketch.app" > ~/.skpmrc
🔧  Built ./my-command.js in 3306ms
```

**Comment by mathieudutour** [comment]
`~/Downloads/Sketch.app` isn't a proper path, the `~` isn't expand by default. With `/Users/MY_USER/Downloads/Sketch.app` is should work fine

**Comment by maciej-gurban** [comment]
That helped, thank you!
