### ISSUE TITLE
Can't run basic-setup example

### ISSUE THREAD

**Issue by LincMitch** [airbnb/react-sketchapp#213]
_I am..._
| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**
Run basic-setup example successfully.

**Observed behavior:**
I get this error:
TypeError: MSAttributedString.alloc().initWithAttributedString is not a function. (In 'MSAttributedString.alloc().initWithAttributedString(attribStr)', 'MSAttributedString.alloc().initWithAttributedString' is undefined)
line: 2813
sourceURL: /Users/lincolnmitchel/Documents/react-sketchapp-1.0.0-beta.5/examples/basic-setup/basic-setup.sketchplugin/Contents/Sketch/my-command.js
column: 72
stack: makeAttributedString@/Users/lincolnmitchel/Documents/react-sketchapp-1.0.0-beta.5/examples/basic-setup/basic-setup.sketchplugin/Contents/Sketch/my-command.js:2813:72
makeTextLayer@/Users/lincolnmitchel/Documents/react-sketchapp-1.0.0-beta.5/examples/basic-setup/basic-setup.sketchplugin/Contents/Sketch/my-command.js:15026:66
renderBackingLayers@/Users/lincolnmitchel/Documents/react-sketchapp-1.0.0-beta.5/examples/basic-setup/basic-setup.sketchplugin/Contents/Sketch/my-command.js:14977:44
flexToSketchJSON@/Users/lincolnmitchel/Documents/react-sketchapp-1.0.0-beta.5/examples/basic-setup/basic-setup.sketchplugin/Contents/Sketch/my-command.js:6061:51
map@[native code]
flexToSketchJSON@/Users/lincolnmitchel/Documents/react-sketchapp-1.0.0-beta.5/examples/basic-setup/basic-setup.sketchplugin/Contents/Sketch/my-command.js:6063:31
map@[native code]
flexToSketchJSON@/Users/lincolnmitchel/Documents/react-sketchapp-1.0.0-beta.5/examples/basic-setup/basic-setup.sketchplugin/Contents/Sketch/my-command.js:6063:31
renderToSketch@/Users/lincolnmitchel/Documents/react-sketchapp-1.0.0-beta.5/examples/basic-setup/basic-setup.sketchplugin/Contents/Sketch/my-command.js:4967:45
/Users/lincolnmitchel/Documents/react-sketchapp-1.0.0-beta.5/examples/basic-setup/basic-setup.sketchplugin/Contents/Sketch/my-command.js:7165:30
run@/Users/lincolnmitchel/Documents/react-sketchapp-1.0.0-beta.5/examples/basic-setup/basic-setup.sketchplugin/Contents/Sketch/my-command.js:18795:17
run@[native code]

**How to reproduce:**
Installed a clean version of react-sketch app and run Basic-Setup.

**Versions:**
SketchApp 48
skpm 1.0.10
npm 5.5.1
OS 10.12.6

**Comment by dericgw** [comment]
@LincMitch It looks like there is an issue with this working with Skecth 48. You can download Sketch 47 [here](https://www.sketchapp.com/updates/) if you want to get up and going with it until a fix is applied.

**Comment by LincMitch** [comment]
Thx @dericgw. With Sketch 47 it works fine.

**Comment by sskyy** [comment]
I'm using sketch 47.1. When I run `npm run render`, I got:

```
🖨  Copied src/manifest.json in 12ms
TypeError: null is not an object (evaluating 'context.document.currentPage')
line: 14644
column: 114
🔩  Built ./my-command.js in 2224ms
```

Please help.
