### ISSUE TITLE
Missing script: npm run render

### ISSUE THREAD

**Issue by antoniobrandao** [airbnb/react-sketchapp#215]
At http://airbnb.io/react-sketchapp/ we are told to try this:

    git clone https://github.com/airbnb/react-sketchapp.git
    cd react-sketchapp/examples/basic-setup && npm install
    npm run render

But the script doesn't exist 

    npm run render
    npm ERR! missing script: render

**Comment by dchen** [comment]
@antoniobrandao Can you make sure you're in `react-sketchapp/examples/basic-setup` when you run `npm run render`?

**Comment by antoniobrandao** [comment]
I didn't realise I had to enter the folder, sorry. Would have had more luck if I had simply copy-pasted.... 

Thanks

**Comment by dchen** [comment]
Glad it worked!
