### ISSUE TITLE
SVG via react-primitives

### ISSUE THREAD

**Issue by LincMitch** [airbnb/react-sketchapp#220]
As we can now render SVG to Sketchapp. Does that mean we can also in theory render to web using react primitives?

If so, anyone got an example?
If not, is it in the pipeline?

**Comment by jongold** [comment]
Render SVG to web via React Primitives? That won't work - only the base set of primitives are wrapped in React Primitives.

**Comment by LincMitch** [comment]
Thx @jongold, thought that would be the case. Was hoping I was wrong and that an SVG could be declared as primitive type **Image**.
