### ISSUE TITLE
Build new tools on top of Sketch?

### ISSUE THREAD

**Issue by LincMitch** [airbnb/react-sketchapp#222]
In the readme file under **What can I do with it?** it says > Build new tools on top of Sketch
Do you mean like the component picker here: https://youtu.be/hNwQPJy-XZY?t=25m2s

Is there a code example to show how to do this?

**Comment by jongold** [comment]
Exactly like that! Unfortunately we weren't able to open source our component picker, and it was a non-trivial amount of work, but https://github.com/airbnb/react-sketchapp/pull/108 should give you a pointer in how you might achieve similar.
