### ISSUE TITLE
Programmatically output .sketch file

### ISSUE THREAD

**Issue by alampros** [airbnb/react-sketchapp#224]
Is there currently a way to render the generated `<Document>` out to a `.sketch` file? I vaguely recall the ability to do so at one point long ago, but I can't seem to find any documentation on it now.

**Comment by mathieudutour** [comment]
you can but that's outside the scope of `react-sketchapp`. Check out http://sketchplugins.com/d/234-how-can-i-save-document-to-sketch-file, you might find what you want :)

**Comment by jongold** [comment]
https://github.com/jongold/sketch-utils this might still work :)
