### ISSUE TITLE
Render script runs in first open document regardless of window focus

### ISSUE THREAD

**Issue by daneden** [airbnb/react-sketchapp#23]
**Expected behavior:** running `npm run render` should run the script in the currently open/focused document.

**Observed behavior:** running `npm run render` runs the script in the first document opened in the current window/session.

**How to reproduce:**
1. Open or create two Sketch documents
2. Focus the second document window/tab
3. Run `npm run render`
4. The second document is unchanged; the first, unfocused document is where the contents are rendered.

**Sketch version:** 43.2

**Comment by jongold** [comment]
Ooh interesting — I think this might be a hard limitation with the current version of `sketchtool`, unfortunately.

```
λ sketchtool run
Missing arguments for command ‘run’.


Usage: sketchtool run <bundle> <command> [ --application=<path> | -A <path> ] [ --new-instance{=YES|NO} | --no-new-instance | -N {<YES|NO>} ] [ --wait-for-exit{=YES|NO} | --no-wait-for-exit | -W {<YES|NO>} ] [ --context=<string> | -C <string> ]

Run a command from a plugin, inside Sketch.

Arguments:

	bundle            plugin bundle containing the command to run
	command           the command to run

Options:

	--application     The version of Sketch to launch. If not supplied, the default is to use the version containing sketchtool. (optional).
	--new-instance    Launch a new instance of Sketch, even if one is already running. (optional, defaults to NO).
	--wait-for-exit   Wait for Sketch to exit before returning from this command. (optional, defaults to NO).
	--context         JSON dictionary of values to pass in to the plugin. (optional).
```

cc @bomberstudios

**Comment by mathieudutour** [comment]
Is it? I would guess it's coming from `context.document` here: https://github.com/airbnb/react-sketchapp/blob/master/examples/basic-setup/src/my-command.js#L71

You can access all the documents with `NSApplication.sharedApplication().orderedDocuments()`.
Here is a small function (not tested so probably doesn't work) to get the focused document or create a new one if there is nothing opened yet:
```js
function getMainDocument (context) {
	const documents = NSApplication.sharedApplication().orderedDocuments()
	if (!documents || !documents.length) {
		return context.api().Application(context).newDocument()
	}
	return documents.find(d => d.documentWindow().isMainWindow()) || documents[0]
}
```

**Comment by daneden** [comment]
@mathieudutour that snippet still isn’t working, sadly. Because the application is in the background when the script runs (assuming it's being run from the command line or after a `.js` file is changed), all the documents return `false` for `isMainWindow()`, which once again causes the script to run in the first open document.

@jongold it looks like sketchtool's `--context` argument may come in handy here. The `render` script runs `skpm build --run`, but `--run` seems to run the plugin [without context](https://github.com/sketch-pm/skpm/blob/master/lib/skpm-build.js#L135). Perhaps the `render` script can instead build the plugin using `skpm` and then run it using `sketchtool` with provided context?

**Comment by jongold** [comment]
🤔 if we can fix this with a patch to `skpm` that would be the best. I'd also love reusable helpers for 'mainDocument' / 'documentByName' / etc, jQuery style. is that feasible? `sketchtool run` was added recently and I still don't full understand how context works :)

**Comment by mathieudutour** [comment]
> all the documents return false for isMainWindow()

🤔  hum I didn't know it was possible to not have a main window. I'm not a cocoa expert by no mean so there might be a way that I don't know about

I think the context option is just to pass some arguments to the plugin, not sure how we could use it. And as long as we are using `context.document` in the render, skpm won't be able to do anything

**Comment by jongold** [comment]
you can pass whatever you want into `render` -

if we added a 'target' to 'context' you could equally do `render(<Foo />, context.target)`

**Comment by mathieudutour** [comment]
yes that's what I mean, we need to change the examples. but `target` would be very react-sketchapp specific, not sure we want to bake that into skpm. But what we can do is allow to pass the context as an argument to the `--run` option of skpm

**Comment by daneden** [comment]
Ack, so my assumption was wrong. I thought that `context.document` would point to the current active document even with a backgrounded window, but it, too, always points to the first open document.

**Comment by thecalvinchan** [comment]
is there documentation for what `context` contains? I'm trying to work with this issue but I can't seem to find any documentation anywhere

**Comment by macintoshhelper** [comment]
Hi, seems that `render` now renders to the current active window, even if it's in the background. It doesn't seem possible to choose which document `react-sketchapp` renders too though with the Sketch plugin API.

I've tried this, but it doesn't work for some reason:

```js
const sketch = require('sketch');

export default () => {
  const documents = sketch.getDocuments();
  let document;

  for (const doc of documents) {
    // Hardcoded ID used, so it's possible to use `Document.open('path/to/the/document.sketch'`, then retrieve the ID and render to the newly opened document
    if (doc.id === '598686A3-DD5B-49CE-B43E-5DC268BE338D') {
      document = doc;
    }
  }

  render(<App />, document.sketchObject);
};
```

@thecalvinchan `context` is mostly deprecated afaik. 

It's unstable, but this is what I get when console.logging it:

```js
{
  document: <MSDocument: 0x70000000>,
  selection: __NSArray0 [],
  scriptPath: '/Users/*/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin',
  scriptURL: <NSURL>
 file:///Users/*/Library/Application%20Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin,
  api: [Function],
  command: <MSPluginCommand: 0x600000000> }
}
```
