### ISSUE TITLE
Performance issue with makeSymbol()

### ISSUE THREAD

**Issue by alampros** [airbnb/react-sketchapp#230]
I hesitated to submit an issue for this because this project is so amazingly cool and it blows my mind that this is even possible...*however*...

I have a project wherein I am rendering ~50 relatively simple SVGs (~300 symbols) into symbols and it is taking around **20 minutes** to render (all while locking up the sketch process).

Is there something I'm doing here that stands out as super non-performant? Is this just an inherently intensive process that actually *should* take this long?

**Expected behavior:**  
Not instant, but closer to the 2-3 minute range.

**Observed behavior:**  
Render takes between 15-25 minutes.

**How to reproduce:**  

See the demo repo here: https://github.com/alampros/react-sketchapp-svg-render-test

I am importing my SVGs via a [babel plugin](https://github.com/alampros/babel-plugin-react-sketchapp-svg) and calling `makeSymbol` on immediately in the import file like so:

> Note: None of the SVGs are actually being rendered to a page – they are output only to the symbols page (for use as a shared library).

#### `svgImports.js`:
```js
import IconAngleDown from '../svg-tmp/angle-down.svg'
import IconAngleLeft from '../svg-tmp/angle-left.svg'
//... 47 more SVGs imported

export default {
  // Generate 5 color variants for each SVG
  'Black': {
    'angle-down': makeSymbol(() => <IconAngleDown fill="rgb(0, 0, 0)" />, 'Icon / angle-down / Black'),
    'angle-left': makeSymbol(() => <IconAngleLeft fill="rgb(0, 0, 0)" />, 'Icon / angle-left / Black'),
    ...
  },
  'White': {
    'angle-down': makeSymbol(() => <IconAngleDown fill="rgb(255, 255, 255)" />, 'Icon / angle-down / White'),
    'angle-left': makeSymbol(() => <IconAngleLeft fill="rgb(255, 255, 255)" />, 'Icon / angle-left / White'),
    ...
  }
  ...
}
```

#### `main.js`:
```jsx
import { Document, Page, Text, render } from 'react-sketchapp'
import './svgImports.js'

const IconsPage = () => {
  return (
    <Document>
      <Page name="Page 1">
        <Text>See the symbols page</Text>
      </Page>
    </Document>
  )
}

const onRun = () => {
  render(<IconsPage />)
}

module.exports = onRun
```

**Sketch version:** 48.2

I'm running on [this](http://browser.geekbench.com/geekbench3/379009) late 2013 rMBP (2.6ghz core i7) with 16gb RAM and an SSD.

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

[Demo repository](https://github.com/alampros/react-sketchapp-svg-render-test)

`skpm-build` takes only **2.3s** to run:

![screen shot 2017-12-21 at 8 57 57 am](https://user-images.githubusercontent.com/297461/34258728-48dfeba8-e62d-11e7-9891-a260e548572e.png)

`skpm-build --run` takes **~16m**:
![screen shot 2017-12-21 at 9 48 50 am](https://user-images.githubusercontent.com/297461/34260536-4c1a0234-e634-11e7-882d-b2c03e3c834d.png)

**Comment by mathieudutour** [comment]
wait are you talking about the build or the rendering?

**Comment by mathieudutour** [comment]
do you have a repo with a repro?

**Comment by alampros** [comment]
The render.

`skpm-build` takes only **2.3s** to run:

![screen shot 2017-12-21 at 8 57 57 am](https://user-images.githubusercontent.com/297461/34258728-48dfeba8-e62d-11e7-9891-a260e548572e.png)

`skpm-build --run` takes **~16m**:
![screen shot 2017-12-21 at 9 48 50 am](https://user-images.githubusercontent.com/297461/34260536-4c1a0234-e634-11e7-882d-b2c03e3c834d.png)

Unfortunately, I can't share the project. I'll try to put together a repro repo soon.

**Comment by alampros** [comment]
@mathieudutour - https://github.com/alampros/react-sketchapp-svg-render-test

**Comment by alampros** [comment]
I just pushed [a branch](https://github.com/alampros/react-sketchapp-svg-render-test/tree/no-symbols) that doesn’t use symbols and it goes *waaay* faster

**Comment by LincMitch** [comment]
The repo with symbols rendered in a sec.
