### ISSUE TITLE
What Sketch versions are supported? 43-47.1? 48.x?

### ISSUE THREAD

**Issue by sogen** [airbnb/react-sketchapp#236]
| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

Tried using Sketch 48 but didn't work, so after reading the issues found that 47.1 is supported, and yes it works.
Just wanted to know if 48 support is on the horizon so I can update Sketch.

**Sketch version:**
47.1

**Comment by LincMitch** [comment]
The latest, 48.2 works. But there is issues, as some examples refer to older versions. For as fix see #229. As you'll see, the fix has been merged, but we are waiting on a new release.

**Comment by sogen** [comment]
Great! Updating Sketch 😁
