### ISSUE TITLE
No Text Style matched when using TextStyles.get  (see styleguide example)

### ISSUE THREAD

**Issue by jeroenransijn** [airbnb/react-sketchapp#240]
Hi I am trying to generate text styles and I have done this successfully in the past, but now the same code is not working for me. Than I checked in the styleguide example and I get the same result. It does create the text styles, but it doesn't apply the text style.

![image](https://user-images.githubusercontent.com/564463/34746270-36f02636-f548-11e7-8c9f-11b7ebd26f9c.png)

**Sketch version:**

48.2 (47327)

**Comment by LincMitch** [comment]
I'm having the same "No Text Style" issue. Good to here that it worked in the past.
Same Sketch version: 48.2 (47327)

**Comment by thierryc** [comment]
On Sketch 50 BETA.  I get this error: context.document.documentData().layerTextStyles().addSharedStyleWithName_firstInstance is not a function.
