### ISSUE TITLE
TypeError: {} is not a function

### ISSUE THREAD

**Issue by nilobarp** [airbnb/react-sketchapp#241]
_I am..._ Reporting a bug or issue

**Expected behavior:**
Should build

**Observed behavior:**
`TypeError: {} is not a function. (In '{}("")', '{}' is an instance of Object)`

**How to reproduce:**
Using package versions
```
"prop-types": "^15.5.8",
"react": "^15.4.2",
"react-dom": "15.4.2",
"react-sketchapp": "^1.0.0",
"react-test-renderer": "15.4.2",
"webpack-shell-plugin": "^0.5.0"
```

Build this
```
class Document extends React.Component {
  render() {
    <Artboard name="Test">
      <View>
         <Text>Sign up</Text>
      </View>
    </Artboard>
  }
}

const onRun = () => {
  render(<Document />, context.document.currentPage());
};

module.exports = onRun;
```
**Sketch version:**
48.2

**Please attach screenshots, a zip file of your project, and/or a link to your github project**
![image](https://user-images.githubusercontent.com/1141369/34802885-387d5456-f6c4-11e7-815c-aca27c6e34ac.png)

![image](https://user-images.githubusercontent.com/1141369/34802899-4b8be74c-f6c4-11e7-81f0-2dd1f15778c2.png)

**Comment by mathieudutour** [comment]
try with
```js
class Document extends React.Component {
  render() {
    <Artboard name="Test">
      <View>
         <Text>Sign up</Text>
      </View>
    </Artboard>
  }
}

export default () => {
  render(<Document />, context.document.currentPage());
};
```
?

**Comment by joevbruno** [comment]
The above simple snippet didn't work for me. Still had the same issue. I'm not sure why, **but completely removing node_modules and re-yarn installing resolved this issue for me** (using it in a mono-repo). After that, both the above code snippet, and my original file worked again. I began receiving this error after upgrading to the both the latest version of the library and Sketch to 48.2 (specifically for SVG use).

**Comment by weaintplastic** [comment]
@mathieudutour I'm running into the same issues every now and then but couldn't track down the original cause. I'm using a monorepo with yarn workspaces enabled as well, just as @joevbruno . But re-yarn doesn't work everytime. Any clue what where I can start investigating?

**Comment by mathieudutour** [comment]
I'm not using yarn and I'm thinking it's an issue with yarn

**Comment by joevbruno** [comment]
@weaintplastic just to clarify, I'm not using yarn workspaces - I am using yarn and lerna.

**Comment by weaintplastic** [comment]
@joevbruno oh alright, sorry. I was assuming you use yarn workspaces.
@mathieudutour Thanks so much for the fast reply. I'll continue to investigate. I'll keep you guys posted if I should come to any result.

**Comment by mathieudutour** [comment]
yeah but it's probably yarn messing up the node_modules. When you do a `skpm create`, it will run `npm install` so if you run yarn on top of it, it will probably break things. Happy to accept a PR to skpm to support yarn

**Comment by weaintplastic** [comment]
actually I just use the @skpm/builder and didn't even use the `skpm create` back then (but was using the template).

**Comment by weaintplastic** [comment]
It might be some environment thing and webpack. When it breaks `index.js` declares `nodeFs` like this

```js
var nodeFs = {}("");
```
when it is working the declaration is

```js
var nodeFs = {};
```

**Comment by thisjeremiah** [comment]
I've also been getting this error. Unfortunately, I have not been able to simply remove and replace `node_modules` to get it working. 

I'm using yarn workspaces (w/o lerna). If I only install packages for `react-sketchapp/examples/basic-setup-typescript` under a single workspace (e.g. `packages/a`), it works fine. But, if I install any packages under another workspace (e.g., `packages/b`), it will fail.

However, I have pinpointed the issue. When i install packages from a new workspace, some code changes in `node_modules/yoga-layout/build/Release/nbind.js`. `var nodeFS = {}` becomes `var nodeFS = {}("")`.

So, it seems like the problem must be between `yoga-layout` and yarn workspaces.

**Comment by thisjeremiah** [comment]
Seems like the latest javascript build v1.8.0 fixed this issue: https://github.com/facebook/yoga/issues/642#event-1396878128. So, it should just be an issue of `react-sketchapp` updating `yoga-layout` to `1.8.0`, ... which it seems has already been done, just not in an official release 😔

**Comment by nampdn** [comment]
Will this get fixed when new release of react-sketchapp is out?

**Comment by mathieudutour** [comment]
Yes
