### ISSUE TITLE
View 'style' prop fails validation when passed StyleSheet ordinal

### ISSUE THREAD

**Issue by dmeehan1968** [airbnb/react-sketchapp#242]
_I am using StyleSheet.create() to compose styles to be passed to sketchpad primitive components_

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**

```
import React from 'react'
import { Text, View, StyleSheet } from 'react-sketchapp'

export default class App extends React.Component {

  render() {
    return (
      <View style={styles.container}>
        <Text>Hello World</Text>
        </View>
        )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  }
})
```

The above code should compile and run without error.  Passing ```styles.container``` to ```View``` should be acceptable.

**Observed behavior:**

```
Warning: Failed prop type: Invalid prop 'style' supplied to 'View'.
    in View (created by App)
    in App (created by Document)
    in view (created by View)
    in View (created by Document)
    in view (created by View)
    in View (created by Document)
    in artboard (created by Artboard)
    in Artboard (created by Document)
    in Document
```

**How to reproduce:**

The same error occurs with react@15.4.2 and react-test-renderer@15.4.2 and react@16.0.0 and react-test-renderer@16.0.0.

```
 <View style={StyleSheet.flatten(styles.container)}>
```

The above edit works around the problem, as the style object is passed instead of the ordinal value generated when the StyleSheet is created.  This is what the View component does internally, but because it fails PropType validation the error is produced.

The problem appears to be introduced in [ViewStylePropTypes.js](https://github.com/airbnb/react-sketchapp/blob/326e070f0007076c71fb4144f65c4d811a4c6ac6/src/components/ViewStylePropTypes.js#L1) which doesn't define the shape of the style prop, so it fails PropType validation.  By commenting out the style prop definition the code runs as expected.

**Other Observations:**

This is likely to affect the following react-sketchapp components: Artboard, Text, View

**Sketch version:**

0.48.2

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

**Comment by mathieudutour** [comment]
See #9. It's not an error, only a warning. Shouldn't affect how it is working
