### ISSUE TITLE
Failing to require a local image

### ISSUE THREAD

**Issue by pastawoua** [airbnb/react-sketchapp#25]
Tried to include a local image to the basic-setup example and it's failing to load it. Is this an issue with skpm or just unsupported at this stage?

Thanks!

```
Executing post-build scripts
error Error while building ./my-command.js
./src/pic.jpg
Module parse failed: /react-sketchapp/examples/basic-setup/src/pic.jpg Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./src/my-command.js 55:70-90
- reactTreeToFlexTree: 0.003
- computeLayout: 0.067
new renderer: 0.083
```

**How to reproduce:**
`<Image source={require('./pic.jpg')} style={{ width: 200, height: 200 }} />`

**Sketch version:**
43.2

<img width="261" src="https://cloud.githubusercontent.com/assets/437646/25418966/e77a69ac-2a92-11e7-96fa-7a8e4905398a.png">

**Comment by jongold** [comment]
Currently, we load images from URLs - this should be relatively easy to implement though.

Would love a contribution if anyone feels up to it - I won't have time to tackle it myself at least until next week

Some notes:
- I'm not a webpack expert but I think you should be able to use some combination of loaders
- skpm just wraps webpack
- you can give skpm a custom webpack config by adding a `webpack.config.js` file in the root of your project (wherever your package.json is)
- some changes will also have to be made in `src/renderers/ImageRenderer.js` (remember to npm link!)
- once it's all working we can discuss moving the updated webpack config into `skpm` itself

**Comment by pastawoua** [comment]
@jongold thanks, I can give it a go!

**Comment by pastawoua** [comment]
@jongold working now by tweaking `skpm` only. I've opened a PR at https://github.com/sketch-pm/skpm/pull/37

**Comment by jongold** [comment]
!!!!!!!!!!! @pastawoua you're awesome. let's take discussion over to https://github.com/sketch-pm/skpm/pull/37 :)

**Comment by pastawoua** [comment]
@jongold 👍 

After going through the rabbit hole of importing images, I realised that the resolution (@2x, @3x) is going to be an issue, I guess it could be parsed and always imported at the highest available resolution. The next question is are pngs/jpgs really appropriate in a design system for things like icons, wouldn't it be better to import svgs as Sketch can't tint images. How did you tackle managing icons on your side?

**Comment by rxb** [comment]
Not a drop in solution, but just wanted to share what I've been using to get my SVG icons (tinted with css) into sketchapp. 

First, made PNGs of all the SVGs with `https://github.com/skiddoo/grunt-convert-svg-to-png`, then used this express server to give all the pngs a localhost url with an optional param to tint them whatever color:

```
var express = require('express');
var path = require('path');
var gm = require('gm').subClass({imageMagick: true});

var app = express();

// serve colorized png
app.get('/:shape?', function(req, res){
	var { shape = 'checkmark' } = req.params;
	var { color = 'black' } = req.query
	var filename = path.join(__dirname, `public/${shape}.png`);
	gm(filename)
		.fill(color)
		.colorize(100)
		.stream()
		.pipe(res);
});

// start server
app.set('port', 4000);
var server = app.listen(app.get('port'), function() {
  var port = server.address().port;
  console.log('react-sketchapp icons on port ' + port);
});
```

Then in my icon component, it's split by platform. For web, it uses the usual `<svg>` tag and sprite shape, colored by css. For sketchapp, it uses the `<Image>` primitive and hits our new webserver:

```
		if(Platform.OS =='sketch')
			return(
				<Image
					source={{uri: `http://localhost:4000/${shape}?color=${color}`}}
					style={{width: 24, height: 24}}
					/>
			);

		if(Platform.OS =='web')
			return(
				<svg className="icon" style={{height: 24, width: 24, stroke: color, fill: 'none'}}>
					<use xlinkHref={`#icon-${shape}`} />
				</svg>
			);
```

**Comment by mathieudutour** [comment]
you should now be able to import local images with skpm

**Comment by LincMitch** [comment]
This seems to be an issue in v1.0.0.
