### ISSUE TITLE
npm run render ->Error while enabling the Sketch developer mode -> SyntaxError: Unexpected identifier 'original'

### ISSUE THREAD

**Issue by DarrenBro** [airbnb/react-sketchapp#251]
**Reporting an issue**

After running the below steps from https://www.npmjs.com/package/react-sketchapp;

1. git clone https://github.com/airbnb/react-sketchapp.git
2. cd react-sketchapp/examples/basic-setup && npm install
3. npm run render

I get the error below from bash terminal.
Any advice on resolutions is very appreciated. 

![image](https://user-images.githubusercontent.com/8710774/35572797-51f89ef0-05cd-11e8-844a-a155efa6857b.png)

**Comment by LincMitch** [comment]
What SketchApp version you using?

**Comment by DarrenBro** [comment]
![image](https://user-images.githubusercontent.com/8710774/35596053-9ecc2c7c-0610-11e8-8bff-7ac2287dfb2d.png)

**Comment by LincMitch** [comment]
What version of npm is installed (npm --version)
How about Xcode, that installed? Don't think the setup mentions needing Xcode, but I pretty sure it's needed

**Comment by DarrenBro** [comment]
npm --version -> 5.6.0
Will install Xcode now.

**Comment by LincMitch** [comment]
Well it only worked for me once I installed Xcode. It makes sense as it's building and then running that plugin in SketchApp. Don't think this can be done with just React code.

If this resolves the issue for you too, then it would be great to see this as part of the setup instructions.

Let us know how you go.

**Comment by DarrenBro** [comment]
Will do man, haven't had the time just yet but next day or so I'll get back to ya.

**Comment by LincMitch** [comment]
OK. When your ready, if you haven't done it before, its a pretty painless.  Here is the link to install Xcode from the Appstore [https://itunes.apple.com/au/app/xcode/id497799835?mt=12](url)

**Comment by DarrenBro** [comment]
Xcode was the exact fix, thanks! Had to install Sierra to be able to install xcode so just wanted to get some time for that, thanks @LincMitch 👍

**Comment by tafelito** [comment]
Hi, I'm having the same issue and I do have xcode installed. It only happens the first time I run npm install. After that it works fine and I'm able to render to sketch

**Comment by nitish24p** [comment]
Just a question, im getting the same issue as mentioned here.. Is installing xcode a mandate ? i dont have xcode also i am running on OSX el capitan 10.11.6.

Sketch version: 48.3
sketchapp version: 1.1.0
Node: 8.2.1

**Comment by DarrenBro** [comment]
Yes you need xcode @nitish24p

**Comment by LincMitch** [comment]
In terminal `defaults write ~/Library/Preferences/com.bohemiancoding.sketch3.plist AlwaysReloadScript -bool YES` This resolved the issue for me. Found it at https://github.com/skpm/skpm/issues/137

**Comment by haysclark** [comment]
Adding to @LincMitch answer, for those that want to know a little more (inlined to avoid future stale links):

Per the _react-sketchapp_ FAQ under [I'm running a project as a plugin & Sketch isn't showing my changes](https://github.com/airbnb/react-sketchapp/blob/master/docs/FAQ.md#im-running-a-project-as-a-plugin--sketch-isnt-showing-my-changes):

>Sketch has a developer mode which refreshes plugins before running. If you're using skpm this should be set up automatically, but just in case try running
>
>```defaults write com.bohemiancoding.sketch3.plist AlwaysReloadScript -bool YES```

_Sketch_'s official _Dev Environment_ documentation on [_Always reload scripts before running_](https://developer.sketch.com/guides/preferences/):

> **Always reload scripts before running**
>
> For performance reasons, Sketch caches the contents of the Plugins folder. This is very convenient for users, since Plugins run very fast, but makes your life hard if you’re a developer. That’s why we added a preference to disable this caching mechanism and force Sketch to always reload a Plugin’s code from disk:
> 
>> `defaults write com.bohemiancoding.sketch3 AlwaysReloadScript -bool YES`
> 
> If you enable this, as soon as you save your script it will be ready for testing in Sketch (bye bye relaunching it just to test a small change!)
> 
> Please note that this setting determines whether the source of the script is reloaded from disc whenever Sketch makes a new javascript context for the script. If it’s NO, the source is cached, if it’s YES, the source is always reloaded from disc.
> 
> What it doesn’t do, however, is change when a new JavaScript context is made. For long-running scripts, the same context is held in memory (it has to be — the running script is using it) until the script exits. So if you’re testing a long-running script, you will still have to find a way to stop the script, so that the context gets thrown away (that usually means relaunching Sketch, or setting `coscript.setShouldKeepAround(false)`).
