### ISSUE TITLE
What skills are needed to contribute?

### ISSUE THREAD

**Issue by LincMitch** [airbnb/react-sketchapp#252]
So far I am using React-SketchApp and learning Reactjs, React-primitives and Styled-components. If I wanted to contribute to the repo would I need to learn **Nodejs** and is that creating the **node**_modules folder? Is there anything else to learn?

**Comment by mathieudutour** [comment]
It depends what you want to contribute to.

A lot can be done by fixing or creating examples without requiring too much knowledge about react renderers, sketch plugins, and such obscure things:
- #192
- #191
- #176

I've seen that you also help others fix their issues, that's the best form of contribution!

**Comment by LincMitch** [comment]
OK, good point. I'll try contribute this way.
