### ISSUE TITLE
Page component doesn't support style prop

### ISSUE THREAD

**Issue by dmeehan1968** [airbnb/react-sketchapp#255]
_I am..._

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**

```Page``` component should accept ```style``` prop and pass to underlying ```page``` component.   Maybe even just pass all props.

Without the ability to pass ```style```, Artboard position on the canvas cannot be controlled.

**Observed behavior:**

Currently only renders ```Page``` children into the ```page``` node.  Any props passed to ```Page``` are not passed to ```page```

**How to reproduce:**

```
render(<Document>
  <Page style={{ backgroundColor: 'red' }}>
    <Artboard>
      <View>
        <Text>Hello World</Text>
      </View>
    </Artboard>
  </Page>
</Document>)
```

NB: ```render``` is not supplied a context so that it renders all pages in the JSX

**Sketch version:**

48.2

**Comment by mathieudutour** [comment]
you cannot style a Sketch page tho...

**Comment by dmeehan1968** [comment]
@mathieudutour You do appear to be able to control position using ```flex``` etc., but I accept the example was poor.

**Comment by mathieudutour** [comment]
> You do appear to be able to control position using flex etc.

So does it work or not?

**Comment by dmeehan1968** [comment]
@mathieudutour The ```Page``` component provided by RSA does not pass any properties to the ```page``` underlying component.  I accept that some style properties are not supported at page level, but layout props do appear to.

**Comment by dmeehan1968** [comment]
@mathieudutour PR submitted.
