### ISSUE TITLE
Sketch crashing when running Styled Components Example

### ISSUE THREAD

**Issue by kharrop** [airbnb/react-sketchapp#257]
_I am..._

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**

When running the Styled Components example, I'm getting errors which causes Sketch to crash. I would expect Sketch to open up the example generated from running "npm run render".

**Observed behavior:**
Currently crashes Sketch when running "npm run render" from the terminal for this specific example.

I'm getting these errors:
console> Warning: Failed prop type: Invalid prop `style` supplied to `View`.
    in View (created by Styled(View))
    in Styled(View) (created by Document)
    in Document
console> Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `Text`, expected `object`.
    in Text (created by Styled(Text))
    in Styled(Text) (created by Document)
    in view (created by View)
    in View (created by Styled(View))
    in Styled(View) (created by Document)
    in Document
Unrecognized font family 'GT America'
Unrecognized font family 'Himalaya'
Unrecognized font family 'Himalaya'
Unrecognized font family 'GT America'
⚒  Built ./my-command.js in 6906ms

**How to reproduce:**
In terminal, navigate to the Styled Components directory, install npm, and enter "npm run render"

**Sketch version:**
48.2

[sketch_crash_notes.pdf](https://github.com/airbnb/react-sketchapp/files/1712451/sketch_crash_notes.pdf)

**Comment by kharrop** [comment]
FYI - When I run the plugin from the Sketch Plugin menu, it will generate the file. However, making any changes in the script file while this folder is watched causes Sketch to crash.
[sketch_crash_notes.pdf](https://github.com/airbnb/react-sketchapp/files/1712451/sketch_crash_notes.pdf)

**Comment by dmeehan1968** [comment]
I tried this, seeing if it was similar to #216 but it builds and runs fine, apart from the missing font messages.  I tried it with Sketch already running, and without.

You need to have the mentioned fonts already installed on your system - the example does nothing to dynamically load them, its just references them in the CSS.  Attempting to include the font files as part of the build process would require use of `require()` which is currently broken for non-.js/.json files (see #216)

**Comment by kharrop** [comment]
Strange, I even cleared about my node modules folder and ran "npm install".

I got this back: 
npm WARN animated@0.1.5 requires a peer of react-dom@* but none was installed.
npm WARN react-native-web@0.0.130 requires a peer of react-dom@15.4.x || 15.5.x || 15.6.x but none was installed.
npm WARN animated@0.2.1 requires a peer of react-dom@* but none was installed.
npm WARN styled-components-example@1.0.0 No repository field.

I also cleared out the font declarations inside of the js file to see if that resolved anything and Sketch still crashes.

In addition, I changed the path to the version of Sketch I have in my Applications folder as well as updated to 49 and it's still failing. This is the only example that seems to be failing for me - I've opened up others with no issue.

**Comment by kharrop** [comment]
Updating react breaks other dependencies as well, so I'm not sure how to proceed...

**Comment by dmeehan1968** [comment]
@kharrop Are you using the npm latest or cloning master from here?  Please confirm version.

**Comment by kharrop** [comment]
@dmeehan1968 I'm cloning master

**Comment by kharrop** [comment]
Closing this for now since it looks like it's an npm dependency issue and I'm unable to update at this time.
