### ISSUE TITLE
react-sketchapp-svg-uri like react-native-svg-uri [new feature]

### ISSUE THREAD

**Issue by thierryc** [airbnb/react-sketchapp#259]
https://github.com/vault-development/react-native-svg-uri

| -------------------------------------------------------------------------------------------------
| Requesting a new feature
| -------------------------------------------------------------------------------------------------

Any close solution like https://github.com/vault-development/react-native-svg-uri 
To load (fetch) SVG file ? 

```javascript
import { View, Svg } from 'react-sketchapp';
import SvgUri from 'react-sketchapp-svg-uri';

const TestSvgUri = () => (
  <View style={styles.container}>
    <SvgUri
      width="200"
      height="200"
      source={{uri:'http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg'}}
    />
  </View>
);
```

**Comment by mathieudutour** [comment]
you can probably fork https://github.com/vault-development/react-native-svg-uri, and replace the `react-native-svg` requires by `react-sketchapp`. That's not going to be part of the core tho

**Comment by thierryc** [comment]
Go https://github.com/thierryc/react-sketchapp-svg-uri
