### ISSUE TITLE
Multiple pages are created when using makeSymbol after saving

### ISSUE THREAD

**Issue by tafelito** [airbnb/react-sketchapp#262]
| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Observed behavior:**

When using symbols, while running `npm run render`, every time I save any new changes, a new page is created in sketch. This doesn't happen if makeSymbol is not used, but if makeSymbol was ever used, even if it's removed, it keeps happening unless stopping process and running it again.

**How to reproduce:**

Run any example that uses makeSymbol like the one @jongold created [here](https://github.com/airbnb/react-sketchapp/blob/master/examples/symbols/src/my-command.js), make any change while running live reloading 

**Sketch version:** 

48.2

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

Empty Project
![image](https://user-images.githubusercontent.com/5973652/36243329-0aa00e7a-11ef-11e8-9da9-2a5f8eea96d7.png)

After running `npm run render`, Page 2 is created

![image](https://user-images.githubusercontent.com/5973652/36243441-87087f06-11ef-11e8-9fd7-469a45e2e762.png)

After saving, Page 3 is created

![image](https://user-images.githubusercontent.com/5973652/36243367-34478244-11ef-11e8-80bf-159931ed8fad.png)

Is this how is supposed to work?

**Comment by LincMitch** [comment]
+1

**Comment by mathieudutour** [comment]
I believe this is fixed in #235

**Comment by tafelito** [comment]
btw using injectSymbols before rendering solves this issue, but I'm not sure what injectSymbols is really used for

**Comment by tafelito** [comment]
@mathieudutour I just tested it using changes from pull #235 and I believe still doing the same. I used @alampros git repo to test this if that does any help

**Comment by tafelito** [comment]
Ok so I just found that this only happens when using `context.document.currentPage()` as the 2nd parameter in render function. Removing that does not create new pages after saving
