### ISSUE TITLE
How to deal with components that aren't built with primitives?

### ISSUE THREAD

**Issue by hilary-L** [airbnb/react-sketchapp#266]
Have been exploring using react-sketchapp and react-primitives to get a component library into sketch for viewing. I watched a talk given by Leland that said that if you are building an app and need to use a component that can't be built with primitives, you should use platform extensions on your component files. That all makes sense, but what if I have a design/component that relies on one of these non-primitive elements... like a scrollview, or a tab system, or so forth? Is it just not possible to render them to sketch right now?

**Comment by mathieudutour** [comment]
no you would need to create your own primitives.

For example, the scroll view:
- on the web it's just a regular div with perhaps an `overflow` or something
- on RN, it's `ScrollView`
- on Sketch, it's just a `Group`

So you need to create 4 different files:
- ScrollView.js <- for the web
- ScrollView.ios.js <- for ios
- ScrollView.android.js <- for android
- ScrollView.sketch.js <- for sketch

You can then import the file `ScrollView` to reuse it as a primitive, the bundlers will pick the right file depending on the platform
