### ISSUE TITLE
Can't quickstart, need to override sketch path.

### ISSUE THREAD

**Issue by zaqqaz** [airbnb/react-sketchapp#27]
Hey :) 
First of all, thanks for this cool stuff!

But I faced with problem when I tried to use quickstart guide.
Actually now if we download sketch (https://www.sketchapp.com/)
default app name will be **Sketch 2.app**, so when we start 
`npm run render` 
we get error:
`/Applications/`**Sketch.app**`/Contents/Resources/sketchtool/bin/sketchtool ENOENT`

It's not very informative, especially for designers.
Actually, I think, we must handle this error and provide information about default config and sketch.app path overriding. 

Also, seems to be better provide a little information about sketch plugin manager and its config in readme. 

p.s. try to create PR soon.

**Comment by jongold** [comment]
We should document this better, but you should be able to make a `.skpmrc` in your home directory 

```
sketchPath: '/Applications/Sketch 1235454.app'
```

See https://github.com/sketch-pm/skpm/blob/master/lib/utils/config.js, sorry for the confusion!
