### ISSUE TITLE
Symbols example not working

### ISSUE THREAD

**Issue by dmeehan1968** [airbnb/react-sketchapp#271]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**

https://github.com/airbnb/react-sketchapp/tree/1974091c696470138216a54611abd125d5828af9/examples/symbols

Looking at the code, a composite symbol is created that defaults to a profile image and a red square.  The overrides specify that the image should be replaced and the red square replaced with a blue square with modified text.

**Observed behavior:**

No overrides are performed.  The rendered document does show overrides for each component as expected in the layer inspector, and appropriate changes can be made manually.

NB: Additionally, the URL specified as the image override no longer appears to be valid.

Looking at the source for both RSA and the SA plugin library suggests that the overrides property is not an object, but an array with objects with a particular set of properties - I can't see if this is being translated somewhere - https://github.com/BohemianCoding/SketchAPI/blob/e374fa3720ee7615353c5fe91f4ee437d3b8015e/docs/api/SymbolInstance.md

**How to reproduce:**

Build and run the example as documented.

**Sketch version:**
48.2

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

![sketch](https://user-images.githubusercontent.com/2016856/36473601-e45cd074-16ec-11e8-813f-f5ca31957c24.jpeg)

**Comment by dmeehan1968** [comment]
I've tried following the docs in my own project but couldn't get any overrides to work, so I turned to the example and found it not to be working.

**Comment by dmeehan1968** [comment]
Ok, I found the problem.  There's been a change in Sketchapp that removes the fixed object wrapper with '0' property value that contains the computed overrides.

Replace ([source](https://github.com/airbnb/react-sketchapp/blob/537ced5562ac67f877b53f40167a5f2148664a4a/src/renderers/SymbolInstanceRenderer.js#L215-L216))

```js
    symbolInstance.overrides = overrides;
    symbolInstance.overrides['0'] = overrides;
```
With:

```js
    symbolInstance.overrides = overrides;
```

However, this will trigger a Flow warning because the shape no longer matches the definition in the current release of [darknoon/sketchapp-json-flow-types](https://github.com/darknoon/sketchapp-json-flow-types).

There is a commit to that repo that [fixes the flow types](https://github.com/darknoon/sketchapp-json-flow-types/commit/e66d2a603aef47f91dfa110b019622b0d4f0204f), but not yet published.

That whole [SymbolInstanceRenderer.js](https://github.com/airbnb/react-sketchapp/blob/537ced5562ac67f877b53f40167a5f2148664a4a/src/renderers/SymbolInstanceRenderer.js) module is not well structured (IMHO) and it took me ages to figure out where it was breaking.  There's a lot of 'any' types which don't help with ensuring correctness of passed values.  Of course, it doesn't help that the flow types for the Sketch internals are not correct in at least one respect!

NB: The symbols example is still broken in that the override URL is no longer valid, so it renders to a red rectangle, Sketch's default behaviour for unloadable images.

[Source](https://github.com/airbnb/react-sketchapp/blob/537ced5562ac67f877b53f40167a5f2148664a4a/examples/symbols/src/my-command.js#L64) - Link: [https://pbs.twimg.com/profile_images/833785170285178881/loBb32g3.jpg](https://pbs.twimg.com/profile_images/833785170285178881/loBb32g3.jpg)

I'm not quite sure how to construct a PR for this:

1. What's the correct way of getting the sketchapp-json-flow-types updated (I'll put in an issue asking for a new release), or can we reference the GitHub repo directly as a package dependency?
2. What should be used as a image reference for the replacement?  This seems to be an issue for other examples in that some of the image URL's are no longer valid - should sample images be part of the repo and use the repo URL to reference them?

**Comment by mathieudutour** [comment]
I believe there is a PR for it already: https://github.com/airbnb/react-sketchapp/pull/198

**Comment by dmeehan1968** [comment]
@mathieudutour I just tried Ian's branch, and the symbols example fails as before (changed example to use local lib, built lib etc).

Observed output:

1. Image remains unchanged
2. Red square not replaced by blue square
3. Suspect that blue square text will not change

That PR also seems held up on how to get around the flow error so that it can pass CI.  One option would be to cast the overrides value perhaps - dirty but at least moves it forward.

**Comment by dmeehan1968** [comment]
Hold up, PR branch is missing

**Comment by dmeehan1968** [comment]
Apologies, I thought I'd pulled the branch but only got master.  It is working, and fixes the blue square text override too.
