### ISSUE TITLE
Text symbol overrides get reset to default

### ISSUE THREAD

**Issue by LFra** [airbnb/react-sketchapp#273]
| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

When creating a new symbol containing ```Text```, the sketch instances using this symbol as a library reset the ```Text``` overrides to the default one specified in the library.
I know this is a sketch specific behavior and the norm when deleting and adding symbols with the same name. However I hope to find a solution to this possibly within this library.

**Expected behavior:**
The ```Text``` symbol keeps the text overrides.

**Observed behavior:**
The ```Text``` symbols return their overrides to the ones specified in the code.

**Sketch version:**
48.2

**Comment by mathieudutour** [comment]
I’m not sure I understand, could you provide a code example?

**Comment by LFra** [comment]
I create this symbol in a library file.
```makeSymbol(() => <Text style={{ color: '#f4f4f4' }}> Override </Text>, 'PESDK/Typography/H1')```

Now I use the generated symbol in another sketch document and replace the override of the text to something like "Generic Heading"

When now changing the color of the text in the code to something like #000000 and saving the generated library sketch file, the sketch files using the library recognize the library change and update accordingly. For shapes this works without a problem, however, the ```<Text>``` symbols get their override reset. So the "Generic Heading" gets reset to "Override" (the default override).
This might be a sketch limitation: when deleting a symbol and creating it manually with the same name I get the same behavior.

**Comment by mathieudutour** [comment]
Oh yes I think that's a Sketch bug that we are working on. I'll close this as this is not something actionable here.

**Comment by LFra** [comment]
Sketch 49 supposedly fixes this bug:
>  Fixed a bug where overrides could be lost when copying and pasting Symbol instances

However, this seems to not really be fixed.

**Comment by mathieudutour** [comment]
No that's another bug. I don't think the fix for this issue is merged already.

**Comment by mpatafio** [comment]
Hi @ludwigfrank 

I'm encountering the same issue with Sketch *0.54.1*, do you know if such issue has been solved?

Thanks

Sketch version: 54.1
react-sketch-app version: 3.0.0-beta.3

**Comment by fabdubois** [comment]
Hi @ludwigfrank @mpatafio 
I am encountering a really similar bug with Sketch _61.1_ !
Any news about this?

**Comment by marxiami** [comment]
I'm using Sketch 61.2 and if I copy something like a checkbox with text and change the override text to something else, it reverts to the original text when I close the doc, then open it again. This SUCKS! (But at least it is consistent, it does it all the time!)

**Comment by fabdubois** [comment]
I fixed this by following Sketch Support recommendation: 1/ check if that comes from a plugin by disabling them all upon app launch. To do this hold SHIFT while loading Sketch, which runs it in safe mode. 2/ If problem persists then use the free **AppCleaner** tool to totally uninstall Sketch and clean all related data from your Mac (just drag the Sketch.app icon onto the AppCleaner window). For me 2/ did the job instantly. Contact Sketch Support if needed. @marxiami
