### ISSUE TITLE
Missing strokeAlignment in SVG support

### ISSUE THREAD

**Issue by dcolin** [airbnb/react-sketchapp#276]
I need to set border position in Sketch on a`<Svg.Circle>` but `strokeAlignment` prop is missing in SVG support.

![svg-support-props](https://user-images.githubusercontent.com/2036784/36849479-706236fe-1d64-11e8-86f2-a3cadcfe682a.png)

And by default, border position is set on « center » :

![sketch-border-position](https://user-images.githubusercontent.com/2036784/36849539-a06d8a6a-1d64-11e8-9fae-ea70e212a399.png)

**Comment by mathieudutour** [comment]
does it work when you set it? is it just a matter of adding `strokeAlignment` to the accepted props?
