### ISSUE TITLE
The domain/default pair of (/Users/X/Library/Preferences/com.bohemiancoding.sketch3.plist, AlwaysReloadScript) does not exist

### ISSUE THREAD

**Issue by vjpr** [airbnb/react-sketchapp#285]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

_I am..._

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**

**Observed behavior:**

```
Error while enabling the Sketch developer mode.
{ Error: Command failed: /usr/bin/defaults read ~/Library/Preferences/com.bohemiancoding.sketch3.plist AlwaysReloadScript
2018-03-25 13:04:26.972 defaults[41152:3568695]
The domain/default pair of (/Users/Vaughan/Library/Preferences/com.bohemiancoding.sketch3.plist, AlwaysReloadScript) does not exist
```

**How to reproduce:**

```
cd examples/basic-setup
yarn install
```

**Sketch version:** 49.1

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

**Comment by vjpr** [comment]
**Workaround**

```
defaults write ~/Library/Preferences/com.bohemiancoding.sketch3.plist AlwaysReloadScript -bool YES
```

**Comment by mathieudutour** [comment]
That's an issue with `skpm` that will be fixed in the new version

**Comment by itsaphel** [comment]
@mathieudutour has this been fixed yet? if not, any eta?
