### ISSUE TITLE
SVG circles not rendering as expected

### ISSUE THREAD

**Issue by huy-nguyen** [airbnb/react-sketchapp#288]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

_I am a developer_

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**
[This gist](https://gist.github.com/huy-nguyen/74cf0f9fe2d0956503c96760ec5b46d3) should show 2 equally sized circles of radius 50:
- A red circle at x = 100, y = 100.
- A blue circle at x = 100, y = 200.

**Observed behavior:**

Actually show two ellipses:

![Wrong output](https://i.stack.imgur.com/chdvS.png)

**How to reproduce:**
- `yarn`
- `yarn run render`

**Sketch version:** 47.1

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

[Link to sketch file](https://drive.google.com/file/d/1q_XSnHQTCUb6Xlk1-utbcLuZQyYu6VYy/view?usp=sharing)

[Stackoverflow question](https://stackoverflow.com/questions/49406995/svg-not-rendering-as-expected-in-react-sketchapp)

**Comment by mathieudutour** [comment]
Thanks for the nice bug report, I'll try to look at it when I have a bit of time

**Comment by mathieudutour** [comment]
Forgot about this. 

But the gist is that Sketch doesn't support SVG (or shapes) that don't "expand" to all sides (eg. in your example, your shape fits in 100x200). So it will render the shape in a rectangle that fits the shape and then scale that rectangle to fit the size of the parent SVG (500x500 in your example).
