### ISSUE TITLE
  textTransform: "uppercase" breaks last word in a sentence

### ISSUE THREAD

**Issue by sogen** [airbnb/react-sketchapp#298]
_I am..._

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**
Sentence appears in one line

**Observed behavior:**
Last word in a sentence appears in a new line.

**How to reproduce:**
Use the Styleguide example
add `textTransform: "uppercase"`
to one of the type examples inside designSystem.js

Example:
```

  'I am error': {
    color: colors.Night,
    fontSize: typeSizes[2],
    fontFamily: fontFamilies.display,
    fontWeight: fontWeights.bold,
    lineHeight: 36,
    textTransform: "uppercase",

```

**Sketch version:**
49.2

**Please attach screenshots, a zip file of your project, and/or a link to your github project**
![screen shot 2018-04-21 at 11 00 26 pm](https://user-images.githubusercontent.com/2784323/39092027-d0bd6e9e-45b7-11e8-8f5c-9d3e4af04e2a.png)

**Comment by mathieudutour** [comment]
I'm not able to reproduce. Feel free to reopen if you have a sample project that can be tested
