### ISSUE TITLE
skpm version support

### ISSUE THREAD

**Issue by Waltari10** [airbnb/react-sketchapp#303]
I noticed that all the example projects are using @skpm/builder version "^0.2.0", even though the latest one is 0.5.4. Is this plugin supposed to work with the latest version? When I try to use 0.2.0 I get an error when trying to require images (see [this issue](https://github.com/airbnb/react-sketchapp/issues/216)), and when I try to use the latest @skpm/builder I get this another error:
`Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/myName/myCompany-app/node_modules/babel-preset-react-native/index.js`

Is React-Sketchapp supposed to work on the latest skpm/builder version also? Which version do you recommend?

My manifest is: 

```
{
	"compatibleVersion": 3,
	"bundleVersion": 1,
	"commands": [
		{
			"name": "react-sketchapp: Basic Setup",
			"identifier": "main",
			"script": "./my-command.js"
		}
	],
	"menu": {
		"isRoot": true,
		"items": [
			"main"
		]
	}
}
```

And my script:
```
import React from 'react'
import {
  render,
  Text,
  Artboard,
  View,
  Image,
  StyleSheet,
} from 'react-sketchapp'

const constants = {
  colors: {},
  helpers: {},
}

const icons = {
  heart: {
    active: require('./heart-active@3x.png'),
    inactive: require('./heart-inactive@3x.png'),
  },
}

const Document = () => (
  <Artboard
    name="HeartButton"
    style={{
      width: 375,
      height: 637,
    }}
  >
    <ButtonHeart
      count={5}
    />
  </Artboard>
)

export default (context) => {
  render(<Document />, context.document.currentPage())
}

function ButtonHeart (props) {
  return (
    <View
      disabled={props.disabled}
      style={styles.touchableArea}
      onPress={props.onPress}
      activeOpacity={constants.helpers.touchableOpacity}
    >
      <View style={[
        styles.button,
        props.isActive ? styles.buttonActive : null,
      ]}
      >
        <Image source={icons['heart'][props.isActive ? 'active' : 'inactive']} style={styles.icon} />
        {props.count ? (
          <Text style={[
            styles.number,
            props.isActive ? styles.numberActive : null,
          ]}
          >
            {props.count}
          </Text>
        ) : null}
      </View>
    </View>
  )
}

const styles = StyleSheet.create({
  touchableArea: {
    paddingBottom: 5,
  },

  button: {
    borderWidth: 1,
    borderRadius: 25,
    borderColor: constants.colors.secondary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 5,
    paddingBottom: 5,
    minHeight: 30,
    minWidth: 30,
  },

  buttonActive: {
    borderColor: constants.colors.negativeHighlight,
  },

  icon: {
    width: 17,
    height: 15,
    marginTop: 1,
  },

  number: {
    // ...getFont('bold', 13),
    marginLeft: 3,
    color: constants.colors.secondary,
  },

  numberActive: {
    color: constants.colors.negativeHighlight,
  },
})
```

Package.json: 

  "skpm": {
    "main": "basic-setup.sketchplugin",
    "manifest": "src/reactSketch/manifest.json"
  },

scripts:  
    "build": "skpm-build",
    "watch": "skpm-build --watch",
    "postinstall": "npm run build && skpm-link",
    "render-sketch": "skpm-build --watch --run",
    "render-sketch:once": "skpm-build --run"

versions:
    "@skpm/builder": "^0.2.0",
    "react-sketchapp": "^1.1.0",

**Comment by mathieudutour** [comment]
It should work yes

**Comment by nixvalentine** [comment]
@Waltari10 I'm sorry but does using the latest version of skpm fix the image locally imported error? If so, could you please share how you update your skpm to the newer version?
