### ISSUE TITLE
Discuss ideas for sustainable project maintenance

### ISSUE THREAD

**Issue by jaridmargolin** [airbnb/react-sketchapp#305]
[EDITED]

In an attempt to keep `react-sketchapp` moving forward, it believe it would be beneficial to discuss various solutions for maintaining this project in a more sustainable way.

The two main concerns I see are:
1. There are a couple PRs blocked by issues filed on direct dependencies that appear to no longer be maintained.
2. PRs currently require at least 1 approving review by reviewers with write access. At the moment @mathieudutour is the only maintainer working on this project and as a result cannot merge anything he authors.

---

In an attempt to solve point 1, I wanted to propose the idea of moving to a new organization which also manages these direct dependencies.

Specifically, the organization would manage this repo as well forks of (or if @darknoon is willing to transfer ownership):
* [sketchapp-json-flow-types](https://github.com/darknoon/sketchapp-json-flow-types)
* [sketchapp-json-plugin](https://github.com/darknoon/sketchapp-json-plugin)

... Perhaps this is all overkill (and perhaps I am overstepping), but it was the most organized and maintainable approach I could devise. Open to any other suggestions.

**Comment by ljharb** [comment]
It seems like a first step would be the owner of those repos granting GitHub and npm access to the maintainers of react-sketchapp; moving this repo to an org is extremely premature.

**Comment by jaridmargolin** [comment]
@ljharb - Two counters (and that doesn't mean this isn't still premature)

1. @darknoon has yet to respond to an issue to publish a new version of `sketchapp-json-flow-types` that was filed on Feb 21st. Perhaps Github is not the correct means to communicate with him. We could try to contact via email, or perhaps someone knows him personally and could reach out.
2. It would require keeping grant access in line with current maintainers of `react-sketchapp`. Perhaps this list isn't volatile and it wouldn't be a major concern, but each time the issue did arise, it would be unnecessary friction.

Besides being "extremely premature", what would be the potential downsides of setting up as an organization?

Thanks for your prompt response, the awesome project, and working through this issue with me :)

**Comment by jaridmargolin** [comment]
@ljharb All good points. I am altering the title of this issue to better reflect the intent, which is to open discussion on the best ways to continue maintenance on this project.

@mathieudutour - I'd be happy to help review and submit PRs where I can. I do want to note however, that my exposure has been fairly short. The insight and help I can bring would be quite different that of the original authors who have in-depth knowledge of trade-offs and early design decisions... If airbnb wants to ensure this project is moving in their desired direction, they really need to have a representative(s) who is available to take ownership.

If airbnb does not have the time to maintain the future of this project, I do think it would be beneficial to have myself added as a maintainer so I can provide a second set of eyes for @mathieudutour. This would at least give us a path forward to getting required PRs merged.

**Comment by ljharb** [comment]
I’ll consult with @jongold in person today about next steps.

**Comment by ljharb** [comment]
Yes, I can now help maintain permissions on both npm and GitHub.

I agree that if there's one maintainer, it doesn't make sense to require approvals, but it'd be ideal to have 2+ maintainers so that things can still get proper review :-)

@mathieudutour can you ping me directly on any PRs you're blocked on, and I can try to take a look?

**Comment by jaridmargolin** [comment]
@jongold @ljharb thank you taking the time to look into this. It really is greatly appreciated  🙏

@mathieudutour - as for the `sketchapp-*` libraries managed by @darknoon... I have attempted to contact him via email and twitter in order to discuss next steps. I will forward on any information I receive but wondering if we should set a deadline for his response. If by _______ we don't hear back, you can move forward with forking the library and maintaining it over at skpm.

**Comment by mathieudutour** [comment]
Alright let's close this and see how it goes

**Comment by mathieudutour** [comment]
I thought that I had the rights to publish an update but I don't (anymore?)

> ❯ npm owner ls react-sketchapp
> ljharb <ljharb@gmail.com>
> airbnb <jordan.harband+npm@airbnb.com>
> jongold <hello@designedbygold.com>

@ljharb @jongold can either of you add me?

**Comment by ljharb** [comment]
I’ll take care of it later today.

**Comment by ljharb** [comment]
@mathieudutour what's your npm username?

**Comment by mathieudutour** [comment]
Same as GitHub: mathieudutour

**Comment by mathieudutour** [comment]
Ok, it doesn't seem to work.

- Can we remove the review required before merging?

**Comment by mathieudutour** [comment]
The process we have now where we require a review before being able to merge

**Comment by ljharb** [comment]
In what way doesn’t it work?

**Comment by mathieudutour** [comment]
I'm the only one working on the project at the moment. @jaridmargolin helped for a while but I can't expect him and other to commit more than they want to.

I'd love to publish the fixes I've made but I can't so I'm ending up using my fork where I'm not restricted  and published it under my own scope on npm :/

**Comment by ljharb** [comment]
That seems extreme and unnecessary. I’ll remove the requirement for now, but let’s try to find a second maintainer so we can restore it.

**Comment by jaridmargolin** [comment]
I don't have "consistent" bandwidth for continual reviews. My availability usually comes in chunks of time in between product sprints.

@mathieudutour - If you want to tag/assign me on PRs you deem important, I'll do my best to review in a timely manner. And worst case scenario, @ljharb has lifted restrictions, so you will be able to move forward if I don't have time.

**Comment by mathieudutour** [comment]
Yeah no worry, I understand perfectly, it's pretty much the same for me. 
I just want to be able to merge quick fixes while I have some time without waiting for a review that might push it out of my "free timeslot"
