### ISSUE TITLE
Build & Deploy to hosting site

### ISSUE THREAD

**Issue by LincMitch** [airbnb/react-sketchapp#309]
I'm trying to work out how to use something like Netlify to host a simple react-primitive example that renders to web. Currently, I can only render to a localhost with the following code:

package.json
..
`"web": "react run src/web.js"`
...

CLI:
**`run render web`** 
...
**`The app is running at http://localhost:3000/`**

As the `"build": "skpm-build",` in the package.json file is for the sketch plugin. I believe I need another script that creates a **build folder** which would contain a **`index.html**` file.

Any pointers?

**Comment by mathieudutour** [comment]
have a look at the docs of nwb: https://github.com/insin/nwb
