### ISSUE TITLE
Multi-Artboard on Master and V2.0.0 Branch

### ISSUE THREAD

**Issue by thierryc** [airbnb/react-sketchapp#318]
| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue on master and V2.0.0
| -------------------------------------------------------------------------------------------------

I upstream your V2.0.0 and I create an example to test a multi-page multi-artboard document. 

**Expected behavior:**

I expect to get 2 page and 2 artboard into each page. 

**Observed behavior:**

But I get only 2 pages (perfect) and 1 artboard into each page. 

**How to reproduce:**

Multipage Multiartboard Setup
https://github.com/thierryc/react-sketchapp/tree/version2.0.0/examples/multipage-multiartboard-setup

I have made a mistake ?

```XML
<Document>
  <Page>
     <Artboard>
         <foo>KO</foo>
     </Artboard>
     <Artboard>
         <bar>OK</bar >
     </Artboard>
  </Page>
  <Page>
     <Artboard>
         <foo>KO</foo>
     </Artboard>
     <Artboard>
         <bar>OK</bar >
     </Artboard>
  </Page>
</Document>
```

This branch work as expected. 

https://github.com/thierryc/react-sketchapp/tree/workingversion-50

https://github.com/thierryc/react-sketchapp/tree/workingversion-50/examples/multipage-multiartboard-setup

**Sketch version:**

49 and 50

**Comment by jaridmargolin** [comment]
This is definitely a bug and I will investigate:

Oddly enough this works:
```
<Document>
  <Page>
     <Artboard style={{ width: 10, height: 10 }} name='1' />
     <Artboard style={{ width: 10, height: 10 }} name='2' />
  </Page>
  <Page>
     <Artboard style={{ width: 10, height: 10 }} name='1' />
     <Artboard style={{ width: 10, height: 10 }} name='2' />
  </Page>
</Document>
```

For some reasons it fails when defining children within the `Artboard`

---

cc @mathieudutour
