### ISSUE TITLE
Color Property is not working on text in Sketch 50

### ISSUE THREAD

**Issue by davidmfry** [airbnb/react-sketchapp#323]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

_I am..._

| -------------------------------------------------------------------------------------------------
| Requesting a new feature
| -------------------------------------------------------------------------------------------------

**Proposal/Feature-request:**

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**
I expect if you change the <Text style={{color: '#FFF'}} then the text should render as white.
![screen shot 2018-05-10 at 4 28 58 pm](https://user-images.githubusercontent.com/4297169/39899295-f0728bd6-546f-11e8-920b-ee10663f9601.png)

**Observed behavior:**
The color on the <Text style={{color: '#FFF'}}> is not changing to the given color.  The text color remains black no matter what you change it to.

**How to reproduce:**
Run the example code for the basic setup.

**Sketch version:**
Sketch version 50

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

**Comment by mathieudutour** [comment]
What version of react-sketchapp are you using?

**Comment by sambrannon** [comment]
Having the same issue with react-sketckapp `v1.1.0` and Sketch `v50`

**Comment by mathieudutour** [comment]
Try with v2.0.0

**Comment by sambrannon** [comment]
That fixed it, thanks @mathieudutour!
