### ISSUE TITLE
Why is the symbols implementation tied to mastersNameRegistry?

### ISSUE THREAD

**Issue by jaridmargolin** [airbnb/react-sketchapp#327]
I've been searching the codebase and reviewing the symbols implementation, and I keep coming to the conclusion that I must be missing something obvious. I am trying to determine why exactly the `mastersNameRegistry` exists and why it acts as the backbone of the symbols implementation.

Every symbol has a `symbolID`. It seems as if we could remove a ton of cruft and unnecessary `find` operations, if we instead had a `symbolsRegistry` which was keyed by the `symbolID` rather than the `masterName`.

**Comment by mathieudutour** [comment]
I don't think there is any reason except that the exposed API to get an existing symbol is to query it by its name.
