### ISSUE TITLE
Is flow currently beneficial to this project?

### ISSUE THREAD

**Issue by jaridmargolin** [airbnb/react-sketchapp#330]
My exposure to flow is still fairly new (this project being the only exposure I have). As I was attempting to wire up my IDE, I realized that not all of the files within the `react-sketchapp` utilize flow.

I attempted to add the flow flag to the top of `types.js` and was greeted with 146 errors. Coupled with the fact that recent updates have mostly skirted around flow by repeatedly using the `any` type, I wonder how much use we are actually getting out of flow.

Broad question,  is flow beneficial to us as it is currently being used, or is it a burden?

cc @ljharb @mathieudutour

**Comment by jaridmargolin** [comment]
Sounds good @ljharb. I'll create a new issue to clean up the flow types. From my initial investigation, it looked like it may be substantial work to get everything back in a good place. I'm a little skeptical that anyone will want to put in the time, but hopefully I will be surprised 😊

Thanks for your input.

Do you think this issue should stay open and revisited if we don't see any movement on cleaning up the flow types, or shall I close it now?

**Comment by ljharb** [comment]
I think it's worth keeping it open

**Comment by Keraito** [comment]
Hey @jaridmargolin, although I don't have experience with Flow, I would definitely be willing to learn about it and help out in this matter if you're still looking for help. Would need a bit of guidance on where to start and stuff though as I'm completely new to this particular project. Is there an issue or something where I can see the current progress?

**Comment by jaridmargolin** [comment]
@Keraito all help is greatly appreciated. I created the issue #341 to track progress. As far as getting started, the [flow documentation](https://flow.org/en/docs/) does a pretty good job introducing the core concepts.

**Comment by Keraito** [comment]
Thanks! Will read up on all the stuff and try to help asap!
