### ISSUE TITLE
Can't run example react-sketchapp on macOS High Sierra 10.13.5

### ISSUE THREAD

**Issue by Noviato** [airbnb/react-sketchapp#347]
Hi, I am Alex
| Reporting a bug or issue
I can't run example basic-setup of the react-sketchapp. When I run npm install, I have an error. Can you help me fix this? Many thanks

**Sketch version:*50.2*
<img width="859" alt="screen shot 2018-05-31 at 09 47 00" src="https://user-images.githubusercontent.com/9394079/40758750-0c3d5978-64b9-11e8-9a3b-1112714e2168.png">

**Comment by mathieudutour** [comment]
It's either an issue with your installation (maybe try to update npm or nodejs) or with yoga-layout but it's not something we can solve here
