### ISSUE TITLE
Support for Touch Actions (Component API for Touchable)

### ISSUE THREAD

**Issue by trevorwhealy** [airbnb/react-sketchapp#349]
**Proposal/Feature-request:**
```
<Touchable
   style={{ backgroundColor: "purple", width: 20, height: 20 }}
   onPress={() => {}}
/>
```

**Expected behavior:**
In Sketch's new `Preview` mode, I was hoping to interact with the certain button behaviors.

**Observed behavior:**
There is no touch support.
Neither `react-native-web` nor `react-primitives` is a supported replacement.

**Sketch version:**
50.2

Thanks to Airbnb and team for an exciting utility.

**Comment by mathieudutour** [comment]
there has been some discussion here: #280 and #343 so I'll close this in favor of the others (and `onPress` is unlikely to be supported since the only possible action would be to go to another artboard so the semantic doesn't work)

**Comment by trevorwhealy** [comment]
@mathieudutour thanks for the quick reply. I think there are styling/animation changes that can also follow an onPress action.

**Comment by mathieudutour** [comment]
prototyping on sketch only supports going to another artboard (with a set of specific animation), you can't change the style or the animation when clicking
