### ISSUE TITLE
Setting Text style.color does not work on 1.1.0

### ISSUE THREAD

**Issue by thecalvinchan** [airbnb/react-sketchapp#354]
| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**

Setting the `color` property inside `<Text>` style should change the color of the text

**Observed behavior:**

Text color remains `#000`

**How to reproduce:**

Run `examples/basic-example` and the color names and hex should be in black. 

This only happens on `react-sketchapp@1.1.0` on Sketch@>=50. This is not an issue on Sketch @<=49.

Furthermore, this is not an issue on Sketch@>=50 with `react-sketchapp@2.x.x`

**Sketch version:**

50.2

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

```
    <Text name="Swatch Name" style={{ color: textColor(hex), fontWeight: 'bold' }}>
      {name}
    </Text>
    <Text name="Swatch Hex" style={{ color: textColor(hex) }}>
      {hex}
    </Text>
```

**Comment by jaridmargolin** [comment]
@thecalvinchan - I would recommend using 2.x releases as it is unlikely that we will backport changes to 1.x release.

**Comment by thecalvinchan** [comment]
@jaridmargolin gotcha, thanks. how often are changes published on npm/yarn? I'm trying to get the latest patch for symbols, what would be the best way to stay up-to-date with latest changes?

**Comment by LincMitch** [comment]
And how do you even install 2.0 via npm, Mentioned in #355

**Comment by mathieudutour** [comment]
`npm install react-sketchapp@2`
