### ISSUE TITLE
Create 2.0.0 release

### ISSUE THREAD

**Issue by jaridmargolin** [airbnb/react-sketchapp#355]
While we have released 2.0.0 via npm, we have not created a 2.0.0 Github Release.

**Comment by LincMitch** [comment]
I tried `npm i react-sketchapp` but got the no such file warning for `package.json`.
Was keen to see what's new in release 2.0 but do I have to use the previous version via git hub for now?

**Comment by jaridmargolin** [comment]
Looking at `npm info react-sketchapp`, the latest version appears to be `2.0.0`, so I would imagine it should install latest by default 🤔

`npm install react-sketchapp@2` should work as well.

**Comment by mathieudutour** [comment]
done
