### ISSUE TITLE
Sketch opens blank document

### ISSUE THREAD

**Issue by dariusgarza** [airbnb/react-sketchapp#36]
**Reporting a bug or issue**
running npm run render just opens a blank sketch document. 
Is there something else I need to be doing? I followed the steps in getting started to no avail. 

**Expected behavior:**
For a demo sketch file to open that's not blank. 

**Observed behavior:**
sketch file is blank.

**How to reproduce:**
npm run render

**Sketch version:**
43.2

**Comment by dariusgarza** [comment]
Got it to work by cloning to desktop and running from there...but why?  ¯\_(ツ)_/¯

**Comment by jongold** [comment]
weird - hard to tell without seeing your logs from Console.app :(

I wonder if this was related?
