### ISSUE TITLE
form-validation and ReactComponentTreeHook

### ISSUE THREAD

**Issue by LincMitch** [airbnb/react-sketchapp#361]
I was getting a ERR **Can't resolve 'react/lib/ReactComponentTreeHook' eact/lib/ReactComponentTreeHook'**
Found answer at:
https://stackoverflow.com/questions/40911760/jest-fails-with-error-cannot-find-module-react-lib-reactcomponenttreehook

No error but still doesnt render.

**Comment by LincMitch** [comment]
Also, I am having the same issue with the **Foursquare** example.

**Comment by derek-smith** [comment]
I'm having the exact same problems...

**Comment by mathieudutour** [comment]
what's the stack trace? I'm guessing you need to update the version of react-primitives

**Comment by scottoasis** [comment]
Updating `react-primitives` package to `0.6.0` solved my problem.
