### ISSUE TITLE
Vertical Text Alignment

### ISSUE THREAD

**Issue by miketamis** [airbnb/react-sketchapp#366]
Currently I can't figure out how to set the vertical text alignment (screenshot attached).

<img width="215" alt="screen shot 2018-07-03 at 2 48 18 pm" src="https://user-images.githubusercontent.com/1079931/42196151-7f4a7c12-7ed0-11e8-97bd-14256582dc40.png">

I feel like this should be done using: https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

left to right for the red box (screenshot):
* verticalAlign: top
* verticalAlign: middle
* verticalAlign: bottom

**Comment by thecalvinchan** [comment]
you can probably achieve this by wrapping your text in a `View` with `flexDirection: row` and `alignItems: center`

vertical alignment for Text primitives aren't supported (in most non-web rendering targets):
- http://airbnb.io/react-sketchapp/docs/styling.html#type-styles
- https://facebook.github.io/react-native/docs/text-style-props
