### ISSUE TITLE
3.0.0beta.0 release seems to break paragraph spacing support

### ISSUE THREAD

**Issue by lessthanzero** [airbnb/react-sketchapp#389]
Tested out v3.0.0beta.0 and it seems that `paragraphSpacing` being properly parsed (logged `hacksforJSONImpl.js` file) doesn't end up in generated .sketch file, thus not being displayed correctly at all.

**Comment by mathieudutour** [comment]
when generating a sketch file with node or running it as a plugin?

**Comment by lessthanzero** [comment]
@mathieudutour when running as a plugin

**Comment by lessthanzero** [comment]
Indeed it is
