### ISSUE TITLE
styled-components integration?

### ISSUE THREAD

**Issue by therealedsheenan** [airbnb/react-sketchapp#39]
It would be nice to have a styled-component integration...
Any ideas?

**Comment by jongold** [comment]
Agreed. I discussed it a little here — https://github.com/airbnb/react-sketchapp/issues/29#issuecomment-297435389

tldr: it should be possible to use with `styled-components/native` but it might require a little bit of webpack config, or a modification to styled-components.

**Comment by mathieudutour** [comment]
I tried that on #117
