### ISSUE TITLE
Sketch 52  TypeError: MSSharedStyle.alloc().initWithName_firstInstance is not a function

### ISSUE THREAD

**Issue by thierryc** [airbnb/react-sketchapp#396]
I am reporting a bug or issue

**Expected behavior:**

Generate a styleguide with Shared text style.
https://github.com/airbnb/react-sketchapp/tree/master/examples/styleguide

**Observed behavior:**

Get an error in the log file "Plugin Log.log"

TypeError: MSSharedStyle.alloc().initWithName_firstInstance is not a function. (In 'MSSharedStyle.alloc().initWithName_firstInstance(name, textStyle)', 'MSSharedStyle.alloc().initWithName_firstInstance' is undefined)
line: 35619

**How to reproduce:**

Install and run the styleguide examples
https://github.com/airbnb/react-sketchapp/tree/master/examples/styleguide

**Sketch version:**

Sketch 52
OSX 10.13.6 (17G2307) 

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

**Comment by bomberstudios** [comment]
Sorry about the breakage, that method has been replaced by `MSSharedStyle.alloc().initWithName_style`

Hope it helps!

**Comment by thierryc** [comment]
support SharedStyles in Sketch 52 #397 

Works for me. I tested it. Thank you Mathieu

**Comment by thierryc** [comment]
May I should close the issue ?

**Comment by mathieudutour** [comment]
It will be close automatically when I merge the PR. Not in front of a computer atm so I’ll do it a bit later
