### ISSUE TITLE
TypeError: null is not an object

### ISSUE THREAD

**Issue by wzulfikar** [airbnb/react-sketchapp#40]
Noob here 🙏

Is it expected that the react-sketchapp can only run when there's a sketch document open?

**Expected behavior:**
- Running `npm run render` should automatically open sketch app if it's not open yet and render the code

**Observed behavior:**
- If the sketch app is not opened, there will be error `TypeError: null is not an object (evaluating 'context.document.currentPage')`.

**How to reproduce:**
- Running `npm run render` when there's no sketch document opened (or sketch app is closed)

**Sketch version:**
- 43.2

![screen shot 2017-04-27 at 9 29 51 am](https://cloud.githubusercontent.com/assets/7823011/25463938/3e98197a-2b2c-11e7-8d9f-b0c1d0ce28c2.jpg)

**Comment by jongold** [comment]
Yeah, it can only render when Sketch is open. see #23 for more discussion about smarter ways we could handle render, but it might be a hard limitation of how we're using `sketchtool` right now

**Comment by wzulfikar** [comment]
Noted. Thanks for quick reply!
