### ISSUE TITLE
Symbol overrides don't work

### ISSUE THREAD

**Issue by lessthanzero** [airbnb/react-sketchapp#409]
I am trying to use standard override example with the most recent `react-sketchapp` version and symbol overrides don't work, returning no errors and just a master symbol instance with default sub-symbol.

**Sketch version:**
52.6

**Comment by lessthanzero** [comment]
@mathieudutour any news?

**Comment by mathieudutour** [comment]
haven't had time to look into it no

**Comment by lessthanzero** [comment]
Kinda found the solution with #412
