### ISSUE TITLE
TypeError: null is not an object (evaluating 'context.document.currentPage')

### ISSUE THREAD

**Issue by xinyu198736** [airbnb/react-sketchapp#41]
i run `npm install` ,and then run `npm run render`,but throw this error 

npm 4.5.0
node 7.8.0
sketch 0.43.2

```
npm run render

> profile-cards@ render /Users/yutou/code/react-sketchapp/examples/profile-cards
> skpm build --watch --run

🖨  Copied src/manifest.json in 9ms
Executing post-build scripts
🔩  Built ./main.js in 1451ms
TypeError: null is not an object (evaluating 'context.document.currentPage')
line: 6740
column: 104
```

**Comment by xinyu198736** [comment]
first open a document!!!

**Comment by jongold** [comment]
This is such a common bug, really sorry we didn't make it clear enough

**Comment by nikolasleblanc** [comment]
Haha, yeah, this just happened to me too. Maybe an error message saying, "Did you open a document dummy?" :)

**Comment by robksawyer** [comment]
Or to be completely clear, maybe... "Hey dummy! Did you open a new document in Sketch?"

**Comment by Bruce-zxy** [comment]
It's funny.
