### ISSUE TITLE
Create children text styles

### ISSUE THREAD

**Issue by luisjmontoro** [airbnb/react-sketchapp#410]
Hello!! Thanks for this amazing tool!

I am trying to nest different text styles to have, for example, different alignments under the same style.

```
Body: {
      fontSize: 16,
      fontFamily: fontFamilies.fontFamily1,
      fontWeight: fontWeights.bold,
      lineHeight: 22,
      color: '#ccc',
        center: {
          textAlign: 'center',
        },
        right: {
          textAlign: 'right',
        },
      },
```
We are planning to create our text styles libraries with the plugin and we need to have different children for alignment, colors and weights under the same parent. Is this possible in any way?

Thank you so much!!

**Comment by mathieudutour** [comment]
you can do something like this:
```js
const style = {
  Body: {
      fontSize: 16,
      fontFamily: fontFamilies.fontFamily1,
      fontWeight: fontWeights.bold,
      lineHeight: 22,
      color: '#ccc',
    },
}
style.center = {
  ...style.Body,
  textAlign: 'center',
}
style. right = {
  ...style.Body,
  textAlign: 'right',
}
```

**Comment by luisjmontoro** [comment]
Hello @mathieudutour, thanks for the quick response!

I did some tests with your approach but it wasn't working. I figured out it was because of not using typeStyles, so I changed it to look something like this:

```js
const typeStyles = {
    Display1:  {
      fontSize: 72,
      fontFamily: fontFamilies.fontFamily1,
      lineHeight: 82,
      },
    }
    typeStyles.left = {
      ...typeStyles.Display1,
      textAlign: 'left',
    }
    typeStyles.center = {
      ...typeStyles.Display1,
      textAlign: 'center',
    }
    typeStyles.right = {
      ...typeStyles.Display1,
      textAlign: 'right',
    }
```
And it works but it does not nest the text styles in Sketch... It generates all of them in the root level.

We need to have them like:
-Display1 / left
                 / center
                 / right

Thank you!!

**Comment by mathieudutour** [comment]
then you need to gives them proper names: `typeStyles['Display1 / left']`, etc.
