### ISSUE TITLE
TypeError: null is not an object (evaluating 'decoded.class')

### ISSUE THREAD

**Issue by boraoren** [airbnb/react-sketchapp#415]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

_I am..._ developer

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**
Running

**Observed behavior:**
Not Running, console message is **TypeError: null is not an object (evaluating 'decoded.class')**

**Sketch version:**
53 (72520)

**Please attach screenshots, a zip file of your project, and/or a link to your github project**
![image](https://user-images.githubusercontent.com/45959515/52993243-a5d53500-3467-11e9-83f9-00235c239445.png)

**Comment by mathieudutour** [comment]
- what version of react-sketchapp are you using?
- do you have a code example to reproduce?

**Comment by boraoren** [comment]
* what version of react-sketchapp are you using? 
"react-sketchapp": "^2.0.0", (as basic setup)

* do you have a code example to reproduce?
I try to run basic-setup

**Comment by itelo** [comment]
Hi @boraoren, I was with the same problem, just updating the version of Sketch to the latest fixed my issue.

**Comment by kaypon** [comment]
> Hi @boraoren, I was with the same problem, just updating the version of Sketch to the latest fixed my issue.

Confirmed, had the same issue, update to 53.2v of Sketch worked for me.
