### ISSUE TITLE
Failing at the basic-setup

### ISSUE THREAD

**Issue by radhigulati** [airbnb/react-sketchapp#42]
_I am..._

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------
When I run `npm run render` I receive a syntax error:
`SyntaxError: Use of const in strict mode.`

<img width="921" alt="screen shot 2017-04-26 at 9 08 22 pm" src="https://cloud.githubusercontent.com/assets/551170/25467674/d0ddf358-2ac4-11e7-8877-46da6432c386.png">

**Comment by jongold** [comment]
Looks like you're using an old version of node :(

Can you try installing a newer version? If you're using [nvm](https://github.com/creationix/nvm#long-term-support) this should work
```
nvm install --lts
```

**Comment by radhigulati** [comment]
Hmm when I do that I see a new error. Attached the ss below
<img width="858" alt="screen shot 2017-04-26 at 9 22 16 pm" src="https://cloud.githubusercontent.com/assets/551170/25467899/7a8c1654-2ac6-11e7-8cb6-7d938058b664.png">

**Comment by ljharb** [comment]
After switching node versions, you may need to run `npm rebuild`.

**Comment by radhigulati** [comment]
That doesn't seem to do it, I get the same error sadly :'(

**Comment by jongold** [comment]
ok so now it looks like you're getting another error - looks like skpm can't find Sketch :)

Where is your Sketch application stored? See #38 - I think it's the same error 🤔

**Comment by radhigulati** [comment]
It worked! Thanks so much for directing me to the correct areas :)

**Comment by jongold** [comment]
🙌 sorry for the hiccups!
