### ISSUE TITLE
Exporting `Svg` components to align with react-native-svg

### ISSUE THREAD

**Issue by saschazar21** [airbnb/react-sketchapp#420]
_I am..._

| -------------------------------------------------------------------------------------------------
| Requesting a new feature
| -------------------------------------------------------------------------------------------------

**Proposal/Feature-request:**

To provide a seamless integration possibility between `react-sketchapp` and `react-native-svg`, it should be possible to use the same export structure for `Svg` components as `react-native-svg` does (e.g. to support `@svgr/core`'s native parsing possibilities).

**Current situation:**

```jsx
import { Svg } from 'react-sketchapp';

export const CircleIcon = (props) => (
  <Svg viewBox="0 0 24 24" {...props}>
    <Svg.Circle cx={12} cy={12} r={1} />
  </Svg>
);
```

**`react-native-svg` approach:**

```jsx
import { Svg, Circle } from 'react-sketchapp';

export const CircleIcon = (props) => (
  <Svg viewBox="0 0 24 24" {...props}>
    <Circle cx={12} cy={12} r={1} />
  </Svg>
);
```

**Comment by mathieudutour** [comment]
The difference is that `react-native-svg` is namespaced. You wouldn't expect `Circle` to be exported on `react-native` but `Svg` might make sense.

You can easily do 
```
import { Svg } from 'react-sketchapp';
const { Circle } = Svg;
```
tho

**Comment by saschazar21** [comment]
Yes I'm completely with you on this one.

If I may suggest a different solution: why not exporting the `Svg` members in the `lib/components/Svg/index.ts` file? Therefore the namespace still makes sense and it would be possible to export each member without the need of a destructuring operation of the imported `Svg` class.

The issue I see with the destructuring option you mentioned above, is that it prevents tree-shaking and as well auto-fixing imports by `tslint`.

I might as well supply a PR for further consideration, if that's okay for you. Otherwise I'm also okay with closing this issue.

**Comment by mathieudutour** [comment]
Happy to look at a PR yes
