### ISSUE TITLE
Symbols instances override issues

### ISSUE THREAD

**Issue by mpatafio** [airbnb/react-sketchapp#424]
_Hello guys!!_

| -------------------------------------------------------------------------------------------------
| Requesting support
| -------------------------------------------------------------------------------------------------
I managed to create a set of Symbols using `makeSymbol` method. My goal is to share such symbols across Pages but I'm encountering several issues or probably I'm missing something in what to expect:
1) On each symbol instance, values override doesn't persist across changes made on the React Component even if I use the same name to make the symbol.
2) Is expected, on each symbol instance to render accordingly to the values I'm overriding? E.g. a View containing a text value (override) that goes on multiple lines, should resize accordingly in the specific symbol instance? If such view contains dynamic content should it react accordingly to the fact I'm overriding values on its symbol instance?

Thanks

**Sketch version:** 54.1
**react-sketch-app version:** 3.0.0-beta.3

**Comment by mpatafio** [comment]
up!^

**Comment by mathieudutour** [comment]
Can you provide a code example? I'm struggling to visualise

**Comment by mpatafio** [comment]
@mathieudutour Thank you for the response !

below all the details 

this is the code of the Component

`export interface MessageBannerProps {
  title: string;
  subtitle?: string;
}

export class MessageBanner extends React.Component<MessageBannerProps> {
  render() {
    const { title, subtitle } = this.props;
    return (
      <View style={styles.container}>
        <Text style={styles.title}>{title}</Text>
        {subtitle && <Text style={styles.subtitle}>{subtitle}</Text>}
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    borderRadius: AppDimensions.spacing5x,
    backgroundColor: Colors.cyanBlue,
    flexDirection: 'column',
    width: 200,
    alignItems: 'center',
  },
  title: {
    color: Colors.grayDarker,
    fontSize: 12,
    margin: AppDimensions.spacing2x,
  },
  subtitle: {
    color: Colors.grayDarker,
    fontSize: 12,
    marginBottom: AppDimensions.spacing2x,
  },
});`

this is the symbol I'm making (it is not rendered in a particular page, but it's inside the Symbols page)

`const messageBanner = () => <MessageBanner title={'Banner title'} subtitle={'Banner subtitle'} />;
makeSymbol(messageBanner, 'banners/message');
`

and that's how it looks like in the Symbols page

<img width="263" alt="Screenshot 2019-05-10 at 09 30 04" src="https://user-images.githubusercontent.com/6072188/57510415-08233080-7307-11e9-9889-3bed476ac476.png">

if, in a such symbol instance on a new Page, I override values like this

<img width="628" alt="Screenshot 2019-05-10 at 09 32 20" src="https://user-images.githubusercontent.com/6072188/57510437-1a04d380-7307-11e9-811b-e637b7b79077.png">

and I change anything in the Component code, even just a style, making the symbol with the same name "'banners/message'", when the Symbol instance is re-rendered inside the Page the overridden values are present in the Inspector view but are not correctly rendered in the Symbol instance 

<img width="631" alt="Screenshot 2019-05-10 at 09 40 22" src="https://user-images.githubusercontent.com/6072188/57510948-4cfb9700-7308-11e9-9f9e-69c4de7e8acf.png">

Is it something expected/unexpected? 
What I also expect is to get dynamic rendering of the symbol instance accordingly to the overridden values: for example, given the previous code, if I put an *empty* overridden value for the subtitle field what I expect on the symbol instance is to render accordingly (like React does), so adjust the height of the banner due to the fact the subtitle is not present. 
Last question: how can I force the re-rendering of each symbol instances on all the pages I've in a Document without re-opening each Page?

Do I misunderstand something? 

Sorry for the long comment, thanks in advance 🙃

**Comment by mathieudutour** [comment]
So I think all of those questions can be answered by "that's how Sketch works".

What I'd recommend is to use a separate document to render your react components and then use that document as a Sketch library. Then in another document you can create symbol instances and it should work fine.

**Comment by mpatafio** [comment]
Thanks @mathieudutour !

**Comment by mpatafio** [comment]
Hi, @mathieudutour just one final thing: I followed your suggestion but I get the same issue once the library is updated: all the symbol instances overrides are defaulted once I perform a sync with the library itself. I googled and I guess it's a Sketch problem, do you have any clue on it?

**Comment by mathieudutour** [comment]
So I've been thinking a bit more about it and I think I was wrong:
the issue is that, while the symbol keeps the same ID (good), its layers don't. So when you re-render your component, Sketch sees the same symbol but with completely different layers, and so different overrides. That's why Sketch seems like it's resetting them. It's not actually a reset tho, it's just using the new overrides which do not have a value yet.

I'll try to think how it can be fixed

**Comment by mpatafio** [comment]
Thank you @mathieudutour,

I'm new in Sketch and I'm trying to build up a design system starting from `react-primitives` based Component. I'm not experienced about design systems, but what I imagine is to have a library that contains a set of symbols representing the source of truth of my design. From such library I'd like to instantiate symbol instances, which can be vary for values (component props), such variation can also drive component behaviours in terms of rendering. From the design system what I expect is to manage  master Symbols and keep instances updated with respect to its modifications (by keeping overrides if present).

Since I'm very new about this topic, am I the only one with such needs? 🙃

**Comment by mathieudutour** [comment]
I think `react-sketchapp@3.0.0-beta.9` should be much smarter at trying to preserve IDs. Can you give it a try?

**Comment by mpatafio** [comment]
Sure thing! please let me know!

**Comment by mathieudutour** [comment]
let you know what? I'd rather have you letting me know if your issue is fixed 😄

**Comment by mpatafio** [comment]
Didn't notice beta.9 😅

It works as expected!! thank you so much! 🙌
