### ISSUE TITLE
No Xcode or CLT version detected!

### ISSUE THREAD

**Issue by gazedash** [airbnb/react-sketchapp#425]
You need to mention that Xcode needs to be installed, please add it to README

**Comment by macintoshhelper** [comment]
You can install command line tools with `xcode-select --install`, unless a full install of XCode is needed?

I'm wondering whether this could be avoided with replacing `yoga-layout` with `yoga-layout-prebuilt`.

**Comment by mathieudutour** [comment]
fixed in v3
