### ISSUE TITLE
Is React-Sketchapp still used by its creators?

### ISSUE THREAD

**Issue by zxti** [airbnb/react-sketchapp#426]
Hi, I noticed this project's velocity has slowed down over time - I'm mostly just curious, does Airbnb still use it / have they moved on to other tools?

**Comment by mathieudutour** [comment]
> I noticed this project's velocity has slowed down over time

That's because the project is pretty much "done", it's working fine as is so there is less need to spend time on it

**Comment by codler** [comment]
When will version 3 be released?
