### ISSUE TITLE
borderWidth property doesn't accept px values

### ISSUE THREAD

**Issue by lucaorio** [airbnb/react-sketchapp#428]
I'm note sure if this is intentional, but the `borderWidth` property doesn't get rendered if its value is specified in `px`.

This **works**:
```js
const style = {
  borderWidth: 1,
 // ...
};
```

This **doesn't work**:
```js
const style = {
  borderWidth: '1px',
 // ...
};
```

**Comment by mathieudutour** [comment]
I believe it is intentional because React Native is doing it that way as well and react-sketchapp wants to mimic the RN API as much as possible.
If RN doesn't do that tho, we should fix it for sure

**Comment by macintoshhelper** [comment]
Can confirm that React Native doesn't support `px` values: in some cases it even crashes React Native, but ignoring the property with a warning would probably be best I think. [related issue on react-native repo](https://github.com/facebook/react-native/issues/20206).

If you want to use `px` values, it may be worth using `styled-components/primitives` with this to better mimic web CSS behaviour, or you could create some kind of `StyleSheet.parse()` util function converts the `px` to numbers.
