### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by liucsny** [airbnb/react-sketchapp#429]
Hello, I run 'cd react-sketchapp/examples/basic-setup && npm install' and got an error, how to fix it?

![image](https://user-images.githubusercontent.com/11475340/60965448-748ed000-a348-11e9-9f01-7a30c6cf46ff.png)
![image](https://user-images.githubusercontent.com/11475340/60965642-dd764800-a348-11e9-839e-128bfb1393c0.png)

Sketch version:
Sketch 55

**Comment by ljharb** [comment]
Try node 10 instead of 12.

**Comment by liucsny** [comment]
It works! Thanks a lot 👍
