### ISSUE TITLE
Opacity on Text Views

### ISSUE THREAD

**Issue by ServusJon** [airbnb/react-sketchapp#43]
Opacity change on text views are not working for me.
Anyone else experience that?

**Comment by jongold** [comment]
[Looks like we missed it](https://github.com/airbnb/react-sketchapp/search?utf8=%E2%9C%93&q=opacity&type=) and from ViewRenderer & ImageRenderer too.

I won't have time to fix it until next week at the earliest, but it should be a fun starter contribution if anyone has time to look on it.

**In the meantime, you should be able to use rgba / hsla colors / backgroundColors etc**

TODO:
- [ ] Make a minimal Sketch file with opacity on the layers
- [ ] use something like [`copy-sketch-json`](https://github.com/jongold/copy-sketch-json) to inspect the output and find where opacity is set
- [ ] find the corresponding function in `src/jsonUtils` and add it in
- [ ] also submit a PR to [`sketchapp-json-flow-types`](https://github.com/darknoon/sketchapp-json-flow-types) fixing it

**Comment by dchen** [comment]
I'm working on this.
