### ISSUE TITLE
Input Support

### ISSUE THREAD

**Issue by Math3v** [airbnb/react-sketchapp#431]
_I am..._

| -------------------------------------------------------------------------------------------------
| Requesting a new feature
| -------------------------------------------------------------------------------------------------

**Proposal/Feature-request:**
Add the ability to render an Input element to Sketch.

Is this feature in the backlog? Can I try to hack a prototype together?

**Comment by mathieudutour** [comment]
an input on Sketch is just a View with a border, right?
