### ISSUE TITLE
transform rotate degree doesn't right when gives 45deg.

### ISSUE THREAD

**Issue by shuyankwok** [airbnb/react-sketchapp#433]
I am...Reporting a bug
-----

My code is:
```
const checks = StyleSheet.create({
  normal: {
    position: "relative",
    width: 16,
    height: 16,
    borderWidth: 1,
    borderColor: "#e6e8eb",
    borderRadius: 2,
    backgroundColor: "#fff",
  },
  marker: {
    width: 6,
    height: 10,
    position: "absolute",
    left: 4,
    top: 1,
    borderColor: 'white',
    borderBottomWidth: 2,
    borderRightWidth: 2,
    transform: 'rotate(45)'
  },
  checked: {
    borderColor: '#3370ff',
    backgroundColor: '#3370ff'
  }
});


<View style={[checks.normal, checks.checked]}>
  <View style={[checks.marker]}></View>
</View>

```
I expect the inside `View` will rotate 45deg counter-clock like this:

![image](https://user-images.githubusercontent.com/13088550/62541188-df6df100-b88b-11e9-8704-9386eb1b2172.png)

But I got this one:
![image](https://user-images.githubusercontent.com/13088550/62541246-03313700-b88c-11e9-9d5b-113ec93de2df.png)

The rotation attr in Sketch is shown as `-45`, not `45`.
I tired more degrees like 90, 180, etc, many of them wrong too.

the `react-sketchapp` version is `2.1.2` and Sketch's version is `56.3 (81716)`

**Comment by macintoshhelper** [comment]
I've reproduced this with the same code.

It's parsing the rotation as 45 when converting to Sketch file JSON, but it appears that when Sketch shows "45" in the GUI, the file actually has -45. Inverting fixes this for some rotations, but say 270 is converting to 90 for some reason.

I'm thinking that maybe the transform API could be aligned with React Native, which convert to web nicely with `react-native-web`. https://github.com/facebook/react-native/blob/0ee5f68929610106ee6864baa04ea90be0fc5160/Libraries/Utilities/MatrixMath.js

**Comment by mathieudutour** [comment]
It probably should yes! IIRC I hack together the transform support but there are def some edge cases I might I missed

**Comment by kchetan92** [comment]
I don't see transform property in the Style interface.

**Comment by yuchuanxi** [comment]
I has this bug too

**Comment by mathieudutour** [comment]
it should be fixed in v3.

Do you have a repro somewhere?

**Comment by yuchuanxi** [comment]
@mathieudutour I push to github

https://github.com/yuchuanxi/sketchappTransform
