### ISSUE TITLE
[Feature] add borderPositionType Prop in View Component

### ISSUE THREAD

**Issue by zzzJH** [airbnb/react-sketchapp#439]
_I am..._ a developer. We are restoring the designer's prototype through the sketch plugin. So we need a controllable borderPositionType. It sets the position of the border.

![image](https://user-images.githubusercontent.com/8839694/64837015-0c49bc80-d61f-11e9-9f7b-29a59cda090e.png)

| -------------------------------------------------------------------------------------------------
| Requesting a new feature
| -------------------------------------------------------------------------------------------------

**Proposal/Feature-request:**

![image](https://user-images.githubusercontent.com/8839694/64836817-3babf980-d61e-11e9-86e1-896ea391e030.png)

**Comment by mathieudutour** [comment]
Hum that's not a react native API. Why not just setting the width and height to be 1px bigger?

**Comment by zzzJH** [comment]
> Hum that's not a react native API. Why not just setting the width and height to be 1px bigger?

In fact, it is not the React Native API, and I know what you mean, I have tried to make it bigger. 
But In our design principles, Designer usually uses Inside border in Sketch.
You can see the pictures below, they have very small differences, smaller border radius. The details are important to our designers.
![image](https://user-images.githubusercontent.com/8839694/64848596-277af300-d644-11e9-901b-a08991ae63f3.png)
I know it doesn't seem to be necessary, Because, In the Web, we don't distinguish between Inside and Outside borders, but in Sketch, we distinguish. 
By the way, my goal is to create a Sketch component library that will increase designer productivity. Therefore, meeting the designer is the first requirement.🤷‍♂️

**Comment by mathieudutour** [comment]
I'm sure the difference is indeed very important, but given an "outside" border is usually not something that can be represented in code, I'd say it's better for your designers to specify the design with properties that developers can use?

**Comment by zzzJH** [comment]
> I'm sure the difference is indeed very important, but given an "outside" border is usually not something that can be represented in code, I'd say it's better for your designers to specify the design with properties that developers can use?

Thank you for your reply. Yeah, it should follow what you said. Now, I have to fork a new package to do that.
