### ISSUE TITLE
How to add text style to some characters in between a Text ?

### ISSUE THREAD

**Issue by brijeshb42** [airbnb/react-sketchapp#44]
For adding text styles like bold, italic to whole sentences, it works great. But how can I add a style to some characters in between ?

I am trying to achieve this functionality -

```javascript
<Text style={myStyle}>This is a <bold>word</bold> in a sentence.</Text>
```

**Comment by lelandrichardson** [comment]
Hey @brijeshb42,

Great question! You can do this by nesting `Text` components inside of each other:

```jsx
<Text style={myStyle}>This is a <Text style={{ fontWeight: 'bold' }}>word</Text> in a sentence.</Text>
```

Hope that helps.

**Comment by lelandrichardson** [comment]
Note that you can also use React to make these things more expressive:

```jsx
const Bold = ({ children }) => <Text style={{ fontWeight: 'bold' }}>{children}</Text>

<Text style={myStyle}>This is a <Bold>word</Bold> in a sentence.</Text>

```

**Comment by brijeshb42** [comment]
I tried this previously but this is what I got

<img width="460" alt="screen shot 2017-04-29 at 12 38 40 am" src="https://cloud.githubusercontent.com/assets/717550/25543604/de49ea54-2c74-11e7-985d-a758c5779619.png">

**Comment by lelandrichardson** [comment]
@brijeshb42 you're right. This is not the expected behavior and is a bug.  Will see what we can do about fixing this!

**Comment by lelandrichardson** [comment]
cc @jongold i'm surprised we didn't run into this as an issue. Confirmed that it behaves this way though. We just don't have many internal components that take advantage of this.

**Comment by LincMitch** [comment]
I'm trying to think of a workaround for nested <Text> objects that are formatted. Why not use 
flexbox on 3  
`<Text style={myStyle}>This is a </Text><Bold>word</Bold><Text> in a sentence.</Text>`

myStyle:
`flex-direction: row;
justify-content: flex-start;`

**Comment by jongold** [comment]
I think there's a bug with our text positioning that stops ^^ from working, @LincMitch — could you try it + report back?

**Comment by mathieudutour** [comment]
Just tried
```
<Text style={{flexDirection: 'row' }}>
  This is a <Text style={{fontWeight: 'bold'}}>bold word</Text> in a sentence
</Text>
```

and it's working as expected. I'm wondering if `flexDirection: 'row'` shouldn't be the default style for `Text`?

**Comment by LincMitch** [comment]
Great @mathieudutour that works for nested Text. But only if it's on the same line. In fact this code will force everything onto one line, so doesn't resolve the paragraph issue.
@jongold, not sure what you are asking me to do, was it this?

**Comment by LincMitch** [comment]
One thing I have noticed is that nested Text elements translate to seperate text blocks inside SketchApp. So, can this bug be resolved with a solution based on Text Styles. The result should be one block of text, and for a word to have a different Text Style added to it.

**Comment by mathieudutour** [comment]
> this code will force everything onto one line

you can use
```js
{
  flexDirection: 'row',
  flexWrap: 'wrap'
}
```

it will break between the blocks tho

**Comment by LincMitch** [comment]
I also tried `Wrap`, it's a step closer.

**Comment by DibPuelma** [comment]
Nesting Text components is not possible now, but you can wrap your text in a View like this:

`<View style={{flexDirection: 'row', flexWrap: 'wrap'}}>
    <Text>
        {'Hello '}
    </Text>
    <Text style={{fontWeight: 'bold'}}>
        {'this is a bold text '}
    </Text>
    <Text>
        and this is not
    </Text>
</View>`

I user the strings inside the brackets to force the space between words, but you can also achieve it with marginRight or marginLeft. Hope it helps.

**Comment by ngocht143** [comment]
How to do in case a text which i want to bold is a value of a variable?
For example: this.state.strTest = `{data-from-server}`

**Comment by abdullatif422** [comment]
@ngocht143 I'm also looking for this type of scenario, ex: bold, Italic styles in between of the dynamic data for specific characters.
Any suggestions please how to achieve this..!

**Comment by abdullatif422** [comment]
> How to do in case a text which i want to bold is a value of a variable?
> For example: this.state.strTest = `{data-from-server}`
Following url may be helpful to achieve the requirment
https://github.com/taskrabbit/react-native-parsed-text

**Comment by StrettoFinestra** [comment]
> Just tried
> 
> ```js
> <Text style={{flexDirection: 'row' }}>
>   This is a <Text style={{fontWeight: 'bold'}}>bold word</Text> in a sentence
> </Text>
> ```
> 
> and it's working as expected. I'm wondering if `flexDirection: 'row'` shouldn't be the default style for `Text`? It would solve this bug

You're a boss!

**Comment by nihp** [comment]
I need to decorate a single word in a line

<Text style={[styles.text, textStyle, {backgroundColor: "#d4e9f3"}]}  onPress={(e) => this.onPress(message.content)}>{msg}</Text>

In the message has This is a **[bold](url)** word
