### ISSUE TITLE
Image can't render as expected

### ISSUE THREAD

**Issue by yuchuanxi** [airbnb/react-sketchapp#458]
_I am a PD from china, I use react-sketch to draw product prototype_

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:** 
render image based on given uri

**Observed behavior:**
render nothing

**How to reproduce:** 
just cd react-sketchapp/examples/emotion && npm install && npm run render

**Sketch version:** 
60.1

**Please attach screenshots, a zip file of your project, and/or a link to your github project**
![image](https://user-images.githubusercontent.com/5205912/69932127-d4a72e00-1504-11ea-9c9b-86c6c72c021d.png)

**Comment by mathieudutour** [comment]
should be fixed in v3.0.4

It was because of https://github.com/sketch-hq/sketch-file-format/issues/34

**Comment by yuchuanxi** [comment]
It's work！ Thank You!
