### ISSUE TITLE
TypeError: null is not an object (evaluating 'context.document.currentPage')

### ISSUE THREAD

**Issue by netsi1964** [airbnb/react-sketchapp#46]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

I am running `npm run render` inside one of the examples folder. Every time I get an error in terminal.
![image](https://cloud.githubusercontent.com/assets/114323/25516732/6f8d81bc-2bec-11e7-83a3-759341ec5aeb.png)

**Expected behavior:**
I expected the command to run successfully creating a new plug-in.

**Observed behavior:**
I get this info:
```
npm run render

> profile-cards@ render /Users/sten/Documents/DEV/NODE/react-sketchapp/examples/profile-cards
> skpm build --watch --run

🖨  Copied src/manifest.json in 7ms
Executing post-build scripts
🔨  Built ./main.js in 34314ms
TypeError: null is not an object (evaluating 'context.document.currentPage')
line: 6740
column: 104
```

**How to reproduce:**
1.  Enter one of the example folder
2. Run install and: `npm run render`

**Sketch version:**
43.2 (39069)

**Comment by brijeshb42** [comment]
@netsi1964 You should already have an empty Sketch project open before running `npm run render`.

**Comment by netsi1964** [comment]
Please state that in the instructions when someone wants to test it. And yes - that helped! Here is screenshot where I have altered the Profile Cards example. Great!
![image](https://cloud.githubusercontent.com/assets/114323/25517934/e67cd41c-2bf1-11e7-9abc-a112ef73284a.png)

**Comment by jongold** [comment]
@netsi1964 sorry you ran into that - I need to make the docs clearer :(
