### ISSUE TITLE
skpm@0.9.2 and react-sketchapp incompatibilities

### ISSUE THREAD

**Issue by jschyz** [airbnb/react-sketchapp#47]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

I am upgrade skpm@0.9.2, running `npm run render` inside one of the examples folder.

Observed behavior:
```
npm run render

> basic-setup@1.0.0 render /Users/huihui/project/react-sketchapp/examples/basic-setup
> skpm build --watch --run

🖨  Copied src/manifest.json in 10ms
Executing post-build scripts
🛠  Built ./my-command.js in 1920ms
(null)
```

Sketch version:
43 (38999)

**Comment by mathieudutour** [comment]
Should be fixed in 0.9.4
