### ISSUE TITLE
Cannot style <Text> within <Text>

### ISSUE THREAD

**Issue by varun531** [airbnb/react-sketchapp#474]
_I am..._

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**

A multiline block of text should be able to have an arbitrary word (or words) within it styled separately. i.e.

The quick brown fox\n
jumped over **the**\n
lazy dog

Here the newlines are added for clarity to show where the text might be forced to wrap.

**Observed behavior:**

This just isn't possible. Attempting to nest `<Text>` within `<Text>` results in the following error:

`Error: "sketch_text" is not a valid child for Text components`

**How to reproduce:**

Try to render this code:

`<Text style={{...}}>Text styled one way,<Text style={{...}}>text styled another way.</Text></Text>`

**Sketch version:**

61.2

I feel like this is a reasonable thing to request, because not being able to do so significantly hampers the ability to design things like the following:

<img width="273" alt="Screen Shot 2020-01-20 at 5 13 26 PM" src="https://user-images.githubusercontent.com/113397/72767223-39e3db00-3ba8-11ea-830d-734d6e87eb76.png">

**Comment by varun531** [comment]
Oh, I guess this is technically feasible if you wrap every word in the sentence inside `<Text></Text>`, and you put all the `<Text>word</Text>` within a ` <View style={{flexDirection: 'row', flexWrap: 'wrap'>`

**Comment by mathieudutour** [comment]
Ah I actually changed this bug yesterday, it should be fixed in 3.1.0
