### ISSUE TITLE
Sketch Welcome Screen

### ISSUE THREAD

**Issue by fabb** [airbnb/react-sketchapp#48]
Small bug when Sketch "Welcome" screen is shown on app start.

**Expected behavior:**

Rendering should start normally.

**Observed behavior:**

* `TypeError: null is not an object (evaluating 'context.document.currentPage')`
* Sketch shows welcome screen, but does not render document

**How to reproduce:**

Install Sketch and don't check off "show on every launch" on the "Welcome" screen.

**Sketch version:**

43.2

**Comment by alisonailea** [comment]
This is still happening to me even after turning off the Welcome Screen

**Comment by jongold** [comment]
Does it work if you open a blank document? We have no way of bypassing the Welcome Screen — I've mentioned it to @bomberstudios but we'd need Sketch to help us out :(

**Comment by fabb** [comment]
> Does it work if you open a blank document? 
Unfortunately not

**Comment by jongold** [comment]
Well that seems like a bigger issue :)

Can you try this?
- Open Console.app (find it with Spotlight)
- in the sidebar, select `~/Library/Logs` -> `com.bohemiancoding.sketch3` -> `Plugin Output.log`
- Close & reopen Sketch
- open a blank document
- type `npm run render` in a terminal
- are there any errors in your terminal, or in that Console screen?

**Comment by alisonailea** [comment]
> Close & reopen Sketch
open a blank document
type npm run render in a terminal

That works! I got the styleguide example to load. 

> are there any errors in your terminal, or in that Console screen?
<img width="710" alt="screen shot 2017-05-01 at 8 42 35 am" src="https://cloud.githubusercontent.com/assets/3362490/25584299/401a3172-2e4a-11e7-8da4-104bf284101c.png">

**Comment by vjpr** [comment]
Fixed by disabling welcome screen. This should be added to the getting started guide.

**Comment by macintoshhelper** [comment]
Hi, this seems to solve the issue and bypass the welcome screen:

```jsx
const sketch = require('sketch');

export default () => {
  const documents = sketch.getDocuments();
  let doc = Array.isArray(documents) && documents.length >= 1
    ? documents[0]
    : new sketch.Document();
  doc = doc.sketchObject;

  const data = doc.documentData();
  const pages = doc.pages();
  render(<DocumentContainer colors={theme.colors} />, data);
  data.setCurrentPage(pages.firstObject());
};
```

Maybe this should be added to the getting started docs?

**Comment by mathieudutour** [comment]
I believe you can just do
```js
const sketch = require('sketch');

export default () => {
  const documents = sketch.getDocuments();
  let doc = Array.isArray(documents) && documents.length >= 1 // if there are any open documents
    ? documents[0] // select the last active document
    : new sketch.Document(); // or create a new document

  render(<DocumentContainer colors={theme.colors} />, doc);
  doc.selectedPage = doc.pages[0] // not sure that's necessary?
};
```

**Comment by macintoshhelper** [comment]
Yes, that works too and is cleaner, thanks. The `doc.selectedPage = doc.pages[0]` isn't needed and can be removed, that was left in to resolve some issue I was having in the past. Should I add it to the docs?

**Comment by mathieudutour** [comment]
sure! 🙏
