### ISSUE TITLE
Changelog on GitHub and on website are not synced

### ISSUE THREAD

**Issue by 1st** [airbnb/react-sketchapp#488]
Hello,

I see that here you have the updated version of changeling file: https://github.com/airbnb/react-sketchapp/blob/master/CHANGELOG.md (it contains `v3.1.1`)

But on the website http://airbnb.io/react-sketchapp/CHANGELOG.html it's mention only for `Version 3.0.1`.

Looks that your build mechanism is broken and website pages are not updated from GitHub. Hope that this will help to keep your project better.

**Comment by mathieudutour** [comment]
forgot to publish the docs. Should be fine now

**Comment by 1st** [comment]
> forgot to publish the docs. Should be fine now

Can you setup GitHub actions to do it automatically for you? It will make your life easier, and developers life happier.

Have a good day!

**Comment by mathieudutour** [comment]
The `master` isn’t necessarily what is published so we need to be careful about automatic deployment

**Comment by 1st** [comment]
Then create a “release” branch to have a stable code that is pushed to the public

**Comment by mathieudutour** [comment]
then it's as much work as running `npm run docs:deploy` :)
