### ISSUE TITLE
how can i use linear-gradient 

### ISSUE THREAD

**Issue by juvenyou** [airbnb/react-sketchapp#489]
👋 Hello! 
I try to set linear gradient background for <View>, looks like dosn't work.

<View
    name={`Swatch ${name}`}
    style={{
      height: 96,
      width: 96,
      margin: 4,
      backgroundImage:"linear-gradient(#fff, #000)",
      padding: 8,
    }}> </View>

**Comment by mathieudutour** [comment]
`backgroundImage` is not a valid style property: http://airbnb.io/react-sketchapp/docs/guides/styling.html

You can use `Svg` to get a linear gradient: http://airbnb.io/react-sketchapp/docs/API.html#svg
