### ISSUE TITLE
Keep Sketch Window in Background

### ISSUE THREAD

**Issue by fabb** [airbnb/react-sketchapp#49]
On every save the Sketch window gets active, while the editor loses focus.

**Expected behavior:**

Would be nice if the focus would stay in the text editor, also after saving.

**Observed behavior:**

On every save in the text editor, the re-rendering happens, and the Sketch window becomes active.

**How to reproduce:**

Save.

**Sketch version:**

43.2

**Comment by jongold** [comment]
Like #48, this is a thing we need Sketch to help us with :( cc @bomberstudios

**Comment by jongold** [comment]
🎊  I have this working on a branch of skpm! Will submit a PR shortly :)

**Comment by fabb** [comment]
Awesome!
