### ISSUE TITLE
Invalid prop `error` of type `String` supplied to `RedBox`

### ISSUE THREAD

**Issue by petetnt** [airbnb/react-sketchapp#50]
| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

I opened the `basic-setup` and started playing around it; I tried to change a color and typo'ed it:
```js
Night: '#333:',
```

Something went wrong.

**Expected behavior:**

`RedBox` renders the correct stacktrace

**Observed behavior:**

![image](https://cloud.githubusercontent.com/assets/7641760/25527683/812e71fc-2c22-11e7-9914-8eaaa5b73757.png)

The error fails to render due to supplied a propType error (?)

```
Warning: Failed prop type: Invalid prop `error` of type `String` supplied to `RedBox`, expected instance of `Error`.
    in RedBox
```

**How to reproduce:**

Follow the instructions above

**Sketch version:**

Version 43.2

**Comment by jongold** [comment]
Looks like our errors have errors, thanks for reporting!
