### ISSUE TITLE
What theme is this?!

### ISSUE THREAD

**Issue by gretzky** [airbnb/react-sketchapp#51]
Sincerest apologies that this isn't an issue, but holy god- what texteditor theme is this?? I _need_ it. Hex codes? Something? Been looking high and low for something similar and couldn't even get close.

![tell me](http://i.imgur.com/ZuSRpKl.png)

**Comment by mathieudutour** [comment]
https://github.com/azemoh/atom-one-monokai ?

**Comment by gretzky** [comment]
@mathieudutour It's SO close. 

VSCode
![vscode](http://i.imgur.com/8PS53GM.png)

Atom
![atom](http://i.imgur.com/eqcq21c.png)

**Comment by jongold** [comment]
One Dark. Looks like I was using Atom in that screenshot, using [this version is VSCode now](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark)
