### ISSUE TITLE
Svg import broken

### ISSUE THREAD

**Issue by macintoshhelper** [airbnb/react-sketchapp#515]
_I am..._

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**

![image](https://user-images.githubusercontent.com/6757532/81488125-afa9aa80-925c-11ea-9eb8-8b94061e9d6c.png)

**Observed behavior:**

```sh
> basic-svg@1.0.0 postinstall /Users/<redacted>/basic-svg
> npm run build && skpm-link


> basic-svg@1.0.0 build /Users/<redacted>/basic-svg
> skpm-build

[1/2] 🖨  Copied src/manifest.json in 3ms
error Error while building ./my-command.js
./node_modules/node-gyp-build/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/<redacted>/basic-svg/node_modules/node-gyp-build'
resolve 'fs' in '/Users/<redacted>/basic-svg/node_modules/node-gyp-build'
  Parsed request is a module
  using description file: /Users/<redacted>/basic-svg/node_modules/node-gyp-build/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/<redacted>/basic-svg/node_modules/node-gyp-build/package.json (relative path: .)
    resolve as module

```

**How to reproduce:**

```bash
curl https://codeload.github.com/airbnb/react-sketchapp/tar.gz/master | tar -xz --strip=2 react-sketchapp-master/examples/basic-svg
cd basic-svg
```

**Sketch version:**

`63.1`

**Please attach ~screenshots, a zip file of your project, and~ or a link to your github project**

> https://github.com/airbnb/react-sketchapp/tree/master/examples/basic-svg

**Comment by macintoshhelper** [comment]
I believe this is caused by https://github.com/airbnb/react-sketchapp/blob/9f4b38cdfb7848b32ff9c1968b145dabd72739a9/src/components/index.ts#L8

**Proposed fix:**

```js
import Svg from './Svg';
export { Svg };
```

Fixed in 78c317019391eaa6ea0505c09bdb2e7a2c1ccf76, but may be best to revert and apply in a new atomic PR.

I believe the `import * as Svg` is not actually needed, as this is already handled by applying `static` references at https://github.com/airbnb/react-sketchapp/blob/9f4b38cdfb7848b32ff9c1968b145dabd72739a9/src/components/Svg/Svg.tsx#L49 . On the other hand, I'm surprised that this was working though with `commonjs`, but not with the `es2015` module, there must be some difference in the `commonjs` interop polyfills compared to ES.

**Comment by mathieudutour** [comment]
Wait I’m confused, the error is completely unrelated to the svg import. 

The import * as is on purpose (feature from a previous PR). And I’m not sure how this is going to fix the error

**Comment by macintoshhelper** [comment]
> Wait I’m confused, the error is completely unrelated to the svg import.
> 
> The import * as is on purpose (feature from a previous PR). And I’m not sure how this is going to fix the error

Ah, sorry, that seems to caused by something else. I managed to get rid of it by aliasing `react-sketchapp` to `lib/module`, then was getting this:

![image](https://user-images.githubusercontent.com/6757532/81494444-e1446500-92a0-11ea-9a23-f950bb1624df.png)

And with doing this in the `lib/module/components/index.js` file:

```dif
export { Document } from './Document';
export { Page } from './Page';
export { Artboard } from './Artboard';
export { Image } from './Image';
export { RedBox } from './RedBox';
export { View } from './View';
export { Text } from './Text';
- import * as Svg from './Svg';
+ import Svg from './Svg';
export { Svg };
```

it renders fine

I can only find `import * as Svg` since the platform refactor. `import Svg, { Circle, ... } from 'react-sketchapp/lib/components/Svg'` should still work I think.

**Comment by mathieudutour** [comment]
So the issue is that it's trying to bundle `lib/module/platformBridges/macos.js` but shouldn't (should bundle the sketch bridge instead)

**Comment by mathieudutour** [comment]
Oh I think it's because of
```js
"module": "lib/module/index.js",
"sketch": "lib/module/index.sketch.js",
```
skpm prioritize the `module` entry point instead of the `sketch` one

**Comment by macintoshhelper** [comment]
Ah, great catch, adding `.sketch.js` to the `module` entry seems to solve that issue.

Am still getting `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.` after that though.

**Comment by mathieudutour** [comment]
I'll fix it

**Comment by macintoshhelper** [comment]
Great, thanks 🙂. I've undone the `import Svg from` patch in #516 , that was fixing it for me before, but isn't fixing it now 😕, anyway, that'll break destructuring from `Svg` I think.

**Comment by macintoshhelper** [comment]
Seems the `import Svg from` fix resolves the `Element type is invalid` error.

I just tested destructuring `const { G, Path } = Svg;` with it too, and that seems to still work.

**Comment by macintoshhelper** [comment]
Thanks a lot, ignore my last message. Works now with `3.2.5` 🎉. 

Looks like using `export * from './components';` instead of `export * from './index.common';` helped 🤔, not sure though.

**Comment by Esorakouki** [comment]
@mathieudutour @macintoshhelper I think the latest version does't work completely.
My code does't work when I update react-sketchapp to 3.2.4 or 3.2.5.
![image](https://user-images.githubusercontent.com/15276351/83972097-01ebf300-a911-11ea-8fc1-9d0044648773.png)

The Svg default export was broken.

![image](https://user-images.githubusercontent.com/15276351/83972206-6eff8880-a911-11ea-94cb-c0e67b26576e.png)

I need change my code this way to get the default export(Svg itself).

**Comment by macintoshhelper** [comment]
> The Svg default export was broken.

Hi, I've run into this too (from running the `basic-svg` example). I'm using this code as a manual patch (inside `node_modules`):

```
export { Document } from './Document';
export { Page } from './Page';
export { Artboard } from './Artboard';
export { Image } from './Image';
export { RedBox } from './RedBox';
export { View } from './View';
export { Text } from './Text';
- import * as Svg from './Svg';
+ import Svg from './Svg';
export { Svg };
```

`const { default: SvgContainer } = Svg;` feels pretty unsafe to me, you should be able to use `<Svg>`
