### ISSUE TITLE
Sketch to JSX

### ISSUE THREAD

**Issue by endquote** [airbnb/react-sketchapp#522]
Just a question. `react-sketchapp` renders JSX to Sketch. I'm wondering what efforts are out there to go in the other direction.

I'm imagining that if `react-sketchapp` included metadata in each Sketch document element that identified the source component that it rendered (as an npm module, version, and export), you could read that back from the Sketch file and output appropriate JSX.

Writing such data to the Sketch file might be in the scope of this project, but reading it back out might not be. Just wondering if this or another project might be working on it.

**Comment by mathieudutour** [comment]
there is https://sketch2react.io for example. But it's out of scope of this project indeed.
