### ISSUE TITLE
Npm run render error

### ISSUE THREAD

**Issue by erinjerri** [airbnb/react-sketchapp#56]
I'm using the latest version of Sketch Beta...

When running `npm run render`

I receive the following error

`pm ERR! argv “/usr/local/bin/node” “/usr/local/bin/npm” “run” “dev”
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9

npm ERR! missing script: dev
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:`

**Comment by jongold** [comment]
@erinjerri weiiiird, I haven't seen that before. you're running `npm run render`, not `npm run dev`…which folder are you running it from?

**Comment by erinjerri** [comment]
From he same directory where I installed react sketch app.

**Comment by jongold** [comment]
🤔 can you try opening one of the examples directories?

```
cd examples/basic-setup
npm install
npm run render
```

**Comment by erinjerri** [comment]
@jongold 

Ya that didn't really do anything, tried to reinstall everything. This is from the debug error file inside of the basic setup folder:

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'render' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 verbose run-script [ 'prerender', 'render', 'postrender' ]
5 info lifecycle basic-setup@1.0.0~prerender: basic-setup@1.0.0
6 silly lifecycle basic-setup@1.0.0~prerender: no script for prerender, continuing
7 info lifecycle basic-setup@1.0.0~render: basic-setup@1.0.0
8 verbose lifecycle basic-setup@1.0.0~render: unsafe-perm in lifecycle true
9 verbose lifecycle basic-setup@1.0.0~render: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/LORIMETTE/Desktop/react-sketchapp/examples/basic-setup/node_modules/.bin:/usr/local/fsl/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Library/TeX/texbin
10 verbose lifecycle basic-setup@1.0.0~render: CWD: /Users/LORIMETTE/Desktop/react-sketchapp/examples/basic-setup
11 silly lifecycle basic-setup@1.0.0~render: Args: [ '-c', 'skpm build --watch --run' ]
12 silly lifecycle basic-setup@1.0.0~render: Returned: code: 1  signal: null
13 info lifecycle basic-setup@1.0.0~render: Failed to exec render script
14 verbose stack Error: basic-setup@1.0.0 render: `skpm build --watch --run`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid basic-setup@1.0.0
16 verbose cwd /Users/LORIMETTE/Desktop/react-sketchapp/examples/basic-setup
17 error Darwin 16.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "render"
19 error node v7.2.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error basic-setup@1.0.0 render: `skpm build --watch --run`
22 error Exit status 1
23 error Failed at the basic-setup@1.0.0 render script 'skpm build --watch --run'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the basic-setup package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     skpm build --watch --run
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs basic-setup
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls basic-setup
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by erinjerri** [comment]
Okay so I got the Sketch file to work but my cli shows the same error message

<img width="878" alt="screen shot 2017-05-01 at 3 55 26 pm" src="https://cloud.githubusercontent.com/assets/3184381/25597936/ab241172-2e86-11e7-8f56-d0447f6f7939.png">

**Comment by agisilaos** [comment]
I can confirm this @erinjerri. I encounter the same error!

**Comment by erinjerri** [comment]
I usually use `npm run dev` vs `npm run render` but got the error with `npm run render`.

**Comment by agisilaos** [comment]
I get this error when I run both commands

**Comment by jongold** [comment]
the command you use with `npm run` is set in each project's `package.json` file, so `npm run dev` shouldn't do anything for our examples - we don't set `npm run dev`!

As for why `npm run render` isn't working - still thinking about that - sorry I don't have a solution right now - bear with us 🤔  😭

**Comment by agisilaos** [comment]
No problem @jongold! Will try to think anything that might help. I know that you're doing the best you can.

**Comment by dchen** [comment]
@erinjerri @agisilaos If you can zip up and share your folder so I can try to recreate your environment and reproduce the issue, I can try to help you figure this out.

**Comment by michaelevensen** [comment]
I got this same error when I tried `npm run render` in the main folder but when doing as prescribed:  
```
cd examples/basic-setup
npm install
npm run render
```

It seemed to work.

**Comment by dennylouis** [comment]
I'm getting this error in the terminal when trying to render any of the examples.

```
Admins-Mac-Pro:colors admin$ npm run render

> colors@ render /Users/admin/react-sketchapp/examples/colors
> skpm build --watch --run

🖨  Copied src/manifest.json in 8ms
error Error while running the command after build
2017-05-24 11:14:49.340 coscript[20612:195633655] Exception: (null)

[NOTE: this exception originated in the server.]
[NOTE: this exception originated in the server.]
*** Object does not implement or has different method signature for selector 'hasExtension:'


⛏  Built main.js in 3035ms
```

**Comment by hawkins** [comment]
I'm also running into this error in each example, same as @dennylouis 

Cloned the repo, entered any example directory, installed packages, tried to render.

**Comment by jongold** [comment]
This is a bug with Sketch 44 - we're working on fixing it - #72
