### ISSUE TITLE
Border-radius values always '8' when exporting to SVG

### ISSUE THREAD

**Issue by davidyeiser** [airbnb/react-sketchapp#67]
When I set a border radius on a rectangle it renders as expected, however when I export the element as an SVG the border radius is always `8` unless I manually change it in Sketch. See screenshots below. I'm not sure if this would be a *react-sketchapp* issue though…

**How to reproduce:**
If you use the **basic-setup** example included with the repository: 

1. add a border radius to the Swatch:
````
<View
    name={`Swatch ${name}`}
    style={{
      height: 96,
      width: 96,
      margin: 4,
      backgroundColor: hex,
      padding: 8,
      borderRadius: 11,
    }}
  >
````

2. Choose one of the swatches and change the border radius manually.
3. Export as SVG and view the code.

**Sketch version:**
43.2

<img width="1289" alt="screenshot 2017-05-03 11 32 24" src="https://cloud.githubusercontent.com/assets/175191/25668317/5ba3126e-2ff4-11e7-9254-44bb840339bf.png">
<img width="1199" alt="screenshot 2017-05-03 11 33 12" src="https://cloud.githubusercontent.com/assets/175191/25668316/5ba1503c-2ff4-11e7-9297-3f0e22f10735.png">
<img width="1286" alt="screenshot 2017-05-03 11 32 09" src="https://cloud.githubusercontent.com/assets/175191/25668318/5ba6157c-2ff4-11e7-8f75-e71cbd3ab2b5.png">
<img width="1205" alt="screenshot 2017-05-03 11 33 25" src="https://cloud.githubusercontent.com/assets/175191/25668315/5b96bb68-2ff4-11e7-83f6-97f91f3844ac.png">

**Comment by jongold** [comment]
Whoa - interesting bug! I'd guess that it's something to do with how we're
setting border radiuses.

Note to future me / anyone who wants to look into it
- try using https://github.com/jongold/sketch-diff to diagnose it
- create one file with that example code, save it.
- change the border radius of a shape in the UI, save as a new file
- use sketchdiff to see what changed about the file structure
- if that doesn't look significantly different, try using
https://github.com/jongold/copy-sketch-json to see how we set border radius
vs a 'clean' rectangle

**Comment by dchen** [comment]
The issue is we set the cornerRadius on each point, but fixedRadius is always set to 8. I'll submit a PR to fix.
