### ISSUE TITLE
Add example with Airtable API

### ISSUE THREAD

**Issue by jongold** [airbnb/react-sketchapp#68]
[Airtable](https://airtable.com/) is very cool - I think would be a super low barrier way for people to integrate live data with mockups.

Could either replicate the [GraphCool example](https://github.com/airbnb/react-sketchapp/tree/master/examples/profile-cards-graphql) or do something new & fresh

cc @howietl

**Comment by howietl** [comment]
Heya! That would be rad : ) + @kasrak @jbbakst
