### ISSUE TITLE
Can I generate code from Sketch?

### ISSUE THREAD

**Issue by kevando** [airbnb/react-sketchapp#70]
This looks really awesome and I am already finding it very useful.

I would like to make changes in sketch, and have it generate the react code. Is that something this tool will be able to do eventually? Thanks, Kev

**Comment by dchen** [comment]
Thank you for your feedback. It's unlikely that react-sketchapp will work in this direction anytime soon. Please see related answer in #32 and [the FAQ](http://airbnb.io/react-sketchapp/docs/FAQ.html).
