### ISSUE TITLE
Quickstart is not working

### ISSUE THREAD

**Issue by dstroot** [airbnb/react-sketchapp#88]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

**Expected behavior:**

Quickstart would do something other than fail.  :)

**Observed behavior:**

```
npm run render

> basic-setup@1.0.0 render /Users/Dan/Code/react-sketchapp/examples/basic-setup
> skpm build --watch --run

🖨  Copied src/manifest.json in 6ms
TypeError: null is not an object (evaluating 'context.document.currentPage')
line: 9229
column: 114
```

**How to reproduce:**

```
git clone https://github.com/airbnb/react-sketchapp.git
cd react-sketchapp/examples/basic-setup && npm install
npm run render
```
e.g. Follow quickstart steps...

**Sketch version:**

43.2

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

I just cloned this repo.

**Comment by jongold** [comment]
@dstroot you currently have to have Sketch open to a new document - fix coming soon, sorry for the confusion!

**Comment by dstroot** [comment]
Got it! Thanks!

**Comment by jongold** [comment]
🙌

**Comment by jonmadison** [comment]
oof, still an issue. made a guess on a fix, but still would be great to add that to the documentation
