### ISSUE TITLE
Bidirectional Way of using it

### ISSUE THREAD

**Issue by krstivoja** [airbnb/react-sketchapp#89]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

I am Marko Krstic - Designer

| -------------------------------------------------------------------------------------------------
| Requesting a new feature for Bidirectional way of using it
| -------------------------------------------------------------------------------------------------

Will be nice to have some kind of panel after you select an object so you can edit it and update the code from sketch. And not using it just an browser.

I would like to set up basics with my developers but to be able to work on file with out developers help as well.

Will be so nice and easy to open new artboard from sketch rename it and see it in code.

**Proposal/Feature-request:**

**Comment by dchen** [comment]
@krstivoja Thank you for the suggestion. It's definitely an interesting idea, although it's not currently within the scope of the project. Hopefully third-party projects will be able to accomplish this in combination with react-sketchapp in the future. See [the FAQ](http://airbnb.io/react-sketchapp/docs/FAQ.html) for more notes on this.
