### ISSUE TITLE
Fix component style propTypes

### ISSUE THREAD

**Issue by jongold** [airbnb/react-sketchapp#9]
Currently our components' propTypes are defined as

```js
const propTypes = {
  style: PropTypes.shape({
    ...ViewStylePropTypes
  }),
}
// or
const propTypes = {
  style: PropTypes.shape({
    ...ViewStylePropTypes
  }),
}
```

This totally breaks how styles actually work —
- it fails with an array of styles
- it fails with an ID returned by StyleSheet.create

It's implemented in `react-primitives` [here](https://github.com/lelandrichardson/react-primitives/blob/master/src/propTypes/StyleSheetPropType.js) — either need to copy over the code or maybe extract it to a common package? 🤔

**Comment by hd719** [comment]
Hello I am new to Open source can I work on this?
