### ISSUE TITLE
Unable to use fetch / foursquare-maps example

### ISSUE THREAD

**Issue by nicolasantryhoot** [airbnb/react-sketchapp#90]
I am unable to run the foursquare-maps example in the repo.

After running `npm install` and `npm run render` it displays the following error:

```
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode..
Plugin “react-sketchapp: Foursquare + Google Maps”, line 12175:
» const SuperInit = (0, _runtime.SuperCall)(NSStringFromSelector("init"), [], { type: "@" });
```

I see the same error ( Unexpected keyword 'const'...) if I try to add fetch to basic-example.

Also seeing it in Profile Cards w/GraphQL:

```
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode..
Plugin “react-sketchapp: Profile Cards w/ GraphQL”, line 6801:
» const SuperInit = (0, _runtime.SuperCall)(NSStringFromSelector("init"), [], { type: "@" });
```

I'm using node v7.10.0 and npm 4.2.0

**Comment by jongold** [comment]
@nicolasantryhoot thanks for reporting, sorry for the hiccup 😭  — can confirm I'm seeing this on one of my Macs too 🤔 

I think [cocoascript-class](https://github.com/darknoon/cocoascript-class) should be set up to transpile const -> var, will check it out and get back to you.

**Comment by revolunet** [comment]
same here

**Comment by jongold** [comment]
@darknoon can you take a look at that PR please 🙏

**Comment by darknoon** [comment]
@jongold doesn't seem to solve the fact that transpilation uses `arguments` to transpile `(..args)`, which AFAIK isn't present with cocoascript. Open to other solutions so long as they aren't as hacky as generating a bunch of functions at runtime.

**Comment by mathieudutour** [comment]
what I've done the setTimeout polyfill is just putting a bunch of arguments: https://github.com/skpm/sketch-module-setTimeout-polyfill/blob/master/lib/index.js#L5
Super ugly but eh 🤷‍♂️

**Comment by ljharb** [comment]
One should only pass 2 args to setTimeout ever anyways, for browser compat - but it'd still be nice to support N.

**Comment by mathieudutour** [comment]
closing this in favor of #106
