### ISSUE TITLE
Sketch still blank (react-native + react-primitives)

### ISSUE THREAD

**Issue by exZ** [airbnb/react-sketchapp#93]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

_I am... Developer_

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**
Sketch(app) rendering the react-native components using react-primitive.

**Observed behavior:**
Hello I'm trying to use react-sketchapp with react-primitives and react-native, on simulator everything looks fine, when I try to export a component to sketch I got stuck with this TypeError.

> skpm build --watch --run

🖨  Copied src/manifest.json in 7ms
TypeError: container.replaceAllLayersWithLayers is not a function. (In 'container.replaceAllLayersWithLayers([layer])', 'container.replaceAllLayersWithLayers' is null)
line: 10845
column: 39

⛏  Built ./sketch.js in 2147ms
**How to reproduce:**

[PayWhat.zip](https://github.com/airbnb/react-sketchapp/files/987274/PayWhat.zip)

**Sketch version:**
43.2

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

**Comment by dchen** [comment]
@exZ In the render line of your src/sketch.js file, see this line:
`export default (context) => {
    render(<App message="Hello world!" />, context);
}`

Change it to:

`export default (context) => {
    render(<App message="Hello world!" />, context.document.currentPage());
}`

And then it should run successfully. Let me know if that works or if you need any more help.

**Comment by exZ** [comment]
Ty @dchen! Working like a charm.
