### ISSUE TITLE
Implement Linear Gradient

### ISSUE THREAD

**Issue by zaqqaz** [airbnb/react-sketchapp#94]
Hey there!

Do you have any plans about implementation primitive components for linear-gradient and box-shadow?

**Comment by jongold** [comment]
Hey @zaqqaz! You're totally right, gradients aren't implemented yet.

Shadows are supported, using [react native-style syntax](https://facebook.github.io/react-native/docs/shadow-props.html)

This should work:
```js
const style = {
  shadowColor: 'rgb(0,0,0)',
  shadowOffset: {
    width: 2,
    height: 2,
  },
  shadowOpacity: 0.2,
  shadowRadius: 5,
}
<View style={style} />
```

**Comment by zaqqaz** [comment]
@jongold, yep, see, shadow api same as in RN, cool.
But gradient more interesting component.

Seems, it can be good candidate as a start point - https://github.com/react-native-community/react-native-linear-gradient. (I mean API). What do you think ?
Actually, maybe I will have free time on this weekend and can try to implement it.

**Comment by jongold** [comment]
Ahhhhhh got it - this seems sensible 🤔

@necolas @lelandrichardson any thoughts?

**Comment by necolas** [comment]
In terms of the web, browsers can paint linear gradients using CSS; which is simpler and more performant than using a React component. I'm not familiar with RN's style implementation details/limitations and whether it could add support for linear/radial gradients.

**Comment by zaqqaz** [comment]
@necolas right, but only web is not a 'react as platform' way, isn't it ? 

Actually, `<LinearGradient>` for web should be the same as `<View>` with linear-gradient CSS styles, but for native devices is a little more complicated task, so i think react-native-linear-gradient API is good. 

What about radial gradient, is not implemented yet https://github.com/react-native-community/react-native-linear-gradient/issues/29.

**Comment by tafelito** [comment]
Hi, I was trying to do gradients but it doesn't seem to be working so I wasn't sure why this is closed? Is using SVG the only way to do gradients right now?

**Comment by mathieudutour** [comment]
yes, SVG has a LinearGradient element, just use it

**Comment by tafelito** [comment]
Thanks @mathieudutour that worked!

**Comment by golmakov** [comment]
Hi, is there any samples on how to use linear gradients? 
I really don't understand how can I set gradient background fill to a View

**Comment by isiaapp** [comment]
@golmakov me too. Couldn't you explain how to use it?

**Comment by golmakov** [comment]
@isiaapp linear gradients support in the react-sketch is cumbersome and inelegant.

This code will create 100x100 rectangle with gradient bg:
`import { Svg } from 'react-sketchapp';

// ...

<Svg width="100" height="100">
    <Svg.Defs>
        <Svg.LinearGradient x1="0" x2="0" y1="0" y2="100%" id="gradient">
            <Svg.Stop offset={0} stopColor="#000" stopOpacity={0} />
            <Svg.Stop offset={1} stopColor="#000" stopOpacity={1} />
        </Svg.LinearGradient>
    </Svg.Defs>
    <Svg.Rect fill="url(#gradient)" y="0" x="0" width="100" height="100" />
</Svg>`

**Comment by isiaapp** [comment]
@golmakov thanks, I'll check.
