### ISSUE TITLE
flexBasis has inconsistent behavior between sketch and web

### ISSUE THREAD

**Issue by jlongster** [airbnb/react-sketchapp#98]
**Expected behavior:**

Rendering with `react-primitives` should always be consistent when rendering to sketch and web. I noticed an inconsistency.

I originally filed this in react-primitives [here](https://github.com/lelandrichardson/react-primitives/issues/61) but I thing it's a bug in sketchapp.

If I have rows of cells, and each cell has `flex: 1`, they should all be the same width and always be aligned across rows. This worked in Sketch. Here's how it looked:

<img width="845" alt="screen shot 2017-05-15 at 12 27 14 pm" src="https://cloud.githubusercontent.com/assets/17031/26068893/17e41a6e-396d-11e7-9a0a-f6a84dffae0b.png">

However, rendering the same thing to the web:

<img width="651" alt="screen shot 2017-05-15 at 12 27 48 pm" src="https://cloud.githubusercontent.com/assets/17031/26068902/212459e0-396d-11e7-902e-99aa2b32231a.png">

I discovered that, for the web version at least, I needed to also set `flexBasis: 0` for this to work. But I think that's the correct behavior, so `react-sketchapp`'s flex layout is wrong here.

**How to reproduce:**

Run this code:

```js
import React from 'react';
import { Text, View } from 'react-primitives';

function Row({ children }) {
  return (
    <View style={{ flexDirection: 'row', height: 50 }}>
      <View style={{ borderWidth: 1, borderColor: '#f0f0f0', flex: 1 }} />
      <View style={{ borderWidth: 1, borderColor: '#f0f0f0', flex: 1 }}>
        {children}
      </View>
      <View style={{ borderWidth: 1, borderColor: '#f0f0f0', flex: 1 }} />
      <View style={{ borderWidth: 1, borderColor: '#f0f0f0', flex: 1 }} />
    </View>
  );
}

function Document() {
  return (
    <View style={{ width: 500 }}>
      <Row>hello</Row>
      <Row />
      <Row />
      <Row />
      <Row />
    </View>
  );
}

export default Document;
```

**Sketch version:**

43.2

**Comment by jongold** [comment]
Thanks for reporting — I'm guessing this is a bug either in css-layout or in our usage of css-layout (probably the latter - we're thinking of switching to Yoga soon though #52)  🤔 

Sorry for the bug, will try to take a look at it

**Comment by necolas** [comment]
This was a bug in react-native-web: https://github.com/necolas/react-native-web/commit/88ddeca0c6b8ad8f2f690e07cd4ede7f9a31d1e2

**Comment by jongold** [comment]
Sweet, thanks @necolas — sounds like I can close this?
